// Generated by scripts/generate-apps-catalog.js. Do not edit by hand.
//
// The fallback App Manager reads when apps/registry.json cannot be fetched. Every
// entry is that app's own pixos.app.json, inlined and keyed by id, so this file
// cannot come to disagree with the manifests -- which is what it did for a year,
// naming two files for monaco where its manifest names 98.
//
// `base` is the bootstrap file list, taken from settings/preinstall.json.
(function () {
	window.PIXOS_APP_CATALOG = {
		"base": {
			"name": "base",
			"files": [
				"/apps/jquery-1.11.1.min.js",
				"/apps/jszip.3.10.1.min.js",
				"/apps/file-type.19.0.0.js",
				"/apps/qrcode.js",
				"/apps/fix-webm-duration.js",
				"/apps/explorer/index.html",
				"/apps/explorer/explorer.css",
				"/apps/explorer/js/format.js",
				"/apps/explorer/js/fs-helpers.js",
				"/apps/explorer/js/failure.js",
				"/apps/explorer/js/open-with.js",
				"/apps/explorer/js/context-menu.js",
				"/apps/explorer/js/selection.js",
				"/apps/explorer/js/dnd.js",
				"/apps/explorer/favicon.svg",
				"/apps/app-manager/index.html",
				"/apps/app-manager/favicon.svg",
				"/apps/ace/index.html",
				"/apps/ace/pixos_supported",
				"/apps/7z/js/parse.js",
				"/apps/7z/js/archive.js",
				"/apps/7z/vendor/js7z.js",
				"/apps/7z/vendor/js7z.wasm",
				"/apps/app-catalog.js",
				"/apps/registry.json"
			]
		},
		"ace": {
			"name": "ace",
			"version": "1.1.0",
			"entryPath": "/apps/ace/index.html",
			"files": [
				{
					"path": "/apps/ace/index.html",
					"hash": "sha256:a29b711ccfd4948157daa2db7316e3e881c068300ece4ee94b592f265fd71890"
				},
				{
					"path": "/apps/ace/pixos_supported",
					"hash": "sha256:092eef04a2b0b6f73d4af2bd2ce7d5d82a816536e4e80bf2112c5a98bb95d76c"
				},
				{
					"path": "/apps/ace/pixos.app.json",
					"hash": "sha256:757d549aee327a9a41a3f25b567a73e84b886e395c095e0a7a82124c8c235144"
				}
			],
			"supported": {
				"extensions": [
					"txt",
					"html",
					"css",
					"js"
				]
			},
			"supportsText": true,
			"needsNetwork": true,
			"autosave": true
		},
		"bookmarks": {
			"name": "Bookmarks",
			"version": "1.0.0",
			"entryPath": "/apps/bookmarks/index.html",
			"files": [
				{
					"path": "/apps/bookmarks/favicon.svg",
					"hash": "sha256:c7319c99bed08fce1d62902eaed1b5c56563a1ee813f684aa5f9e742d8194bbf"
				},
				{
					"path": "/apps/bookmarks/index.html",
					"hash": "sha256:5ec41ef0c973b6da0a4409e5d6384571fcbabc29dad233cb266c3eb044fa2055"
				},
				{
					"path": "/apps/bookmarks/js/links.js",
					"hash": "sha256:4ba511e152f9d24785133e8f209b2dba6624e61ba12ed18e7b73ceeb44300836"
				},
				{
					"path": "/apps/bookmarks/pixos.app.json",
					"hash": "sha256:a61355b4b3e5ca61ee8a30a96d2a0c65671fa105df9a30db78bed12d5da23cfc"
				}
			],
			"icon": "/apps/bookmarks/favicon.svg"
		},
		"calendar": {
			"name": "Calendar",
			"version": "1.1.0",
			"entryPath": "/apps/calendar/index.html",
			"files": [
				{
					"path": "/apps/calendar/favicon.svg",
					"hash": "sha256:81744052ca51fe768512a4cbb9a218790d385b7c78e4e79c6ab4be5a73f7b630"
				},
				{
					"path": "/apps/calendar/index.html",
					"hash": "sha256:06867daa24ba4323133068d93640b7658747e642ef623e82d79779fac128b3ff"
				},
				{
					"path": "/apps/calendar/js/calendar.js",
					"hash": "sha256:018a81fae6009a58787bb5d2892a21d03c07c2bcc9303299a7c26f34f26b80f3"
				},
				{
					"path": "/apps/calendar/pixos.app.json",
					"hash": "sha256:546fcc159c642bde6fcc33bda53d975562ff708480e9d642888c6784e44e7ad7"
				}
			],
			"icon": "/apps/calendar/favicon.svg"
		},
		"djvujs": {
			"name": "djvujs",
			"version": "1.0.0",
			"entryPath": "/apps/djvujs/index.html",
			"files": [
				{
					"path": "/apps/djvujs/djvu_viewer.js",
					"hash": "sha256:2d8bff05e37146affdc2428fd476751f002175879a9f918e4d17e5f4e37060a9"
				},
				{
					"path": "/apps/djvujs/djvu.js",
					"hash": "sha256:10a831d62cc7ced39c30c7350a11410402d082a0f0a5b073a88d3d7ca662add3"
				},
				{
					"path": "/apps/djvujs/index.html",
					"hash": "sha256:f134f19b4c1e7587eb562b041ef3bb01c38ff5cad59fb6d5818c6547de7ffb46"
				},
				{
					"path": "/apps/djvujs/pixos_supported",
					"hash": "sha256:416d0ddcaf862139270ee1a45f80b7971fe1de8a5b8d089afe00055331877d03"
				},
				{
					"path": "/apps/djvujs/pixos.app.json",
					"hash": "sha256:3e41c92fc2efcc1f0b9cdbbe2c3b530e42c881340f993471a1bea5421ec6d427"
				}
			],
			"supported": {
				"extensions": [
					"djvu"
				]
			}
		},
		"docx": {
			"name": "docx",
			"version": "1.0.0",
			"entryPath": "/apps/docx/index.html",
			"files": [
				{
					"path": "/apps/docx/docx-preview.js",
					"hash": "sha256:54d515dd012bca75e135119f1a1e9bafcf97211efca649f4221c50bf5fa8c28f"
				},
				{
					"path": "/apps/docx/index.html",
					"hash": "sha256:3aa85889d966e36283be668ce15b33feb8fe21c13a02f7550b2c248c6e44d5c0"
				},
				{
					"path": "/apps/docx/pixos_supported",
					"hash": "sha256:7c98b7fb59c98e21a5fc25357b32e9d21c34f154cf642a7ece74f61587d1fc1b"
				},
				{
					"path": "/apps/docx/pixos.app.json",
					"hash": "sha256:54590f51b58a214e0794a1eadbcb3e8df7e4d11fad3d4ad62f8e8c0a9cdaeedf"
				}
			],
			"supported": {
				"extensions": [
					"doc",
					"docx"
				]
			}
		},
		"emulatorjs": {
			"name": "EmulatorJS",
			"version": "1.0.1",
			"entryPath": "/apps/emulatorjs/index.html",
			"files": [
				{
					"path": "/apps/emulatorjs/index.html",
					"hash": "sha256:284fbb97af7450af988bb5be9171de16f77ede4b204baeb66ebd1c0cc22fc8c1"
				},
				{
					"path": "/apps/emulatorjs/pixos_supported",
					"hash": "sha256:1935b8bf474f60301884ac16791feb8d30fec7c6e2233e3aacc7e8073c9a934c"
				},
				{
					"path": "/apps/emulatorjs/pixos.app.json",
					"hash": "sha256:8a5ef2246ec3ba1040835018aef9fd2fd8d7c4a995332dc122738f46430fee52"
				}
			],
			"supported": {
				"extensions": [
					"fds",
					"nes",
					"unif",
					"unf",
					"smc",
					"fig",
					"sfc",
					"gd3",
					"gd7",
					"dx2",
					"bsx",
					"swc",
					"z64",
					"n64",
					"pce",
					"ngp",
					"ngc",
					"ws",
					"wsc",
					"col",
					"cv",
					"d64",
					"nds",
					"gba",
					"gb",
					"z64",
					"n64",
					"gen",
					"zip"
				]
			},
			"needsNetwork": true
		},
		"filmoskop": {
			"name": "Filmoskop",
			"version": "1.2.2",
			"entryPath": "/apps/filmoskop/index.html",
			"files": [
				{
					"path": "/apps/filmoskop/favicon.svg",
					"hash": "sha256:a8cb0d7291933d11a63e09d1d7ed62608a97406429360cdf20f220b06f82d316"
				},
				{
					"path": "/apps/filmoskop/index.html",
					"hash": "sha256:0c373d8556e75bcdc8784eb89a0de1458ac65e25bafbc58e3d1f87649935f6be"
				},
				{
					"path": "/apps/filmoskop/js/deck.js",
					"hash": "sha256:b68cf939b9171508e0c4771d0976a2391cd76af95ebf1a76ea2ca772e774d88d"
				},
				{
					"path": "/apps/filmoskop/pixos_supported",
					"hash": "sha256:7191f53bf8680c3aefe82ee96f5726087975726366f5bbe8dabb304721de441a"
				},
				{
					"path": "/apps/filmoskop/pixos.app.json",
					"hash": "sha256:5caa0ca1876db28987285ef30cc97ad90c2e0ac1328c62628061f746eae1b095"
				},
				{
					"path": "/apps/filmoskop/speaker.html",
					"hash": "sha256:1db5319b05f9923712046b5c6e5ab0ea53db3a3e8ab097761d0065370f09eda5"
				},
				{
					"path": "/apps/filmoskop/vendor/comark.mjs",
					"hash": "sha256:91ccb623c575aad9c9adcd8b5decea2e91a9966b0345a6fa92357d014a3cde83"
				},
				{
					"path": "/apps/filmoskop/vendor/prism.js",
					"hash": "sha256:73ae0c317d81fa9c816168e75e326c7043d8578e8a4f3af63d014e61af20d2c7"
				},
				{
					"path": "/apps/filmoskop/vendor/README.md",
					"hash": "sha256:3b5133c7cdffd44b4e5ab3131f6739ea0ccccef976871d0bac157e9a7da7ff1e"
				}
			],
			"icon": "/apps/filmoskop/favicon.svg",
			"supported": {
				"extensions": [
					"deck.md",
					"md"
				]
			},
			"autosave": true
		},
		"image": {
			"name": "image viewer",
			"version": "1.0.0",
			"entryPath": "/apps/image/index.html",
			"files": [
				{
					"path": "/apps/image/comparator.js",
					"hash": "sha256:87539a783be7daa1086cc45a4814640299db9187dec8adb10d084244e964a078"
				},
				{
					"path": "/apps/image/diff_match_patch_uncompressed.js",
					"hash": "sha256:9a79cf031ac7c2e366416181051acb3e6d2cacf79c5354148f4c71ea20c7e4a3"
				},
				{
					"path": "/apps/image/getDiffImgData.worker.js",
					"hash": "sha256:e9f56069fd039da5595690a2d06c01617c23d69003fc99f9c6b1ed9a16c8684e"
				},
				{
					"path": "/apps/image/getDiffInline.js",
					"hash": "sha256:ab091855d0a12c411e48fbbd571ffe22045d99970b3d3634f3cef2f2a14bc749"
				},
				{
					"path": "/apps/image/image-input.js",
					"hash": "sha256:74a5c220ff5ab0767921de8c92829dd4d4e8318a8d6cfb9f3d7b0a11ef0675a2"
				},
				{
					"path": "/apps/image/index.html",
					"hash": "sha256:c848c0d2bcd11903595b0319bd2c825bdb09ab87298e4cc3a7be03b55f3276a4"
				},
				{
					"path": "/apps/image/paste.js",
					"hash": "sha256:5c197ea974b39531d5f8e924ee99c8dfbec6a360044c26d72eda0d72a00f94ab"
				},
				{
					"path": "/apps/image/pixos_supported",
					"hash": "sha256:c1d40c434a8578b9b7b909e6be126cbae70ef6193e48ac2eb19c4b135ec97498"
				},
				{
					"path": "/apps/image/pixos.app.json",
					"hash": "sha256:a55732906547c7e5314d46ce73ed6566d12ee4f77bd9c538475d91902c925716"
				}
			],
			"supported": {
				"extensions": [
					"jpg",
					"jpeg",
					"png",
					"gif",
					"webp",
					"bmp",
					"svg"
				]
			}
		},
		"jsdos": {
			"name": "JS-DOS",
			"version": "1.0.0",
			"entryPath": "/apps/jsdosv7.5.0/index.html",
			"files": [
				{
					"path": "/apps/jsdosv7.5.0/dosbox.conf",
					"hash": "sha256:cba76f52a1131a369d86c1a8705c84c522a0596741123020eefc7a3dea1d0add"
				},
				{
					"path": "/apps/jsdosv7.5.0/emulators-ui-loader.png",
					"hash": "sha256:f3ca1f50f92c12b8f22427d312f4ef78a177d367e806000984397b68560db8f3"
				},
				{
					"path": "/apps/jsdosv7.5.0/index.html",
					"hash": "sha256:087b0d72d311e7b9eeb70cf29979f7b56a5622e9423ddaa04c5c50c13edcadef"
				},
				{
					"path": "/apps/jsdosv7.5.0/js-dos.css",
					"hash": "sha256:38badc9115872ec723c6e2d04e057d661f5a76990b9c5c5075b6dd63ff58089c"
				},
				{
					"path": "/apps/jsdosv7.5.0/js-dos.js",
					"hash": "sha256:806d74c34fdb16bf9a873c76f8693dfe25dd982e0519437a73bec3b5ff9727a0"
				},
				{
					"path": "/apps/jsdosv7.5.0/js-dos.js.map",
					"hash": "sha256:c07ce9a3c9dafdf64d6fb6e9c087d8dcfb1dcfc71c35f490f102cbb75afd51bb"
				},
				{
					"path": "/apps/jsdosv7.5.0/pixos_supported",
					"hash": "sha256:808b0bbd3c76ff533d47ab9646e71280ab70f192b186138ecd9b5b8b3ce34f4a"
				},
				{
					"path": "/apps/jsdosv7.5.0/pixos.app.json",
					"hash": "sha256:a2ce8dc54c52817553acd2df9d4498068052024771abb42a409c5d137eb06ce0"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/backend/v7/latency.d.ts",
					"hash": "sha256:76b83d4a3e8c030ffafe299164822ef6fc4eb1fd2863512a2250bbe6c28aa309"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/backend/v7/personal.d.ts",
					"hash": "sha256:98f5e81d5b0f0b982455f29184fe995d9549526ba022752f56890a9c4a11a578"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/backend/v7/v7-config.d.ts",
					"hash": "sha256:d3bd3b91d018040c603e1fe277afae1976e88009378529b246621cdce2da05c9"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/action-bar.d.ts",
					"hash": "sha256:b8c3a2cf5e7975b611a79aacc7f62ef4dcdcaa87b48f62da1eaafae441bf1899"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/action-hide.d.ts",
					"hash": "sha256:da8ee502108a9e623780a104fd4b931f4f93ad985a004f6b6aad29f939592eed"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/action-save-or-exit.d.ts",
					"hash": "sha256:f92aa7e7e84d4e08f97173d3c29a636fa7aed2569c19759fb4ce68fa5fac0098"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/client.d.ts",
					"hash": "sha256:18f0cca9efc11f04feafe939da83960bd4582da2e50010b8453d767da32f0874"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/controls.d.ts",
					"hash": "sha256:0e92b881fbff4942e2bc517ffb8009427936f7223616d4baeed240b89e7adef5"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/cpu-control.d.ts",
					"hash": "sha256:2741e2302c7942c354ff26a12cdcbabd7ebe6a2d6b3ae6baad97e0b190c3a2cf"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/horizontal-slider.d.ts",
					"hash": "sha256:2bf3f9f7372894dcbf6292cd9ef4df0a51aa4cceea1b8c1d22acc0cd15b4ec2e"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/region.d.ts",
					"hash": "sha256:54bc5a7327063068f1510acb5b0612557ae7024ae14db6a9a646c1c5427a0132"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/scale-control.d.ts",
					"hash": "sha256:36539fbe36a5eb6865df8b57f46ef00be9a6a3d40f5f07b837a296014694ab1d"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sensitivity-control.d.ts",
					"hash": "sha256:04b4c28cdbffad1c6390eea60c17ab4a21ae9c4adc577023fd2d3ee7891763f9"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar.d.ts",
					"hash": "sha256:40bec86686ab8b1fc9642747a8f505d610bd4c89b4eaed4acb4c8a612e69f1c7"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/latency-info.d.ts",
					"hash": "sha256:9f8ac5285a7881af54ab2278c3c389fb4a6b21385a161a17a1da420b2f158f60"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/main.d.ts",
					"hash": "sha256:c8eda60df6c48590696ff2ea4a798e8fad36b5056e5420cb3fa6b776b2055b3f"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/networking.d.ts",
					"hash": "sha256:4507775da18eb46b358e0da58059bed6c3342c6eaba8f602076a5714cd25b024"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/token/token-add-time.d.ts",
					"hash": "sha256:4eb045901632d6072605d1b2117daf8ac67ca08a3e139e1b2a8bd95f6829d094"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/token/token-select.d.ts",
					"hash": "sha256:e7689bc90c9b61a62e83b2f58ee986253dd89ccf773cd3e04d2a7d2061248491"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sidebar/token/token.d.ts",
					"hash": "sha256:85c2e06825a8027eb935b1bc7aa632a6ed3619a5c48f10a13aef36ea3bb1b9ca"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/sync-control.d.ts",
					"hash": "sha256:6b230afe51f9c4af764c487c0b7791e4984b617d3d6e2886b4d91d56b79865ab"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/tip.d.ts",
					"hash": "sha256:ab19394e66fcc1633664a5331666ce89c391484091e424f2ac4dec567bbd017b"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/vertical-slider.d.ts",
					"hash": "sha256:468c449bc7e9bdde1c7f7e9484d6b36eb1cb4a85786c5e6ce194f4e91d461745"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/components/volume-control.d.ts",
					"hash": "sha256:de1f295aae1e5b23ca257d6bb84772afc4dfd1978fc151fabedf0bdc3dfd2f40"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/dom.d.ts",
					"hash": "sha256:e406ec0baddafcbe79bccf17e9d8b3bb0cfe00a51f64dc34c08497ab5f05a453"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/hardware-transport-layer.d.ts",
					"hash": "sha256:7a6a39a63084cca04ba3d377444829572ff9f977a121f48f261c8a425391abea"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/icons.d.ts",
					"hash": "sha256:3a7c23ab97e6c3c9f312ca2fe6da079abf98460d3da923c0a89b0d0def95280f"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/player-app.d.ts",
					"hash": "sha256:d20ac8aeebfd50a006566622bcad9cb8a9f34c8ecd73b2fc051f0933167583ae"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/player.d.ts",
					"hash": "sha256:32ed8f45f56a2dcc2d1865a42bb46930fb85ca542a9f688af10b5a3380b8af9a"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/request.d.ts",
					"hash": "sha256:2a1e21e5bbdd04e91d848cc60a0ee7183fb42f3e38ce4bb8b3c97ba40a6f3996"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/src/xhr.d.ts",
					"hash": "sha256:556c2ec07b9652e27f5ce50558b24257338f76fa6a9a899f082b053a16ee1949"
				},
				{
					"path": "/apps/jsdosv7.5.0/types/v7-services/src/personal.d.ts",
					"hash": "sha256:0a33b02ddd3c89ff5775fa35027e3cc775fcf9e3ae197ecd520ff837154b63e4"
				},
				{
					"path": "/apps/jsdosv7.5.0/wdosbox.js",
					"hash": "sha256:80c871923d6265625a4ca3ee9799c2a856eeae6a88fc535a100fd5d98c004abc"
				},
				{
					"path": "/apps/jsdosv7.5.0/wdosbox.js.symbols",
					"hash": "sha256:8e026e8603c3bec4935d7f85c415db961a936e2c0b6b43e5d8f9666b7bede64f"
				},
				{
					"path": "/apps/jsdosv7.5.0/wdosbox.wasm",
					"hash": "sha256:5a932a483cc366ce581ff3bee46a2e775fa315a8fb492dffb3029594ea2472bf"
				}
			],
			"supported": {
				"extensions": [
					"jsdos",
					"zip"
				]
			}
		},
		"luckySheet": {
			"name": "luckySheet",
			"version": "1.1.0",
			"entryPath": "/apps/luckySheet/index.html",
			"files": [
				{
					"path": "/apps/luckySheet/CHANGELOG.md",
					"hash": "sha256:74e3c65f244c1d5b37adccd152fab3c699917a99fd4140a679162e562fdae18a"
				},
				{
					"path": "/apps/luckySheet/chartmix.css",
					"hash": "sha256:7e666ccd4be227541018be8b77ae8672dce09eb04a781b9de3dd1890774402fe"
				},
				{
					"path": "/apps/luckySheet/chartmix.umd.min.js",
					"hash": "sha256:fd32adf065d097fd4d9bb7495a414ccd11d7a95c97bdb7b0d48f5fa23b528683"
				},
				{
					"path": "/apps/luckySheet/CLAUDE.md",
					"hash": "sha256:9de200ada922e2980f19e5101a1ac24f8874512ac8a0d02322142bc614b8a8d7"
				},
				{
					"path": "/apps/luckySheet/echarts@4.8.0__dist__echarts.min.js",
					"hash": "sha256:b7e1783dd2adc8595e9f5ffb81460f25c328fe0fef8e1043f8accc847633146b"
				},
				{
					"path": "/apps/luckySheet/element-ui@2.13.2__lib__index.js",
					"hash": "sha256:9beb98a3adc5088200a98eea9b1cd77b00333efa17a075139a295d8b261632c7"
				},
				{
					"path": "/apps/luckySheet/element-ui@2.13.2__lib__theme-chalk__index.css",
					"hash": "sha256:6c77054732e2287e9fd3579bce6318c3c8499586aecaca283010e864428eae14"
				},
				{
					"path": "/apps/luckySheet/exceljs.umd.js",
					"hash": "sha256:7e49da68588e250dbb8bba190d2caa8ab3787cc0284bda1d8b2f805c4df742c9"
				},
				{
					"path": "/apps/luckySheet/export.js",
					"hash": "sha256:1b143dab14b399306bf37160eaf6f259b0c4018869edee661b846c8e647e30e8"
				},
				{
					"path": "/apps/luckySheet/fontawesome-webfont.woff2",
					"hash": "sha256:2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe"
				},
				{
					"path": "/apps/luckySheet/iconfont.css",
					"hash": "sha256:959ec0d7960590ba276307bcbcff4377ae09f8fd3988119785b5a9a0ab68549c"
				},
				{
					"path": "/apps/luckySheet/index.html",
					"hash": "sha256:b638fd9608aed76ca181d1fe36266ccf8ea510369e1fbe2a0da4cce9ea66341e"
				},
				{
					"path": "/apps/luckySheet/luckyexcel.umd.js",
					"hash": "sha256:fb1d198e983cbaf76fc93cd0e81a24a8170f6903963ef8d31f09986ee677bb10"
				},
				{
					"path": "/apps/luckySheet/luckysheet.css",
					"hash": "sha256:d34fd2f59035b9c0d047a0a364e216713530efab92d1ad91b2581c411b20ab2d"
				},
				{
					"path": "/apps/luckySheet/luckysheet.umd.js",
					"hash": "sha256:2b376a7e1ef448625fd0836b384d64d4985900929c1dbeab4817e2dcbf193a3d"
				},
				{
					"path": "/apps/luckySheet/pixos_supported",
					"hash": "sha256:20cc38965cad2df4253254656483c4b16952874a350670d77ba153aa20397119"
				},
				{
					"path": "/apps/luckySheet/pixos.app.json",
					"hash": "sha256:4143034ee0e3aef316408a6f02f31a9ae7372630f1199f07a94cfdb4da334661"
				},
				{
					"path": "/apps/luckySheet/plugin.js",
					"hash": "sha256:4a9447188e3915a74af139b0f63bad6b37933cf63678aaa8118ae0331169943a"
				},
				{
					"path": "/apps/luckySheet/plugins.css",
					"hash": "sha256:03b506a9c5be0b4f661e9f8e9c4880084d7a172b3be18d06568c324064f7117d"
				},
				{
					"path": "/apps/luckySheet/pluginsCss.css",
					"hash": "sha256:c5d129fc3406acfa16316aa9b988a0bbefc343c6823654a99e3b09d447b2f4a5"
				},
				{
					"path": "/apps/luckySheet/sheetjs-export.js",
					"hash": "sha256:7c25bb6554facdebcc94f86af0cf6985b70a2951ce186eaa98828f2cfcbee73a"
				},
				{
					"path": "/apps/luckySheet/sheetjs-import.js",
					"hash": "sha256:46b1d5307221a261cd097538414dcea95060085b84ff7905d4a40967f8ab491a"
				},
				{
					"path": "/apps/luckySheet/unpkg.com__vuex@3.4.0__dist__vuex.min.js",
					"hash": "sha256:3c28a5e22a0bd8df2845298cd8969f98d74de5ddc0cdfdd2411f419f608ec212"
				},
				{
					"path": "/apps/luckySheet/vue@2.6.11__dist__vue.min.js",
					"hash": "sha256:9e0156dd49c03744e79bbea60eebbbb94b5811c1b71b91f5fb38a8270dedfbaf"
				},
				{
					"path": "/apps/luckySheet/vuex@3.4.0__dist__vuex.min.js",
					"hash": "sha256:3c28a5e22a0bd8df2845298cd8969f98d74de5ddc0cdfdd2411f419f608ec212"
				},
				{
					"path": "/apps/luckySheet/waffle_sprite.png",
					"hash": "sha256:5b2f8581f3db2de166cbcbadf3e4256167ffb43d897d22e327840f9cd1d16405"
				},
				{
					"path": "/apps/luckySheet/xlsx.full.min.js",
					"hash": "sha256:c9506197caf809a075b6dee1da0d36fb19da7158ffe8a88e7b0c96c5d8623c99"
				}
			],
			"supported": {
				"extensions": [
					"xlsx",
					"xlsm",
					"xls",
					"csv",
					"tsv",
					"txt",
					"ods",
					"xlsb"
				]
			}
		},
		"markdown-viewer": {
			"name": "Markdown Viewer",
			"version": "1.0.0",
			"entryPath": "/apps/markdown-viewer/index.html",
			"files": [
				{
					"path": "/apps/markdown-viewer/favicon.svg",
					"hash": "sha256:9f30980daef1f63a12dd55c8febd8d9873183ee70bb0e8020835bd90ef1d21be"
				},
				{
					"path": "/apps/markdown-viewer/index.html",
					"hash": "sha256:b516cee9c8a8f7d7d6e62dfb20f13723d5ae1583e601da2dd8e96656b2cdef61"
				},
				{
					"path": "/apps/markdown-viewer/js/markdown.js",
					"hash": "sha256:3a4923dc2b4e44069c2673015119a377fc4f0fe7e3d3b828cc30f8d3a68a8df4"
				},
				{
					"path": "/apps/markdown-viewer/pixos_supported",
					"hash": "sha256:0eee160b6a3871cd9cca4d1fac71a4552148d15e4cf53a385784421165fc67c5"
				},
				{
					"path": "/apps/markdown-viewer/pixos.app.json",
					"hash": "sha256:407f03ec2dc4861eb20ea80e72b4c5913cb145a7d879163568b718275f705152"
				}
			],
			"icon": "/apps/markdown-viewer/favicon.svg",
			"supported": {
				"extensions": [
					"md",
					"markdown",
					"mdown",
					"mkd"
				]
			}
		},
		"media-player": {
			"name": "Media Player",
			"version": "1.0.1",
			"entryPath": "/apps/media-player/index.html",
			"files": [
				{
					"path": "/apps/media-player/assets/butterchurn.js",
					"hash": "sha256:2632a5e827e010d099a5b597fb3c55bb87aaa5c593f4f5bc14084c0ea53286a4"
				},
				{
					"path": "/apps/media-player/assets/butterchurnPresets.min.js",
					"hash": "sha256:d3c26688eae69d9c9f64aca3ccf3c4eff04c9ad6b831534645e371a4aee5a7f7"
				},
				{
					"path": "/apps/media-player/assets/commonjsHelpers.js",
					"hash": "sha256:4c81dcd54e7e877a79145c4c6fde30ac0e8d857f412b73f48f6970e5d7eab938"
				},
				{
					"path": "/apps/media-player/assets/index.css",
					"hash": "sha256:58ae5df3faa23de31920974bbcf3093b8aa44a851f2990123b68626ba3f64e60"
				},
				{
					"path": "/apps/media-player/assets/index.js",
					"hash": "sha256:7db2dc0df36a5d11bbdb017e3ced8cac41b1de3f83d7d8a8b00f7a286bff39a1"
				},
				{
					"path": "/apps/media-player/assets/worker.js",
					"hash": "sha256:242931933b757920171cbdfd4ad7a082cfaa6537a0110e707d80d1555eaa0890"
				},
				{
					"path": "/apps/media-player/favicon.svg",
					"hash": "sha256:533792f526a704756fb95f2cc30e2a6e8ac0b1a01a848b8c99ea496264fdcad7"
				},
				{
					"path": "/apps/media-player/index.html",
					"hash": "sha256:ed4c715673fb3dd196ca28cd6c4349da20be3f5c8d18fa0a86ac12f83c7abc3b"
				},
				{
					"path": "/apps/media-player/pixos_supported",
					"hash": "sha256:ee5d42d340ef1a2c269c08c6be4f30dde62fd87df5afbfe90896d0a6e7f32070"
				},
				{
					"path": "/apps/media-player/pixos.app.json",
					"hash": "sha256:43b6f6b6623a18604949a75a8e0071f3318c35e7fc88ffdd65f5be7b5d5c35a4"
				}
			],
			"icon": "/apps/media-player/favicon.svg",
			"supported": {
				"extensions": [
					"mp4",
					"webm",
					"mkv",
					"avi",
					"mov",
					"mp3",
					"m4a",
					"aac",
					"flac",
					"ogg",
					"opus",
					"wav",
					"wma",
					"ts",
					"m2ts",
					"m3u",
					"m3u8"
				]
			}
		},
		"mkvPlayer": {
			"name": "mkv player",
			"version": "1.0.0",
			"entryPath": "/apps/mkv-player/index.html",
			"files": [
				{
					"path": "/apps/mkv-player/index.html",
					"hash": "sha256:3168555cea43219b815203088e35b393292390f2b10f8e2904c077733a741bdc"
				},
				{
					"path": "/apps/mkv-player/index.js",
					"hash": "sha256:6ad99de8221239627a2f6abfa7a008687c1df5c02c1860d2ff04803dd60aebbf"
				},
				{
					"path": "/apps/mkv-player/pixos_supported",
					"hash": "sha256:912c58529c4f7568326117667a95abe865d63f404d6461a55b461f9ed2c3b71f"
				},
				{
					"path": "/apps/mkv-player/pixos.app.json",
					"hash": "sha256:943c087c0cbf72dddc1bbf1b85a90c7eec55e6d9b87c397af13a9ad75d2379f7"
				}
			],
			"supported": {
				"extensions": [
					"mkv"
				]
			}
		},
		"monaco": {
			"name": "monaco",
			"version": "1.2.0",
			"entryPath": "/apps/monaco-cdn/index.html",
			"files": [
				{
					"path": "/apps/monaco-cdn/index.html",
					"hash": "sha256:9dcfed90bc908bc1809b1b1783651da272b4729b640280b2c8a8ab9ed7b998f0"
				},
				{
					"path": "/apps/monaco-cdn/pixos_supported",
					"hash": "sha256:092eef04a2b0b6f73d4af2bd2ce7d5d82a816536e4e80bf2112c5a98bb95d76c"
				},
				{
					"path": "/apps/monaco-cdn/pixos.app.json",
					"hash": "sha256:bdfbbd6ea56d974637c4d35d8a55f68788f884f184a462e067a0ab832f82edbc"
				},
				{
					"path": "/apps/monaco-cdn/vendor/README.md",
					"hash": "sha256:94d8722d57b44a69b05974e3795e4d1fed01519c8d3d8d989fca41b0794cb216"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/base/browser/ui/codicons/codicon/codicon.ttf",
					"hash": "sha256:0f1d5219934e96e83b8db162d60b4d8c09b5de1e7d38031cbafe4a3c0f2889c9"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/base/worker/workerMain.js",
					"hash": "sha256:0a01b12af244f4a118b3fb5fe757be98b254f4d3f18b810a650a02b42ec6324c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/abap/abap.js",
					"hash": "sha256:4a9281fca9ced06ec5c2446d84ac654cd46c12e5b9c1523ade20b42c9bdcaf90"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/apex/apex.js",
					"hash": "sha256:543a90079a527a8e3c3656ddd8e3d840e35d0f568e415faa3745c8e518a0292a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/azcli/azcli.js",
					"hash": "sha256:95fa8d3737c20f957a980ba5662c235318f541a34d22f7a9f78da60c819d1587"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/bat/bat.js",
					"hash": "sha256:6d33e3b5e1e0daa92fa2431533ea237427e6335692bb85a80a572bf0240bcd1c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/bicep/bicep.js",
					"hash": "sha256:e06556197faf9643bfc74892fd3b00a093648581fe2b854ec5d4dd8760923039"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/cameligo/cameligo.js",
					"hash": "sha256:0a6b683527e79c9b4d9746f1a781c70ca9ff3a03003ad685fdad7c1c44756910"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/clojure/clojure.js",
					"hash": "sha256:ad62bc6630a9b3974d03fa98eb321b405aa8979c91ebf391f878aa9c3ddadb5a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/coffee/coffee.js",
					"hash": "sha256:692bb5de3d55582d1d574eb2945b4728810e8cc530792f8ba36ca2a550c763ac"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/cpp/cpp.js",
					"hash": "sha256:49447e995c556ea01f838d0585db3235c111660b4ede632dce44b4d228498e0a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/csharp/csharp.js",
					"hash": "sha256:94f3d5a7ca6c214aaab263558ec6709169b0430c4084ac9085098898ccb4525a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/csp/csp.js",
					"hash": "sha256:eaa64fda54615fb89eb6523e727363d689b0305a1e65be7d3db52aefb56bcbf2"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/css/css.js",
					"hash": "sha256:72be97c175efcd5888184c0d66de61a65a720349a2bba426a64fcceb6e950ce5"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/cypher/cypher.js",
					"hash": "sha256:9b67f9a891350590ff60ce85ac77e12e793188d9e1da4b85cf68e18f508c7d8f"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/dart/dart.js",
					"hash": "sha256:f441319c24a0f208115268d0a5a9e4c168ea2f6681e4bd91948d90a7406403a0"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/dockerfile/dockerfile.js",
					"hash": "sha256:eb821c79fccb1a64ad9bebfadb4c707b36fe40d794110559b10dc7b6de8088ed"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/ecl/ecl.js",
					"hash": "sha256:ebcd773bd68cb5e9169bd81b7f484d5d72d10700147291c90b92fa13e5b2e7f1"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/elixir/elixir.js",
					"hash": "sha256:31afddc0f53c778af44e77e7fc7c8645aa72345dcf51ca8c9fbfb55ed499e008"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/flow9/flow9.js",
					"hash": "sha256:ac14c650b1c98bee78c77356cad6332326a8147a6d1f6d381035a729f66e7859"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/freemarker2/freemarker2.js",
					"hash": "sha256:f6241ca5da914ab2236a80b09181cc572d15f723a4581263b7b5313f61aa16c1"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/fsharp/fsharp.js",
					"hash": "sha256:e28a38991ee25b267a837a7abfd81cb383c82f261ff274b5be08a22e9bb16dc6"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/go/go.js",
					"hash": "sha256:0071120125864169774b6e23e5e1aa47b6c7b80c24aae5d83050e999db8c1728"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/graphql/graphql.js",
					"hash": "sha256:3001192f3be0c7f66632e08094131161d868e98e0676e669dbb8bd84049220ce"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/handlebars/handlebars.js",
					"hash": "sha256:d6d62e675489555ab060f9ab5e91f81af74b9ff3e83eeebb877975ba967b4263"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/hcl/hcl.js",
					"hash": "sha256:75da585935feae0977d78a42d2ff07c46dd6e5abe1c1eb0935426a349fb91415"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/html/html.js",
					"hash": "sha256:4b5e0e6ba55182e080ac15c58006c10596e6b2348c64809b6b654c6696cf0fbf"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/ini/ini.js",
					"hash": "sha256:28eaff43e1328ce0bdcb262f9c3073e236c542038022a3ec35fc83a40d41eaa3"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/java/java.js",
					"hash": "sha256:6b4a08f9e99b11935405b8ce04c4dbb703583c56a29429e99a55b6ae14664816"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/javascript/javascript.js",
					"hash": "sha256:edc4427d470285d3fd9e3e2baa5d882cc489fe6499c3f6732264bc386dd07e6a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/julia/julia.js",
					"hash": "sha256:56f157fe9c8a644657b77c223ecf99a2c31a5351151ec168e8fe7600d31b6cbd"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/kotlin/kotlin.js",
					"hash": "sha256:1c35a9772062b076f0d36774061ecf008c9edb42f38f95f24e790b749237e60d"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/less/less.js",
					"hash": "sha256:32fb140c9b4d82cbfd2714d6aed8ebddd9af0d9dbbaa7ce63026d3995d0705d9"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/lexon/lexon.js",
					"hash": "sha256:d36935595b4f68f2e515f9df70be1776d8606c748dd4b7fece1a308b2bfac293"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/liquid/liquid.js",
					"hash": "sha256:18e15f67522f7b4fd34f96434b35fd72dd662bc5423756c4b8ea10df50877690"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/lua/lua.js",
					"hash": "sha256:64d7654a92eeaafe315a0d08f1a1da0a3c34e805953b10ae34edae399ab800b5"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/m3/m3.js",
					"hash": "sha256:0df543e361eeb57186afbf2d3b6942335b345f02e578a16a2f20ae625fb035cd"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/markdown/markdown.js",
					"hash": "sha256:1d116ad166b29a56de9cd0093561555b5496a630a12eebdffa6ea76232079fe6"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/mdx/mdx.js",
					"hash": "sha256:c61671711dc41925fff28ccc08d648c47c8a92f65a4bd20b1fc002f20a1bde5d"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/mips/mips.js",
					"hash": "sha256:e9ee29765b48eceb02e282a1c20fd9520182e7ef37aa390cbb77b6ec4ebd6d4d"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/msdax/msdax.js",
					"hash": "sha256:09fd6e36922be495b77eb4f5e3bfd8a9c696d3181cf1e6a59d4ff3a012aa078b"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/mysql/mysql.js",
					"hash": "sha256:91c56654f8ea3fc9db203cb87be255542706cab287d4882e23ec3c523b2fb49e"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/objective-c/objective-c.js",
					"hash": "sha256:8eebde4cc1e1fce90c08cd709c1de103520fa3752eae58b074a99e2ed82198f2"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/pascal/pascal.js",
					"hash": "sha256:bc9f86e10316518557081c2ffe209eaa6958ecb9eb8cc752f346d786ae833490"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/pascaligo/pascaligo.js",
					"hash": "sha256:be6aeb4b6a2f0ae6e4cf2b86994316e0047d1d943b5ba1f3af48d978d99d9e07"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/perl/perl.js",
					"hash": "sha256:aef83567e9e58aa10447329fc1bcc54cdd1da816a9b4057ec4a5a6ef940f273c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/pgsql/pgsql.js",
					"hash": "sha256:733f926dd517039b762b372a10080a269341b338870bf34e33391da6d7c30ee4"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/php/php.js",
					"hash": "sha256:64f29dd7fab8bca9f5d1bd3f1f85c52ceffe7aa192ef646fa93fd64af5e50a3c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/pla/pla.js",
					"hash": "sha256:bb6e4661238435a652786f6c8ab9b26266cd55ee31f18e302da89a68a5042ef4"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/postiats/postiats.js",
					"hash": "sha256:d4d2d2f9ef9b6f447a6513ee179b0d1ebe671e7cc9c4bf0578d7cb4ca48b75a0"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/powerquery/powerquery.js",
					"hash": "sha256:875dd7f5d45a573fed65733d9e8df39b1c13b018a2d50fcc90abe86d3cc8f344"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/powershell/powershell.js",
					"hash": "sha256:4cd4f6d7937b178da32c58f400f3c5fb0b1aecab43d04d128538645078f471e6"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/protobuf/protobuf.js",
					"hash": "sha256:54a9b1e2da93eb7cad230a79fee95b9552ec44abe7ce3d65cb5ea363b8853557"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/pug/pug.js",
					"hash": "sha256:7aee49835c7f791fdbc6b9c3145defb841dc0a11cf0e5a47c096b5d35f862b4d"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/python/python.js",
					"hash": "sha256:0d8874e9831410a753f5c1b6ea5df18b790ee94348c3d7a4ff1a9b6ede2c4a61"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/qsharp/qsharp.js",
					"hash": "sha256:f3f15200f4d74711142d96e51fbb6a8f98e3373c1068873bc2d68f3d35e5a525"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/r/r.js",
					"hash": "sha256:ef8943c15f4212b09c2409bb5801509efcbe3bcfb7876ee15c5ce82e3210d878"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/razor/razor.js",
					"hash": "sha256:fe2157163d454d71469000a1634054597e257d2684d42560bc372828e5691bc6"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/redis/redis.js",
					"hash": "sha256:7cae02f4816c91f564ec477da7024d4cea420b4589cd2d1528e931ba385654d6"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/redshift/redshift.js",
					"hash": "sha256:a32e8ab29c40163877a0f796e1ae381a543c9b41112bf64fbf23ba0601673e22"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/restructuredtext/restructuredtext.js",
					"hash": "sha256:80599112a73eaf3c399bdbdb03bd0566c4a120970d3b100bbb5efcf6838d6441"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/ruby/ruby.js",
					"hash": "sha256:260ea0ffdd17c493096f8187a2b9a28214e2fcb58f27126af02d7dfa567c005a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/rust/rust.js",
					"hash": "sha256:28cf6c4170af3045d02eae53b394315d43fdf06f80263c7b0e2522657651531c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/sb/sb.js",
					"hash": "sha256:695888e1a4916adc2bcf77a154bd3633975e5ec6262e959a3d6337414930ecd9"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/scala/scala.js",
					"hash": "sha256:4e16b65c07e890744a4ce51468b51078e362492568dd55a225f5cdfc7a0954c1"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/scheme/scheme.js",
					"hash": "sha256:586c408b10171526d6647b5471d69dcd6e9fe05743be3f5679b2e508d6e4c940"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/scss/scss.js",
					"hash": "sha256:4fc7a3957b02653e9999083c588d011626cfa071463b9b7e869752ae2b826149"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/shell/shell.js",
					"hash": "sha256:85ce2d10eed15befb8e69268b0eba7d3cafa0e22c955f21e5ad1aeba8a7e1820"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/solidity/solidity.js",
					"hash": "sha256:db4df586205f7f6fe09532bc448113c12b9bdfba145b185c7cd06bfc0c83358a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/sophia/sophia.js",
					"hash": "sha256:f654291e79746e5969d9a6bda27c4690850f7c52c5dc7950958591f0d1992b35"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/sparql/sparql.js",
					"hash": "sha256:1d51e2e8163f9c6d3d639e879bd73801ad8b1e6976aa487c4bab6f757b3a4c11"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/sql/sql.js",
					"hash": "sha256:c0461e7035b3287360dda2bfe65314306fdd05106fd9707de16fcaada3252a9e"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/st/st.js",
					"hash": "sha256:4bf002a48dec1a22ca4d4f306d230c8dcd8a2c2b15307dff1ca07355e6c3af30"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/swift/swift.js",
					"hash": "sha256:921223cd77aef0005a2b396c8aa277ac154c392b438ad0229cdf8f4b4dc4ba5b"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/systemverilog/systemverilog.js",
					"hash": "sha256:1c2345e07c4416c8ae314d0bf5c45c914c13d77873c5926d27cb7a277b7ce9e5"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/tcl/tcl.js",
					"hash": "sha256:509a945554fab64a64551b73815c0762da50642b4276845abb51ba256d3ae9de"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/twig/twig.js",
					"hash": "sha256:53f350c87328eceabc393cfd5153ccb419c58069284df0ab3f0d2777c23289a2"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/typescript/typescript.js",
					"hash": "sha256:ee4db8523ed88bccf86613f3dbc8ec7b1345feaa59474240a1c81bf7cd373af8"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/typespec/typespec.js",
					"hash": "sha256:8afb242a50cb80bd765f3d00773ee72ac95e22fbfeeaa4cc49bc22c272428b6b"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/vb/vb.js",
					"hash": "sha256:1d6144ac018fbe02955249425683bda242aa736ec0f796398fdad479d2e71590"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/wgsl/wgsl.js",
					"hash": "sha256:20b8de1d6065e85ab68fc3875fa462627e5e4fc782c881ea373c5b3a8c8d32dc"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/xml/xml.js",
					"hash": "sha256:18b724364ab8d710e379c80bbf698da96f53fe224fbd7c6479f09c115b361ace"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/basic-languages/yaml/yaml.js",
					"hash": "sha256:35c9a0f34335b4f8db8ee6a28a96d5147c47f7b24a702e9f4e8504c08a1fe297"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/editor/editor.main.css",
					"hash": "sha256:05173e18dfdaa4ebff84f6cf01dd9ca7915722b406920e939188116074049afa"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/editor/editor.main.js",
					"hash": "sha256:598cd6093cb1ff8f65b17b3b50077f8cea9aff60cbb2b9084d82dcc60785f0fb"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/css/cssMode.js",
					"hash": "sha256:917c9b6afc79fd9cc55354c2f01912e585d6bddffe98591bad323174dd99efa9"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/css/cssWorker.js",
					"hash": "sha256:06173e1f0c6ba0d567f79f73ff0a8762f8aabcc79992aca7b2c57f5970b0d58a"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/html/htmlMode.js",
					"hash": "sha256:c96916a4d4fff9e11e04cb6648141bc51580c7f48454d27536aea48ab981a8da"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/html/htmlWorker.js",
					"hash": "sha256:91acd78a2204084ee63039b11dd06eead0d7ae5836a92ce3a8a575c497036895"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/json/jsonMode.js",
					"hash": "sha256:93ab918520312e82bd99116c28859a307e600c48c62c78f0162f8a7da1ca392c"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/json/jsonWorker.js",
					"hash": "sha256:2011510aa86d52126e769de62dc1f1147e47740701ddde039398d102db35f350"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/typescript/tsMode.js",
					"hash": "sha256:d516c762930e4e44154bb2c7f1b9ddc2ba09fa90056d3afc6787735882f13d08"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/language/typescript/tsWorker.js",
					"hash": "sha256:c2b665ca25048e1a06b3570f29fc1849b9eccd51590a59713902a7059e5a8848"
				},
				{
					"path": "/apps/monaco-cdn/vendor/vs/loader.js",
					"hash": "sha256:776b5fd6c506078d8a41ba14ea19dca222406332fa1b402381e1af1c31f35841"
				}
			],
			"supported": {
				"extensions": [
					"txt",
					"html",
					"css",
					"js"
				]
			},
			"supportsText": true,
			"autosave": true
		},
		"ocr": {
			"name": "image OCR",
			"version": "1.0.0",
			"entryPath": "/apps/ocr/index.html",
			"files": [
				{
					"path": "/apps/ocr/index.html",
					"hash": "sha256:b2bfb5c0730a524146c2bfa544f018658b0a9e619f85e7dce98078fb25c437dd"
				},
				{
					"path": "/apps/ocr/pixos_supported",
					"hash": "sha256:c1d40c434a8578b9b7b909e6be126cbae70ef6193e48ac2eb19c4b135ec97498"
				},
				{
					"path": "/apps/ocr/pixos.app.json",
					"hash": "sha256:c5bfea46293901df7b1ea3cba500a46be233a2ea05326e277e3f29410c8a3e51"
				},
				{
					"path": "/apps/ocr/tesseract-core-simd-lstm.js",
					"hash": "sha256:4aaf414ae3c2a410df8182c2169b2b6598b06d1fd595df5f1e88a1fbb1c41f52"
				},
				{
					"path": "/apps/ocr/tesseract-core-simd-lstm.wasm.js",
					"hash": "sha256:18797eef96bab787636c40b53efaa445cf5ca1c97abd735c4fd8dc3d03652959"
				},
				{
					"path": "/apps/ocr/tesseract-core.js",
					"hash": "sha256:f3b9b5b49258980aebc2bd4df26bc5389bef7c5f5d29e09bbff0b034aacddddb"
				},
				{
					"path": "/apps/ocr/tesseract-core.wasm.js",
					"hash": "sha256:fe68f746dc186bb19e2c55de3514d3d6c4036ede53488b5a4db00dfe3f75e5f1"
				},
				{
					"path": "/apps/ocr/tesseract.5.1.0.min.js",
					"hash": "sha256:ed178b2478023fcd09eaf5df5ce5fc284cc6a6c60169edc5be13f33fb7823d88"
				},
				{
					"path": "/apps/ocr/tesseract.5.min.js",
					"hash": "sha256:be397e903f26199d428b528e8d834cdca8064f95c82068fa34ec8c4d34fd9de9"
				},
				{
					"path": "/apps/ocr/worker.5.1.0.min.js",
					"hash": "sha256:162d4728065ffb34b69825f895b8a9b4fde3a22a217252fec3a4c3d1effc34e6"
				}
			],
			"supported": {
				"extensions": [
					"jpg",
					"jpeg",
					"png",
					"gif",
					"webp",
					"bmp",
					"svg"
				]
			}
		},
		"photopea": {
			"name": "Photopea",
			"version": "1.1.0",
			"entryPath": "/apps/photopea/index.html",
			"files": [
				{
					"path": "/apps/photopea/index.html",
					"hash": "sha256:4d5242e210931201f52286ca62a97cec3d9f83f190637d44c758a83d1efd141b"
				},
				{
					"path": "/apps/photopea/pixos_supported",
					"hash": "sha256:aa99cd7d398c693fcb173b46563b340a91bef8a5c8f7d1d76186d6c2a48533c3"
				},
				{
					"path": "/apps/photopea/pixos.app.json",
					"hash": "sha256:84355bac6f41be136ecd106f92c6c38d3d8b6fdd42a66cc30ee8cbd90f021fc2"
				}
			],
			"supported": {
				"extensions": [
					"psd",
					"ai",
					"indd",
					"xcf",
					"sketch",
					"xd",
					"fig",
					"kri",
					"clip",
					"pxd",
					"pxz",
					"cdr",
					"ufo",
					"afphoto",
					"svg",
					"eps",
					"pdf",
					"pdn",
					"wmf",
					"emf",
					"png",
					"jpg",
					"jpeg",
					"gif",
					"webp",
					"ico",
					"icns",
					"bmp",
					"avif",
					"heic",
					"jxl",
					"ppm",
					"pgm",
					"pbm",
					"tiff",
					"dds",
					"iff",
					"anim",
					"tga",
					"dng",
					"nef",
					"cr2",
					"cr3",
					"arw",
					"rw2",
					"raf",
					"orf",
					"gpr",
					"3fr",
					"fff"
				]
			}
		},
		"pico8": {
			"name": "pico-8",
			"version": "1.0.0",
			"entryPath": "/apps/pico8/index.html",
			"files": [
				{
					"path": "/apps/pico8/favicon.ico",
					"hash": "sha256:b0d5c561868a54db7147618a69e589174fb3f2ade9648673c3f86ec91159ee75"
				},
				{
					"path": "/apps/pico8/index.html",
					"hash": "sha256:279b59c05a7597018f85a77cccb11d00bce9dce3b9a51e978752a268ef8a9f55"
				},
				{
					"path": "/apps/pico8/pico8_edu_0206b.js",
					"hash": "sha256:c0c97757eedb2a178e86fd0e89e93363740d7b4c5032aafc97af03cb98e1d588"
				},
				{
					"path": "/apps/pico8/pixos_supported",
					"hash": "sha256:33d8344a7135c42aa3876706b908f95b702d83ff53e05e4aaff17c07bf67a98e"
				},
				{
					"path": "/apps/pico8/pixos.app.json",
					"hash": "sha256:60200cc71c0981124ee81854cb250266415dfc9321187d2884dc59ef7dc659a0"
				},
				{
					"path": "/apps/pico8/zoot_idle.gif",
					"hash": "sha256:80e56570685cb2a8cd875bda3ac38346d777b9d08b6543e04487252473a06438"
				},
				{
					"path": "/apps/pico8/zoot_talking.gif",
					"hash": "sha256:ee985ee7fbf3f7a00c4d8ae1ffca160b48a8122fba3bb487468c60e117118d63"
				}
			],
			"supported": {
				"extensions": [
					"png"
				]
			}
		},
		"ppt": {
			"name": "ppt",
			"version": "1.0.0",
			"entryPath": "/apps/ppt/index.html",
			"files": [
				{
					"path": "/apps/ppt/css/nv.d3.min.css",
					"hash": "sha256:d0821b9917df9978a8b377746ada4c15c311c83b1e44bcdfe812809ec5f51bd7"
				},
				{
					"path": "/apps/ppt/css/pptxjs.css",
					"hash": "sha256:c488fb0ec604387bb2a6b8cc8f1e2427dc6e24b2e38cf239b38b10a480195ed3"
				},
				{
					"path": "/apps/ppt/filereader.js",
					"hash": "sha256:96df9b7a2c5801e64fbf4917ea8d10167e22b90de17767352e286e8202737079"
				},
				{
					"path": "/apps/ppt/index.html",
					"hash": "sha256:a03ac600b70aee7ad335b4213ce09af77ac117c9eb7e8a3bc9a139a3770d027e"
				},
				{
					"path": "/apps/ppt/js/d3.min.js",
					"hash": "sha256:46c05e6969d585cd0ecb89f5de826501e7aa574f416a4a1823a500ae0a8254e3"
				},
				{
					"path": "/apps/ppt/js/dingbat.js",
					"hash": "sha256:9c1e836e97bf59bef1246addcc8028744a3abfa4dae82fcf90c0a44414362bf1"
				},
				{
					"path": "/apps/ppt/js/divs2slides.js",
					"hash": "sha256:2362ec53b975a6440f4b402b10f2dadf61ac19ccbe8c64f543cda5b279868e3d"
				},
				{
					"path": "/apps/ppt/js/divs2slides.min.js",
					"hash": "sha256:aebd8d03ecd91d13ca35ada9376dac62a61c56d4e8737d18779c5237ac0ec5d0"
				},
				{
					"path": "/apps/ppt/js/filereader.js",
					"hash": "sha256:96df9b7a2c5801e64fbf4917ea8d10167e22b90de17767352e286e8202737079"
				},
				{
					"path": "/apps/ppt/js/jquery-1.11.3.min.js",
					"hash": "sha256:ecb916133a9376911f10bc5c659952eb0031e457f5df367cde560edbfba38fb8"
				},
				{
					"path": "/apps/ppt/js/jquery.fullscreen-min.js",
					"hash": "sha256:44be3d8f1ec12caf21534ae6a70e387d568d6bf82b77f65e7d7e60635b4890ca"
				},
				{
					"path": "/apps/ppt/js/jszip.min.js",
					"hash": "sha256:215fb2537b13d82daabd46e1ee59ffe4dce90abd0acb0ac5432e77071f422e9c"
				},
				{
					"path": "/apps/ppt/js/nv.d3.min.js",
					"hash": "sha256:a88a6fcf2999cce9654cb119e8c2aa50872cc55da25341099b872f1a788ce233"
				},
				{
					"path": "/apps/ppt/js/pptxjs.js",
					"hash": "sha256:108fb8dca723240f98387d46507dee372fb1146cab71e42678a555e7986ac35e"
				},
				{
					"path": "/apps/ppt/js/pptxjs.min.js",
					"hash": "sha256:845555ec4179f557f0b78822baeffbaa6aa14c303eaaba1def7f608367eaca46"
				},
				{
					"path": "/apps/ppt/LICENSE",
					"hash": "sha256:01a22beb8c63e8e32bf96fe7d80f91fa09ab13b947596ffa268c2a123e8fb9a1"
				},
				{
					"path": "/apps/ppt/pixos_supported",
					"hash": "sha256:3b80543eff5cdffe8e40db5a9dea8daaadf60e9d5317228af8af4254d3de9c5f"
				},
				{
					"path": "/apps/ppt/pixos.app.json",
					"hash": "sha256:68773c7ab30b47c804b96aca988198260470d69281c043e49e34e7e56d852560"
				},
				{
					"path": "/apps/ppt/README.md",
					"hash": "sha256:260ca66cbf1a960bee43644b5c420eb3f6572b4b46fc5e47893fae54f2dcccfc"
				}
			],
			"supported": {
				"extensions": [
					"pptx"
				]
			}
		},
		"ruffle": {
			"name": "ruffle",
			"version": "1.0.0",
			"entryPath": "/apps/ruffle/index.html",
			"files": [
				{
					"path": "/apps/ruffle/25cc2cbaaa5f41229f38.wasm",
					"hash": "sha256:1f5ddef1c9ab81b00a1ad0ded5246a8399a5d80377a692de32419f3da60e2ae0"
				},
				{
					"path": "/apps/ruffle/core.ruffle.4023be96d56a3c732101.js",
					"hash": "sha256:51abe44288fb3f5c32ca8273dc992cfc04f5d8b59ed82e8a3d0f943193010169"
				},
				{
					"path": "/apps/ruffle/core.ruffle.4023be96d56a3c732101.js.map",
					"hash": "sha256:6e3245baa47731e2bc803bbb16ac13ad5ffd1f5a25b3dcb36ee048b190f40c0a"
				},
				{
					"path": "/apps/ruffle/index.html",
					"hash": "sha256:57972490fd794630ce5a73245fcbacbf66b32f1e3e9dc611dd5d6fa6440ef6e0"
				},
				{
					"path": "/apps/ruffle/LICENSE_APACHE",
					"hash": "sha256:62c7a1e35f56406896d7aa7ca52d0cc0d272ac022b5d2796e7d6905db8a3636a"
				},
				{
					"path": "/apps/ruffle/LICENSE_MIT",
					"hash": "sha256:4de9338a7879c68e911742a7d691f0797ff1ef8d8a6fb978b0c711e258fe959c"
				},
				{
					"path": "/apps/ruffle/package.json",
					"hash": "sha256:eaed921991c4024d0964e95e9419f5eeacc7d2e478fd069630a103454c873484"
				},
				{
					"path": "/apps/ruffle/pixos_supported",
					"hash": "sha256:07ea7abf5f305d9a6a77423bcec6df52331c35a8a8f3b33ce2a65880e2f1991e"
				},
				{
					"path": "/apps/ruffle/pixos.app.json",
					"hash": "sha256:53ad30941b62c40598fdc03a4ba46e08bb61a87b6fdcadd6f7d8926916b494fd"
				},
				{
					"path": "/apps/ruffle/README.md",
					"hash": "sha256:986146620686d86b3ef9e404bd7f07dd98f5241c02d66e9e5b96500d5eabe15f"
				},
				{
					"path": "/apps/ruffle/ruffle.js",
					"hash": "sha256:667a9d8ac6dfd2acd359644ec529701cd91de2f3c96fe312df61165884348280"
				},
				{
					"path": "/apps/ruffle/ruffle.js.LICENSE.txt",
					"hash": "sha256:73fae11242ef45ac94fd11e6ec88513f6a6fcee06c8bc319f3e163a0c7f29aa3"
				},
				{
					"path": "/apps/ruffle/ruffle.js.map",
					"hash": "sha256:f377071299d0873d64877aa2d0fe33a3420f966149b9bc67ceec1427352bd38e"
				}
			],
			"supported": {
				"extensions": [
					"swf"
				]
			}
		},
		"sheetjs": {
			"name": "sheetjs",
			"version": "1.0.0",
			"entryPath": "/apps/sheetjs/index.html",
			"files": [
				{
					"path": "/apps/sheetjs/index.html",
					"hash": "sha256:06f8be818ed1086276d8dc656e8f9b68fe059e4f1321626d4e87406a74a1d1ff"
				},
				{
					"path": "/apps/sheetjs/pixos_supported",
					"hash": "sha256:880f8e8678c449a9f7ac1ffa70486ade66cbef01fa396212a49b42eaa5230cb9"
				},
				{
					"path": "/apps/sheetjs/pixos.app.json",
					"hash": "sha256:9967b419f850ab352f478222ce1bd351c6806acb96b733262a4c11a57c66d382"
				},
				{
					"path": "/apps/sheetjs/sheet.js",
					"hash": "sha256:c9506197caf809a075b6dee1da0d36fb19da7158ffe8a88e7b0c96c5d8623c99"
				}
			],
			"supported": {
				"extensions": [
					"csv",
					"xls"
				]
			}
		},
		"system-info": {
			"name": "System Info",
			"version": "1.1.0",
			"entryPath": "/apps/system-info/index.html",
			"files": [
				{
					"path": "/apps/system-info/favicon.svg",
					"hash": "sha256:d497968f63ad5c89841b167b9b7b0ffc5ef847704de22baef9e2f5839918b5dd"
				},
				{
					"path": "/apps/system-info/index.html",
					"hash": "sha256:b8f1fc169a2d440a30acf901363a8138fb2b11f6759f8a3cbaf34f60bf56742e"
				},
				{
					"path": "/apps/system-info/js/probe.js",
					"hash": "sha256:3d6fdec397a69339bf860e601a939ed58845c2699d7376f31fd9b708349ad351"
				},
				{
					"path": "/apps/system-info/pixos.app.json",
					"hash": "sha256:b2a1f9684af015e95bee1dbd2652b336498dd9965e763d3f4705f8bc498e6081"
				}
			],
			"icon": "/apps/system-info/favicon.svg"
		},
		"terminal": {
			"name": "terminal",
			"version": "1.0.0",
			"entryPath": "/apps/terminal/index.html",
			"files": [
				{
					"path": "/apps/terminal/autocomplete_menu.js",
					"hash": "sha256:129401c0eda06dabd14de1991ad5e743381e1e95ddfdb25f2a26a086082df744"
				},
				{
					"path": "/apps/terminal/index.html",
					"hash": "sha256:879ae51c2310fad90f150e8005d0dd698081250aae6bf2a270ddd3706a3b5891"
				},
				{
					"path": "/apps/terminal/jquery.terminal.min.css",
					"hash": "sha256:0b59901af07b7619d0b3ab8675ca5fc9d6751552dd9dd90cb3859a709949e61b"
				},
				{
					"path": "/apps/terminal/jquery.terminal.min.js",
					"hash": "sha256:e66b7f76bf5aa94736a4164588bc11eb8c3ee512dc76c154658b8965dea8a4c9"
				},
				{
					"path": "/apps/terminal/pipe.js",
					"hash": "sha256:141b1971f9c3046d22f38a292839bbe6ffe5ee06951638b9a71332be7ab234f9"
				},
				{
					"path": "/apps/terminal/pixos.app.json",
					"hash": "sha256:9474ddcf375f040d0e730070a2f9baed0929f4e4279b438e41b182f548f22b9a"
				}
			]
		},
		"tic80": {
			"name": "tic80",
			"version": "1.0.0",
			"entryPath": "/apps/tic80-v1.1-html/index.html",
			"files": [
				{
					"path": "/apps/tic80-v1.1-html/index.html",
					"hash": "sha256:f40a8c8a89eed5f451813f62a38c008b63f44eafc6fd95eebb5c2d2aac518ae8"
				},
				{
					"path": "/apps/tic80-v1.1-html/pixos_supported",
					"hash": "sha256:ba40439d4e3b6e47528fc4ea0b40763bdfdd8d99dfdd6ff94fbae9f31a24b2e3"
				},
				{
					"path": "/apps/tic80-v1.1-html/pixos.app.json",
					"hash": "sha256:af4725507c6e48ba8fbe96314b962b069db6bd4c776cf2bb29a6b3e7cdcf3cd8"
				},
				{
					"path": "/apps/tic80-v1.1-html/tic80.js",
					"hash": "sha256:14c2ed64774129f23858e3d964e4ddbacd0457c34e74b19c74a2dcc94fa766b0"
				},
				{
					"path": "/apps/tic80-v1.1-html/tic80.wasm",
					"hash": "sha256:464b1373f5e44836f7e580d25bbbc5955a9bfb880399dc7efcb66a6bdb4e4b56"
				}
			],
			"supported": {
				"extensions": [
					"tic"
				]
			}
		},
		"tinymce": {
			"name": "tinymce",
			"version": "1.2.0",
			"entryPath": "/apps/tinymce-cdn/index.html",
			"files": [
				{
					"path": "/apps/tinymce-cdn/index.html",
					"hash": "sha256:12d834ae92d94c0136ce4a6f3cf849ea8f5605968e01990fa3bbb1002a6fe64a"
				},
				{
					"path": "/apps/tinymce-cdn/pixos_supported",
					"hash": "sha256:95d53ad4efbcc898697e40693e04357cb6b8e54198270fc9d2b1b51227d23b7b"
				},
				{
					"path": "/apps/tinymce-cdn/pixos.app.json",
					"hash": "sha256:7982e3348625664d39e6313ed4ed7930eab67c110155420a3a46996d1c569583"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/README.md",
					"hash": "sha256:f842a38620a8d919a2852664d3005ebbc35bf404e512977683a2bca65a1a23da"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/icons/default/icons.min.js",
					"hash": "sha256:f046dc4ebc739916555327c31649a7dd724b3511da35e1a907b4d92db26dcf4d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/license.md",
					"hash": "sha256:2fcd38ecec1bedcf12c8fc7b6d874537028ae36a03ce9d4e9a243ea8371fe7ea"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/models/dom/model.min.js",
					"hash": "sha256:b3790b8868fea4fae707f8838563ceaa4f191e0b3e704b9b05de507692dd263e"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/notices.txt",
					"hash": "sha256:658de17590bce4a2fa0c158f9780fae02f75309906cdc7e285e05ab9b166f156"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/accordion/plugin.min.js",
					"hash": "sha256:57858305a2339f4c1f0b6d18d624c1868b3645a229c2b092d5a6311e79536cd8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/advlist/plugin.min.js",
					"hash": "sha256:26042b3d1380f8c5b6a8ea3212a6c009f59e211f09032ab7ddccc4866cfda06f"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/anchor/plugin.min.js",
					"hash": "sha256:0cd21f09c1eab48cd1b77bb8de3497f20aae99748bef3145619930990d508dc3"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/autolink/plugin.min.js",
					"hash": "sha256:0c88dbb5b98a8891e671884bd22a2ba227f3d8273520746419c88138ded14d1c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/autoresize/plugin.min.js",
					"hash": "sha256:da703490abb15d2b23bbcf385ee081d3e543953e4c574e241d4ba881c221053f"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/autosave/plugin.min.js",
					"hash": "sha256:1e85f698dd4b5412803acf5147082f83af203ab3d248c1e4bc89dba465e8180c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/charmap/plugin.min.js",
					"hash": "sha256:7777c9d8a94431e2a52937ecf8352d9d595602fe0fe2b81708d3321e30d72a63"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/code/plugin.min.js",
					"hash": "sha256:47daa9d619922549424552e47e0d67a8e94b3b206e1f02a97735839e9bddea9b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/codesample/plugin.min.js",
					"hash": "sha256:0db6b61f20b16bdeec85ec4683dced461aaa16cb2d19fef0d9618252ce8c382e"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/directionality/plugin.min.js",
					"hash": "sha256:e3c25a3170fed894b5c5fcc10ab7ad6a15e0302558e51901da8339a41a7cd57d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/emoticons/js/emojiimages.min.js",
					"hash": "sha256:1a7cf49f6b0da134e9bb86f6b052dfa8e7c19d910c6cb75f7c9a24256d9e4edb"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/emoticons/js/emojis.min.js",
					"hash": "sha256:66f71a7fc7094165772664ff37a327c75090fbc646186b7e89c6e39d0676cdf1"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/emoticons/plugin.min.js",
					"hash": "sha256:9bc0fd5f3c74c6c71072c35d153caa650980fa9d6e46f22232634926d0ef7930"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/fullscreen/plugin.min.js",
					"hash": "sha256:a020850c9524b0109d6c261de7b4f12739b86622cb8dd3f6f1949eb873c7139e"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ar.js",
					"hash": "sha256:aae87ae81e6758bb134912b0488498054cb34f9809cc6befa73c37fe35ebc714"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/bg_BG.js",
					"hash": "sha256:4ed8eaf52d8042a5b06f6e01794bec9c524a385fe54d765e9289b8471332c476"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/bg-BG.js",
					"hash": "sha256:b70f5b6fff279a7264edc6c2b7276fb0fd984cbc0e5ff9e0a2a89ed4ddd0b1fd"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ca.js",
					"hash": "sha256:cf3efbf1918788a56dc7d9672d644f759f55d8a65b66d7faaf5c1093c60c9152"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/cs.js",
					"hash": "sha256:09eabd55f71ab4ba53e0ac5bf0bf7a89296d855b70f1e01ab2b19fca3fe526a3"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/da.js",
					"hash": "sha256:22857b275c79339cff13512254d46d9a19b81bce51c54ff4cfb87f1d25a3cdc7"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/de.js",
					"hash": "sha256:353cea8fef4b2c4aaf42820b0752459a6bd936413381554544006b85cf1e65ad"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/el.js",
					"hash": "sha256:b120fb86ac0200bedcfafa5470090fd1aadf4d3966cf3b8b02ab28ee7d27737d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/en.js",
					"hash": "sha256:74c398ce4d10b08bc1e4166392965c8641c886a36e7cf65386987d4685a44e46"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/es.js",
					"hash": "sha256:621772b620bb646ef9cf9a3b0a1a1f7234fba45af2fe1b350c4dfa2c890a7a50"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/eu.js",
					"hash": "sha256:083fd2a9b10072036c14452e910a965f4db643e08a9580d7b499bb8896359827"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/fa.js",
					"hash": "sha256:e04b73eb0700e42b7095c9e32250e8d318d2972bfbb79daec597855f788f2182"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/fi.js",
					"hash": "sha256:c71edaaae9d774bb349a43b2bdaab0e00a83144a7ab3dcf35a610cd5c22c436b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/fr_FR.js",
					"hash": "sha256:d0b3ad703e750e2a714f3bcae6e5177614c156147bdab044a23d1940477cad0b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/fr-FR.js",
					"hash": "sha256:7dfd0d1e147468b0dfb367b07a9511d26cb4e5f8f912b79577c62f023a913faf"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/he_IL.js",
					"hash": "sha256:6178faac0a53c23af0979468d20175e20211cf547f74d6fabdb5ddc7587793b0"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/he-IL.js",
					"hash": "sha256:bc2e8bc74523d7d8bbc833de218354ede193a8d65cf4a8658ccb1a2a1f92c774"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/hi.js",
					"hash": "sha256:74a1947d455896f2573b00eb8118996b685193fb3684cb1b230b19942595a12c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/hr.js",
					"hash": "sha256:a03e59a0dd65c7529fd167300b31db4eb1d34deecd49823a46219ac65831261c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/hu_HU.js",
					"hash": "sha256:9092e3de8a93654f99ba73e65ca75a9459a547125036d611bea9fb84b74d63b1"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/hu-HU.js",
					"hash": "sha256:9fa01416c50a9a87bd591a20ddca97ab25ed3d258beec7d6736c698e5daf33cb"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/id.js",
					"hash": "sha256:0d53b4a2c7d45ddd8643a798dd395a0f8a6a0722638ef9d15a4a946e3a9d8652"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/it.js",
					"hash": "sha256:813e71b23ae94e74c1e66d854488feb2f5b65bb3748c5bfc2fead35a931954cb"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ja.js",
					"hash": "sha256:92153b640c26154754b4c5d41112542d69b82440ce88d9f7abb55eb47551f63c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/kk.js",
					"hash": "sha256:235da4e4864e9c4f5400ef9afdef877cf9077d6329b73bf3703961dd4faa6dc2"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ko_KR.js",
					"hash": "sha256:9c414069fd55dc6bc4dda5aa25ef13d9364c83b089fd40c818061c282f2e0c90"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ko-KR.js",
					"hash": "sha256:5b1d9a748b6b64c709bb11f1eef44686c94f4b707d6ea8da6273ba4e84badeec"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ms.js",
					"hash": "sha256:137d45cebe18d85f9675ff7b5f94c4b5db7398b65bc2c4a079e20d0397d24f32"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/nb_NO.js",
					"hash": "sha256:bf8343cea466fb0bdd27d8de1b72fc390c3fa1145b2bcd4040f57b7fd94d2952"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/nb-NO.js",
					"hash": "sha256:fc6738ed8b46d5ce40d00d6cb273528aa4d7f5e96f4064d8c661ec4606aaaaac"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/nl.js",
					"hash": "sha256:fcd6bcb64c05598ff1a903dd90cdf9a3cd285d580d436ccf78eff99f0ec053da"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/pl.js",
					"hash": "sha256:6a3cf7148c4467e25f2444c568a51b1445744423ae99ffad8ad432294caa0c45"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/pt_BR.js",
					"hash": "sha256:717dc0b6538a108d1e987909dac97becac841b3e0b908b2b4d9466d71bc9d055"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/pt_PT.js",
					"hash": "sha256:fc4b879cb0d58c58e2708bee5618a037a1a7dc03783b31bfef42d1c5abf15176"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/pt-BR.js",
					"hash": "sha256:dd908a68b989d77ac84b8a7761791eb8cc02b7207a36775913f2d61990bdaaac"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/pt-PT.js",
					"hash": "sha256:985dda81960d37e8b4493adaa27fdaaae6fa2ae65ab3a3c67aa796d3c3a994fb"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ro.js",
					"hash": "sha256:43e2c4e203cd10a44d27ab1dacd69de7febe207b259b756448ef94ada6b7fdf2"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/ru.js",
					"hash": "sha256:4b9dfaceba0f965eea48f1c1b4fe116b753337bc3567b35a8b9ec9e167522076"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/sk.js",
					"hash": "sha256:cde939aca54e3f5027de462f365a36a1f7e55078c46c38a1d8ffdfcce3e8fbc7"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/sl_SI.js",
					"hash": "sha256:e23874b3f5bc1abadf95689f0203186171c8454c7283a31dee1fb2689daea448"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/sl-SI.js",
					"hash": "sha256:a1e978fb9af4d0f3574436f445b1609af4aa0c0ce63813612ce09d27994bdcf8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/sv_SE.js",
					"hash": "sha256:b846f52322216ef35772ad9942f917156ce2c7ca8cf0e6e6c68db5531426dffa"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/sv-SE.js",
					"hash": "sha256:1fdbc66b3c385fe411cab2e5edc8f818eb19f476c452c6b9538cf580751d1084"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/th_TH.js",
					"hash": "sha256:f31074a2ddbb66781ed77f3732010534d38eb6904456c5f1a80544faf8451c63"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/th-TH.js",
					"hash": "sha256:4b7738a4ecb258a9fffd7a8ddd45690a308c15ad4581a21df7b457cd2ed10eba"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/tr.js",
					"hash": "sha256:eb7543620fe39aeedaeb10fb0ca5bb5db6b9c8c62b549a011857dd444d49751e"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/uk.js",
					"hash": "sha256:0d8625dae70a854a24a3b876c8022ecb23a89d0cc864bdbbac1874739308a410"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/vi.js",
					"hash": "sha256:a38410226618792ef52f55c7dbdf5954bf451305aef346c6aaf9b0774effda69"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/zh_CN.js",
					"hash": "sha256:006fd3a2fa6df1f1f8b79d96b196e7e4cb13677ce0d3ae10250322cc272721de"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/zh_TW.js",
					"hash": "sha256:83731a78b55509d7b8b076ed734efe7207c57fea4df482ed36c772009fcb6147"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/zh-CN.js",
					"hash": "sha256:ffb9a1f59afa1564b252f8d76b77e25dfd7cbfa3504bcc4db9b0b9600adca731"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/js/i18n/keynav/zh-TW.js",
					"hash": "sha256:4afedd89b5edf7c685a924f4ae02e26cf021cf5cb42ad3e862aa75a0c2bdad91"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/help/plugin.min.js",
					"hash": "sha256:d8f00ac041218fdfe1909dacc2a8b506961269397a106637d3a71348aff7ba41"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/image/plugin.min.js",
					"hash": "sha256:00fdc11f94a64553a19b24c2cc6f9763272cd16c59ea09af803e0e7aa49ac76b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/importcss/plugin.min.js",
					"hash": "sha256:e35f6df58fc845088237208480ac890c2471f51f344d379dca199397ad101d0f"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/insertdatetime/plugin.min.js",
					"hash": "sha256:5413b8c847fd2a1e0ac374d41510b1513f36e131b33fe62e728a6441ed66b6ca"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/link/plugin.min.js",
					"hash": "sha256:33e0dc25bdab261cc7e53ad8e1f1d4817d1cdecfb66a17191bc6c2ff55b56666"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/lists/plugin.min.js",
					"hash": "sha256:c71815e8f8b7f8804fb8c6396835cb5cab8f1a94fabc4ba7ce6772c465a69847"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/media/plugin.min.js",
					"hash": "sha256:43bcce3455d294de7ff13ac00531b7e890fd094ecfcd0db63caeb70d8ac9567e"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/nonbreaking/plugin.min.js",
					"hash": "sha256:7fcb4a11df8f3afe1a7edfbe0939e306d1123192c3a6fa576173ef07374a31a6"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/pagebreak/plugin.min.js",
					"hash": "sha256:262d42bbfebf2f0aab8dcc9e60a3c2271d4ea3bdbddcf263ed2be356f7718543"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/preview/plugin.min.js",
					"hash": "sha256:e28779a4269a7cd15eb91702638db36dbe256666b485e17ab984011625414af0"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/quickbars/plugin.min.js",
					"hash": "sha256:6157476cb2e71d03883723e3adf68284c1499f710ae88a399a6bd6a339d849b5"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/save/plugin.min.js",
					"hash": "sha256:bbe57897674d638d69ff2fb69374b234fb3a9276b2e6a9fe49d684b11e653c83"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/searchreplace/plugin.min.js",
					"hash": "sha256:677ecac1a7e1be0ad5b30a9c9bf921bb2a89954bff67b02a55b02d9426d56804"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/table/plugin.min.js",
					"hash": "sha256:cb65eaef4b8daa05a381bfd4dd0685b16218ad25df6ff6d4571258599be9803d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/visualblocks/plugin.min.js",
					"hash": "sha256:34792e0ee7ae63ec30205ab2f04c6702fe5a97c028652f5a4085db97aa325691"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/visualchars/plugin.min.js",
					"hash": "sha256:a91c608703daff619b586a90538556ed3ebbf319cb80647136263dd849276788"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/plugins/wordcount/plugin.min.js",
					"hash": "sha256:39767b2a7fa91dbef9f3ea958a57f102d54fb78be0f14735cc2ee37ac80e9ff3"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/dark/content.js",
					"hash": "sha256:143f7d8edb58c441973f08a55b3caa3f7209912a7ac59fd435aefdbb5e16a095"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/dark/content.min.css",
					"hash": "sha256:8ba507276d65640b3b55fc6183c63c0bf6d5a15010711a4acb163e6f3d2fe269"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/default/content.js",
					"hash": "sha256:70abbc227c485613b8a4ca5d394aec9cc7f987f44587cbec71195dca6db6dca3"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/default/content.min.css",
					"hash": "sha256:8fbc7f18efefe59b8b7d692d25e0c4283aa4100eaba292e1cdda0cd32e20fc88"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/document/content.js",
					"hash": "sha256:17b7e8f28929a21ad6f8381cb45fc2bc65bebf4361726be5983e551f5cfcedc9"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/document/content.min.css",
					"hash": "sha256:e85bd15d4415b37ddc129a72f6e70d5462b142a19a69fc40c68111b9406af87d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/tinymce-5-dark/content.js",
					"hash": "sha256:8ce32248f259dd7dda01ea36672b0265fc7384b3991a53596340c6c9b47559f1"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/tinymce-5-dark/content.min.css",
					"hash": "sha256:594677b662a41739e2eef429c8ea24fccfda327ebe6ce6277c174da453d0fcce"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/tinymce-5/content.js",
					"hash": "sha256:cfd3e6ba5ec7241df1c68f76a5b0192aa5089fb68abfa594f72fadadb30d67ac"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/tinymce-5/content.min.css",
					"hash": "sha256:8fbc7f18efefe59b8b7d692d25e0c4283aa4100eaba292e1cdda0cd32e20fc88"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/writer/content.js",
					"hash": "sha256:6e64e16bdc5365f9e243cadf754e25eaa471dbec4727159ea09d4718318d4580"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/content/writer/content.min.css",
					"hash": "sha256:72d046347f68cd058bbaa8246a28826b132d25d4b466891d5296111b82c11682"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/content.inline.js",
					"hash": "sha256:4a9d2c1f137606612c41775acac237ab39f7a1083c2a77687c665f3e6291683b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/content.inline.min.css",
					"hash": "sha256:679af4eab27a518d30c06c451ac8fdab4b347b82cd9d0f4e91fbf12f6da1bee8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/content.js",
					"hash": "sha256:eb5339a5566e040a2f041d82ea462d03eb39578ff78fcb535288189e9158f32d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/content.min.css",
					"hash": "sha256:5c26280af6955140969918ccde41bb16f3b20393f0f01132f73b3f6a55bbd1c2"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/skin.js",
					"hash": "sha256:7bafb6f257a9eea4ac5930ab8d77d0bdbf9cb6b1a2a41a41df6ca9ec01826460"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/skin.min.css",
					"hash": "sha256:495d348c65e313159182a8d0afa3220859d4a24181ff4521fc2d3aaf13390065"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/skin.shadowdom.js",
					"hash": "sha256:e8d7d4fbe2730b55df04bb40bde5b69827da653e213eb642891c961a44cb1f5c"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide-dark/skin.shadowdom.min.css",
					"hash": "sha256:d8a9f2d384edd57a6e04e52cd58bb3f5c4a566da539b08c1eaeb7f918a42c262"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/content.inline.js",
					"hash": "sha256:445175742c6f70fef87cd4b3e0e60a4c409fe6a7b25062d83b2a519f949661fe"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/content.inline.min.css",
					"hash": "sha256:679af4eab27a518d30c06c451ac8fdab4b347b82cd9d0f4e91fbf12f6da1bee8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/content.js",
					"hash": "sha256:35a9999a294293ecf4e29d7e2cd5ee231a69d8e900f0ddb5b94ee10ec6fe194d"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/content.min.css",
					"hash": "sha256:f33bf1a16533c75ea10b95166ba3fabe6fa2063aa4495390c2751f33e9ed8c11"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/skin.js",
					"hash": "sha256:13d6ad5fe69483e801056b7ff0d72b5e8bc777c5a0cae2ff115231e5e8e4171f"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/skin.min.css",
					"hash": "sha256:530b8b09d48d0a0fcfaa3b6a9148ea34d63aa5402f9dff065ca7afb16197fb4b"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/skin.shadowdom.js",
					"hash": "sha256:7d7b34f9979790bd1b7028fc36ef275345f8d59a91e08c85e9941efbba2d37bc"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/oxide/skin.shadowdom.min.css",
					"hash": "sha256:d8a9f2d384edd57a6e04e52cd58bb3f5c4a566da539b08c1eaeb7f918a42c262"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/content.inline.js",
					"hash": "sha256:9a1e44259045051401f2120f4fca303e67510ad425108d301bf3dbdd94ffe1c9"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/content.inline.min.css",
					"hash": "sha256:679af4eab27a518d30c06c451ac8fdab4b347b82cd9d0f4e91fbf12f6da1bee8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/content.js",
					"hash": "sha256:f35c19a94447d7e4768fb0178e66e2d0dd2d73b430871d73fa9ef0b13cb9b792"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/content.min.css",
					"hash": "sha256:3dc58c266128f37299a93b00961f2ed6649eb413c2d7a85803fe6549513b56af"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/skin.js",
					"hash": "sha256:8be73806d669f54794d1c7a54f8becb12b969554ee35a72e2c8c9d0130621d39"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/skin.min.css",
					"hash": "sha256:03aeea60ebf6bf89beb5483d648481f512db8ac3de057e532f691204834d1c65"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/skin.shadowdom.js",
					"hash": "sha256:4848aeb61f2c5c3457ee5489d4d6c8e3d35707b323fd408da8244065ec528051"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5-dark/skin.shadowdom.min.css",
					"hash": "sha256:d8a9f2d384edd57a6e04e52cd58bb3f5c4a566da539b08c1eaeb7f918a42c262"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/content.inline.js",
					"hash": "sha256:a4bdbfec4153a0fce8668e5fce75a2aafa78cf8f99f807830991b4bf13f0bc88"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/content.inline.min.css",
					"hash": "sha256:679af4eab27a518d30c06c451ac8fdab4b347b82cd9d0f4e91fbf12f6da1bee8"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/content.js",
					"hash": "sha256:6e65fb4e04d6964ad8a3f5f8c4d8deb94e03f84247e430711bdb72c4cb718021"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/content.min.css",
					"hash": "sha256:f33bf1a16533c75ea10b95166ba3fabe6fa2063aa4495390c2751f33e9ed8c11"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/skin.js",
					"hash": "sha256:881f771b4131b7175cb1856eee6ba11ca1a333bd26dc9eb839434da1b5637a88"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/skin.min.css",
					"hash": "sha256:96e1d86dc45cc20ee24043ef71102350adc98fea759654ecc5f3ad39765de6a5"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/skin.shadowdom.js",
					"hash": "sha256:5f526cd2523c825a45387d5f850fdbfd4c42d3bda1480161c8cf5eaa6288cd52"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/skins/ui/tinymce-5/skin.shadowdom.min.css",
					"hash": "sha256:d8a9f2d384edd57a6e04e52cd58bb3f5c4a566da539b08c1eaeb7f918a42c262"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/themes/silver/theme.min.js",
					"hash": "sha256:007d3c4ed76a899262e9ca4220ac4bf91076780a3324d3a944f4f3edfc5644c7"
				},
				{
					"path": "/apps/tinymce-cdn/vendor/tinymce/tinymce.min.js",
					"hash": "sha256:9b6e7f2cc56f22229cde2c8b3309c7c8e08a7195c34a8b6e2ba516f1cda56b8c"
				}
			],
			"supported": {
				"extensions": [
					"html"
				]
			},
			"supportedMimeTypes": [
				"text/html"
			]
		},
		"transcriber": {
			"name": "Transcriber",
			"version": "1.0.0",
			"entryPath": "/apps/transcriber/index.html",
			"files": [
				{
					"path": "/apps/transcriber/app.js",
					"hash": "sha256:e8469b70aad2f4bdb3643b1195311f79bf72c5e034f78b395a98afd952e88184"
				},
				{
					"path": "/apps/transcriber/audio-url.js",
					"hash": "sha256:f9e478f8445e8700734a7c7e6d658916a06bec32725fa678d3af2863b268fa20"
				},
				{
					"path": "/apps/transcriber/editor-controller.js",
					"hash": "sha256:f15966581dd59f919a44d2a7f93912529e0e8964664ec0da42fea567f2ef9318"
				},
				{
					"path": "/apps/transcriber/editor.css",
					"hash": "sha256:de80c209aac0dd0b74bfa7b67cbb7eaeaefd8fae38dfd4fe7a1fb1e4c5460a19"
				},
				{
					"path": "/apps/transcriber/gigaam-transcriber.js",
					"hash": "sha256:7e814e86a946b8c014f4efb802941d1187c1a6d8ca8c74d2f63f6259e54d052e"
				},
				{
					"path": "/apps/transcriber/index.html",
					"hash": "sha256:3d0b20a9e9c2845f25aa622a0ffddd2f445346523bbf3cd5562aa252f1668ef2"
				},
				{
					"path": "/apps/transcriber/pixos_supported",
					"hash": "sha256:b61f398662cbd2088435f2a744c2588327e91aa7f69b964ba2534a7da4013b96"
				},
				{
					"path": "/apps/transcriber/pixos.app.json",
					"hash": "sha256:133ed372e4e4ca92acb55d07609ea89adfcf9081f1c391176be038dcc0d058ce"
				},
				{
					"path": "/apps/transcriber/README.md",
					"hash": "sha256:031276b56bc94d9c27b67fc59789959073c5fb53424009e14ec47924d7a43bad"
				},
				{
					"path": "/apps/transcriber/recognizer-worker.js",
					"hash": "sha256:9471617b4a314faf96ea6d532798f5677123497fdc585f2fe83f2668cd2b5853"
				},
				{
					"path": "/apps/transcriber/serve.py",
					"hash": "sha256:218ca915fd015a4282f5d835044d3e0191811f199f15966b99972e2557675f14"
				},
				{
					"path": "/apps/transcriber/service-worker-register.js",
					"hash": "sha256:66c06b60118a114f7d77b84759324a2653783dea7a7e69e72c79903807fb15ee"
				},
				{
					"path": "/apps/transcriber/service-worker.js",
					"hash": "sha256:71be27810fd6c796a023fa51b3e7d3df73e3a76febce215818083753a2027159"
				},
				{
					"path": "/apps/transcriber/share-export.js",
					"hash": "sha256:0ec5d0bd3156b010934c4b007d75d3094eb118f8467805b8687e79ed7b4c0826"
				},
				{
					"path": "/apps/transcriber/sherpa-onnx-asr.js",
					"hash": "sha256:d51ae8e8b756ee5e53423ffada0c9702973f154f561aca7984fe0b12f4060178"
				},
				{
					"path": "/apps/transcriber/sherpa-onnx-vad.js",
					"hash": "sha256:893f01168d529add8318c0a6055cf725e788585fda9b81722564a8c3c3f60e34"
				},
				{
					"path": "/apps/transcriber/sherpa-onnx-wasm.js",
					"hash": "sha256:9bb6efce53e07f77a23a0472cdd6898051c9a1f9143ec4ce93dee2cff11638de"
				},
				{
					"path": "/apps/transcriber/speakers-panel.js",
					"hash": "sha256:d4bdfed77b6e9d6e784ab56acc9484f59175485cbf36fefecfba79bd87ef3c4d"
				},
				{
					"path": "/apps/transcriber/srt.js",
					"hash": "sha256:18a1276c7309852fd31635fbe3ec2297fe08db4366477493470536b5fda4c379"
				},
				{
					"path": "/apps/transcriber/sw-readiness.js",
					"hash": "sha256:77144fb64ce850d1ecb8c34dbbbf7e37db308cc64365bcfef178ca4603d3e8df"
				},
				{
					"path": "/apps/transcriber/transcriber-config.js",
					"hash": "sha256:6eae03308fc519f52b86268956014a86d1c818bfaf0343934ddbe4b45e0d9d29"
				},
				{
					"path": "/apps/transcriber/transcript-model.js",
					"hash": "sha256:098c3c2a2e8044be5de2f122b73132a397171f4913529ba69e3480532f98c170"
				},
				{
					"path": "/apps/transcriber/transcript-panel.js",
					"hash": "sha256:f9b40716cae4a93b9a1311819ce4e44187b11bf1ea0362c4ae8c9ea7716353f8"
				},
				{
					"path": "/apps/transcriber/wasm-assets-config.js",
					"hash": "sha256:98278d3e9abe92259612868173e8bb786cf322d66f0297a484c74a7420813eef"
				},
				{
					"path": "/apps/transcriber/wasm-settings.js",
					"hash": "sha256:0912382bd0f563b08ab5a167a47963a82a6c0e64b63d7a6a4b1be0ea82f25ec0"
				},
				{
					"path": "/apps/transcriber/waveform-view.js",
					"hash": "sha256:e4c0c9fb55b439145747a1b04c3774161cfdb6ffcec144ff64f93107580df890"
				}
			],
			"supported": {
				"extensions": [
					"wav",
					"mp3",
					"m4a",
					"aac",
					"flac",
					"ogg",
					"oga",
					"opus",
					"wma",
					"webm"
				]
			}
		},
		"treemap": {
			"name": "Disk Treemap",
			"version": "1.0.2",
			"entryPath": "/apps/treemap/index.html",
			"files": [
				{
					"path": "/apps/treemap/css/style.css",
					"hash": "sha256:cd07dbe208806ee16ededd3575e9c2600a35bcbfc5ec6a7b705224a517d90a75"
				},
				{
					"path": "/apps/treemap/favicon.svg",
					"hash": "sha256:f291018eb5bd9afa878d189981ad58e4f2f96ce86e963e3c2ce88ebdac661487"
				},
				{
					"path": "/apps/treemap/index.html",
					"hash": "sha256:983b528e72abc6b4cf6e5bb29366ea5e7e09b2f12004611719f460d9a867b4a6"
				},
				{
					"path": "/apps/treemap/js/app.js",
					"hash": "sha256:dbded4b3a7506b2c156304ad4055ad3e6bff85f87ce1228343be0ac6745a5f21"
				},
				{
					"path": "/apps/treemap/js/colors.js",
					"hash": "sha256:bbc6878c4d036631df8bc3497a6ec6899f08a952e0e599d269aface957547265"
				},
				{
					"path": "/apps/treemap/js/format.js",
					"hash": "sha256:2f9bd95af4fad8a0618b06f4739d11ddeab7e5208de2d184803a901153bfe750"
				},
				{
					"path": "/apps/treemap/js/open-file.js",
					"hash": "sha256:fc3b1c63a896c8614246cddbfe220ee16f7acc82ca5a98e9b9cb8d10c0520264"
				},
				{
					"path": "/apps/treemap/js/render.js",
					"hash": "sha256:7c08d43730a3289997482bef5e9f5b63cd562fc73a7b4238475a2c22406c4944"
				},
				{
					"path": "/apps/treemap/js/scan-pixos.js",
					"hash": "sha256:f286645be3644e242d7ef3602775025f932f595b694947aa0c4f824abc98b3f5"
				},
				{
					"path": "/apps/treemap/js/scan.js",
					"hash": "sha256:fc3baa6651d2427e99a3248768ed20ea2471c2b0d02abe9e170d4e150e2253b2"
				},
				{
					"path": "/apps/treemap/js/treemap.js",
					"hash": "sha256:6e4ff9bf7cca99c582f3559713a01d78ca5185dc9171e3c507e62c94062fbff9"
				},
				{
					"path": "/apps/treemap/pixos.app.json",
					"hash": "sha256:78c8f3fd15471d4424662a1c445392fcc81e873f51edf067d5b9e6b86dbdd391"
				},
				{
					"path": "/apps/treemap/test-data/readme.txt",
					"hash": "sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447"
				},
				{
					"path": "/apps/treemap/test-data/subdir/big.bin",
					"hash": "sha256:16fa66a7dc98d93f2a4c5d20baf5177f59c4c37fc62face65690c11c15fe6ff9"
				},
				{
					"path": "/apps/treemap/test-data/subdir/file.js",
					"hash": "sha256:434728a410a78f56fc1b5899c3593436e61ab0c731e9072d95e96db290205e53"
				},
				{
					"path": "/apps/treemap/test-data/subdir/nested/deep.json",
					"hash": "sha256:2396099c6c084fa4b9beac9f0d52cf3be9cf8d47040ef127883d532b5790cd74"
				}
			],
			"icon": "/apps/treemap/favicon.svg",
			"needsNetwork": true
		},
		"vips": {
			"name": "vips",
			"version": "1.0.0",
			"entryPath": "/apps/vips/index.html",
			"files": [
				{
					"path": "/apps/vips/clipboard-2.jpg",
					"hash": "sha256:5d04b85d6195ef1d47c97ace1f483d744527b353fbfab92e27fcedc7156240cc"
				},
				{
					"path": "/apps/vips/clipboard-3.jpg",
					"hash": "sha256:e2112ce452fc94571d5e272f6463d984bd72ab25413e9ec2563773d71fbf1b1a"
				},
				{
					"path": "/apps/vips/clipboard-4.jpg",
					"hash": "sha256:bf0d8cffdb7c4897fd9b7c98b918652bdf20a5d6bef27bdb350afad9fe24bc0a"
				},
				{
					"path": "/apps/vips/index.html",
					"hash": "sha256:e18551a4100d82d8bc318ca88e797a83eb2df7f2e9a20d46e575f9e95bf48074"
				},
				{
					"path": "/apps/vips/pixos.app.json",
					"hash": "sha256:79f4be4ebe286571f0676a2f2580d5a74788343244fb3762ff55eeacd1cba192"
				},
				{
					"path": "/apps/vips/vips-es6.js",
					"hash": "sha256:62d99dfc7b502ae987fea8c29d5e8d822b03bfd3afa9d1365d77786614030f09"
				},
				{
					"path": "/apps/vips/vips-heif.wasm",
					"hash": "sha256:79d6c01981b5754ff3c4ca20d9a96931beedfa71df4999bbae345480eeedf161"
				},
				{
					"path": "/apps/vips/vips-jxl.wasm",
					"hash": "sha256:ceb872e5e5f7529c75a1f33d1681a51c336e869e152cb9b9989f72e2a7524baa"
				},
				{
					"path": "/apps/vips/vips.js",
					"hash": "sha256:700c80d5319ae9509d82e04ea412c579eb94c3766b70fd287282a27fd4408371"
				},
				{
					"path": "/apps/vips/vips.wasm",
					"hash": "sha256:c506a65f476e2ead7d31fcdbb59a6c23ba13e91401edcdadf7f082c24863d2dc"
				}
			]
		},
		"yaReader": {
			"name": "Yandex Book Reader",
			"version": "1.1.0",
			"entryPath": "/apps/ya-book-reader/index.html",
			"files": [
				{
					"path": "/apps/ya-book-reader/CHANGELOG.md",
					"hash": "sha256:3ab50b681bba1702dc8728440ec39d57d4cd4f28b8a1f6970f52af78ddb2d311"
				},
				{
					"path": "/apps/ya-book-reader/CLAUDE.md",
					"hash": "sha256:e4ff4dd65a7daeb2601c43e1e0facbb522ef0e40f13f34956593081c16c579e9"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_cover/images/book_cover.png",
					"hash": "sha256:061469a6346c549cfd9d7cae1c6deb48284da39280f4e7d4373ee73ca00cd260"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_close_hover.png",
					"hash": "sha256:248246f09084dd7b83c1703e4627a3157b63a735e9563bd30ba92b7ee59e72a8"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_close.png",
					"hash": "sha256:810da7c618a86c87ea6c2977e29d2b09de256dd54c7db13c3f75ba9a1c83ca9d"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_minus_hover.png",
					"hash": "sha256:1dc90244201394aad643ef761673e5921d49537ec7446d3d5e0d48f8665b5a55"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_minus.png",
					"hash": "sha256:6dd0c042a9344631c6020f1b908c63739f6ddf48755907d9809c3ec1994aa94f"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_mode_page_hover.png",
					"hash": "sha256:c088e911658c4302929dbf24a7695a052e452f1eee6faef1961f0b8287551582"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_mode_page.png",
					"hash": "sha256:95cd32bdb9dcd53934542ef3d38c883bb9a092f820e952a1112d3404e335c5ae"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_mode_scroll_hover.png",
					"hash": "sha256:e44984a7a092a74417dcbc507e43b61680e2668fe8f1d7210e469ff34b7e6754"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_mode_scroll.png",
					"hash": "sha256:855186eeb38657685ce9a2d3db899c10b1798e48c794cc8b99e31ac5b6055b8b"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_navigation_hover.png",
					"hash": "sha256:c652130b685d7c8425537889bbb5fbd50caa48304ad4e75b834ca76a1fe2d0fd"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_navigation.png",
					"hash": "sha256:77fd2acf37c6f6d1fbbba3daa2993c256cba8f3d6ba1f56f88f7563ea48bdc34"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_open.png",
					"hash": "sha256:cb727eaa478586e043a2dbbc59a77dd1fe76733518f3c0dff3dda9ce0177a81c"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_plus_hover.png",
					"hash": "sha256:d76a2bc23e7d3b7f61afd5f19c2e2e652e4025a8b34c954d459cd4c79b50f2ba"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_action_plus.png",
					"hash": "sha256:d551eb8342e882b2a91a1b9bf3c289f024353d7f37010e014e68ef5310cc4cdf"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_menu/images/menu_delimiter.png",
					"hash": "sha256:591b3f9e8e29b224a893e239e3de923941401fc74670acb2cc2becd5a427eeb5"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_navigation/images/close_button_hover.png",
					"hash": "sha256:a02249a16de13a9c68e93559733b5c763174999c70565f0b455f990052c74532"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_navigation/images/close_button.png",
					"hash": "sha256:820816bedb26a9398f3c254d9491d81810ee98d778c62836bec6015a4190b1bf"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/arrow_left_hover.png",
					"hash": "sha256:57138da6432abe4618a2ee0f8d3ea8e10420e54b0cf3b6a76cbe27b1ddc3a0c4"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/arrow_left.png",
					"hash": "sha256:2285b0322632c3272df72977f6edace2b1a86baa6d1c2d3d4f6309676ff53a26"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/arrow_right_hover.png",
					"hash": "sha256:6e1ae3835d4bedc6c81be0c22bf5f78b8a5781884254f315e3025ee8d500b1ab"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/arrow_right.png",
					"hash": "sha256:5ef355aa73eb1477a3082e5061fe595db059d352f006910ab490c8ca284339e4"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/bookmark_icon_active.png",
					"hash": "sha256:b76d76f9a2f56005af97ffc7b719222432913ef42d7b435048478f9e62cb6c74"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/bookmark_icon_hover.png",
					"hash": "sha256:a5755049c3bdb275bd8ccc336e79a8d15265009de4b46df4261e58395b0de293"
				},
				{
					"path": "/apps/ya-book-reader/elements/reader_page/images/bookmark_icon.png",
					"hash": "sha256:0020967c011459dd30f0be29d73f631ab02255db75c14849b7a8620729929c29"
				},
				{
					"path": "/apps/ya-book-reader/example.fb2.zip",
					"hash": "sha256:2be9593987cf9ce5e7f2c81240654b26958a126cd512d7f8bab96afe3850da36"
				},
				{
					"path": "/apps/ya-book-reader/extensions/keep_alive.js",
					"hash": "sha256:0bb60ec083129046e4d98f3a4b6696e64ce4b9481dca146748ea91d57c80ec07"
				},
				{
					"path": "/apps/ya-book-reader/extensions/keep_alive.mojom.js",
					"hash": "sha256:7a2c0312bcbe8f5b97c31ed1f75dbcb10a2ca65d6671d606ce360f965d3243cd"
				},
				{
					"path": "/apps/ya-book-reader/extensions/mime_handler.mojom.js",
					"hash": "sha256:f63707b85fb9eff4d07c937ad95fdbae42eab85400564ae1dad59c883178ddaf"
				},
				{
					"path": "/apps/ya-book-reader/extensions/mimeHandlerPrivate.js",
					"hash": "sha256:61a9c3486b34361d6ef9681927d1d875a541779bdd8f4e6b588ab9df9fab9321"
				},
				{
					"path": "/apps/ya-book-reader/extensions/mojo_bindings.js",
					"hash": "sha256:6036cf29a7d67eaf94defb80c4b64408b2637bfdf935660500667c0ab4fba968"
				},
				{
					"path": "/apps/ya-book-reader/extensions/uncaught_exception_handler.js",
					"hash": "sha256:903bf007ec2c9348c83a8a71fcb57b8c9aa3d46cea5c05823e8f6d6183ca6636"
				},
				{
					"path": "/apps/ya-book-reader/index.css",
					"hash": "sha256:64baeecdf04a3be54f0d7e8280087028c666d53d9d69e57564075568cba50164"
				},
				{
					"path": "/apps/ya-book-reader/index.html",
					"hash": "sha256:6f79009907e6ceea6fb720201b33e46b43d295502a685c51b7f2b697a149b512"
				},
				{
					"path": "/apps/ya-book-reader/index.js",
					"hash": "sha256:a3b36fbe4adfd3f882876c8a57c709b158b9955b05d82835d489b92a5a261ea1"
				},
				{
					"path": "/apps/ya-book-reader/pixos_supported",
					"hash": "sha256:1bebcefea3460fbfa27e648c08bfaa8ca030580ef1dd0b06f536a94b4b3be9d5"
				},
				{
					"path": "/apps/ya-book-reader/pixos.app.json",
					"hash": "sha256:35cf7fd3549293049dcd32f73bf8963c128a6abab59fdd5d453cb3a887886ef4"
				},
				{
					"path": "/apps/ya-book-reader/resources/css/text_defaults.css",
					"hash": "sha256:fb453bb126f38422ef6eceffd8e9734e1cf9c30c4621fe2176a725fc58871456"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/load_time_data.m.js",
					"hash": "sha256:36fc1600bf2ae6ac37d5d505c645b480662568865cdba74807a7a83309ed7270"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/reader_core/reader_core.js",
					"hash": "sha256:18561ea1f27f9985717e7041da6a7544e38c37d58f267353fb0570bc98644078"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/zip/inflate.js",
					"hash": "sha256:a84720d8facc41ed623f58133692fad63906fafa00ef83f4975635107d10b778"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/zip/mime_types.js",
					"hash": "sha256:06f5a1237148c4c75ec2bf6d16893b432feedc9f1385883f6420133c62a9a03d"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/zip/z_worker.js",
					"hash": "sha256:09b0b5863d28324cddf31ac2819a0e3a4dfff6a06cae173d99d14e20a17c3a76"
				},
				{
					"path": "/apps/ya-book-reader/resources/js/zip/zip.js",
					"hash": "sha256:37be829622a0070d7f9987ce4db7f413fbc437eabfb8b2ab4a196a4057087ee2"
				},
				{
					"path": "/apps/ya-book-reader/resources/polymer/v3_0/polymer/polymer_bundled.min.js",
					"hash": "sha256:ef4d2e80e16c431ef287755e0354d0354d452618f795016be1b16c16bc6ddec1"
				},
				{
					"path": "/apps/ya-book-reader/resources/yandex/images/loader.svg",
					"hash": "sha256:22cde5f39305e144b4057e7277b24ee445004e61fdba2d599712ae94aedae3d2"
				}
			],
			"supported": {
				"extensions": [
					"epub",
					"fb2.zip",
					"fb2"
				]
			}
		}
	};
}());
