
var Vips = (() => {
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var m=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof Deno,t=ea&&self.name?.startsWith("em-pthread");m.dynamicLibraries=m.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var ja=Object.assign({},m),ka=[],la="./this.program",ma=import.meta.url,na="";function oa(a){return m.locateFile?m.locateFile(a,na):na+a}var pa,qa;
if(fa)na=(new URL("./",import.meta.url)).href,pa=a=>ra(a)?Deno.readFile(new URL(a)):fetch(a).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));else if(da||ea)ma.startsWith("blob:")||(na=ma.substr(0,ma.replace(/[?#].*/,"").lastIndexOf("/")+1)),ea&&(qa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+
" : "+b.url)));var sa=m.print||console.log.bind(console),w=m.printErr||console.error.bind(console);Object.assign(m,ja);ja=null;m.arguments&&(ka=m.arguments);m.thisProgram&&(la=m.thisProgram);var ta=m.dynamicLibraries||[],ua=m.wasmBinary,va,wa,xa=!1,ya,x,y,z,A,B,C,za,D,Aa,Ba;
function Ca(){var a=va.buffer;m.HEAP8=x=new Int8Array(a);m.HEAP16=z=new Int16Array(a);m.HEAPU8=y=new Uint8Array(a);m.HEAPU16=A=new Uint16Array(a);m.HEAP32=B=new Int32Array(a);m.HEAPU32=C=new Uint32Array(a);m.HEAPF32=za=new Float32Array(a);m.HEAPF64=Ba=new Float64Array(a);m.HEAP64=D=new BigInt64Array(a);m.HEAPU64=Aa=new BigUint64Array(a)}
if(t){var Da,Ea=!1;function a(...c){console.error(c.join(" "))}m.printErr||(w=a);self.alert=function(...c){postMessage({P:"alert",text:c.join(" "),nc:Fa()})};m.instantiateWasm=(c,d)=>new Promise(e=>{Da=f=>{var g=new WebAssembly.Instance(f,Ga());d(g,f);e()}});self.onunhandledrejection=c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.P;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({P:"loaded"});for(let g of f)b(g);self.onmessage=b};ta=d.Ab;Ha=d.ic;for(const g of d.Lb)if(!m[g]||
m[g].proxy)m[g]=(...h)=>{postMessage({P:"callHandler",Kb:g,qb:h})},"print"==g&&(sa=m[g]),"printErr"==g&&(w=m[g]);va=d.rc;Ca();Da(d.sc)}else if("run"===e){Ia(d.W);Ja(d.W,0,0,1,0,0);Ka();La(d.W);Ea||(Ma(),Ea=!0);try{Na(d.lc,d.Da)}catch(f){if("unwind"!=f)throw f;}}else"setimmediate"!==d.target&&("checkMailbox"===e?Ea&&Oa():e&&(w(`worker: received unknown command ${e}`),w(d)))}catch(f){throw Pa(),f;}}self.onmessage=b}
if(!t){if(m.wasmMemory)va=m.wasmMemory;else{var Ra=m.INITIAL_MEMORY||1073741824;va=new WebAssembly.Memory({initial:Ra/65536,maximum:Ra/65536,shared:!0})}Ca()}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Xa=[],Ya=!1,Za=!1;function $a(){var a=m.preRun;a&&("function"==typeof a&&(a=[a]),a.forEach(ab));bb(Sa)}function cb(){Ya=!0;t||(bb(Xa),m.noFSInit||FS.Ia||FS.init(),FS.$a=!1,bb(Ta))}function ab(a){Sa.unshift(a)}function db(a){Wa.unshift(a)}var eb=0,fb=null,gb=null;
function hb(){eb++;m.monitorRunDependencies?.(eb)}function ib(){eb--;m.monitorRunDependencies?.(eb);if(0==eb&&(null!==fb&&(clearInterval(fb),fb=null),gb)){var a=gb;gb=null;a()}}function jb(a){m.onAbort?.(a);a="Aborted("+a+")";w(a);xa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var kb=a=>a.startsWith("data:application/octet-stream;base64,"),ra=a=>a.startsWith("file://");class E extends Error{}class lb extends E{}
class mb extends E{constructor(a){super(a);this.ta=a;a=nb(a);this.name=a[0];this.message=a[1]}}var ob;function pb(a){if(a==ob&&ua)return new Uint8Array(ua);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}function qb(a){return ua?Promise.resolve().then(()=>pb(a)):pa(a).then(b=>new Uint8Array(b),()=>pb(a))}function rb(a,b,c){return qb(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);jb(d)})}
function sb(a,b){var c=ob;return ua||"function"!=typeof WebAssembly.instantiateStreaming||kb(c)||"function"!=typeof fetch?rb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return rb(c,a,b)}))}
function Ga(){F={__assert_fail:tb,__call_sighandler:ub,__cxa_begin_catch:vb,__cxa_end_catch:wb,__cxa_find_matching_catch_2:xb,__cxa_find_matching_catch_3:yb,__cxa_rethrow:zb,__cxa_throw:Ab,__cxa_uncaught_exceptions:Bb,__heap_base:Cb,__indirect_function_table:I,__lsan_ignore_object:Db,__memory_base:Eb,__pthread_create_js:Fb,__resumeException:Gb,__stack_high:Hb,__stack_low:Ib,__stack_pointer:Jb,__syscall_dup:Kb,__syscall_faccessat:Lb,__syscall_fcntl64:Mb,__syscall_fstat64:Nb,__syscall_ftruncate64:Ob,
__syscall_getcwd:Pb,__syscall_ioctl:Qb,__syscall_lstat64:Rb,__syscall_newfstatat:Sb,__syscall_openat:Tb,__syscall_poll:Ub,__syscall_rmdir:Vb,__syscall_stat64:Wb,__syscall_unlinkat:Xb,__table_base:Yb,_abort_js:Zb,_dlopen_js:$b,_dlsym_catchup_js:ac,_dlsym_js:bc,_embind_finalize_value_object:cc,_embind_register_arithmetic_vector:dc,_embind_register_bigint:ec,_embind_register_bool:fc,_embind_register_class:gc,_embind_register_class_class_function:hc,_embind_register_class_constructor:ic,_embind_register_class_function:jc,
_embind_register_class_property:kc,_embind_register_emval:lc,_embind_register_enum:mc,_embind_register_enum_value:nc,_embind_register_float:oc,_embind_register_function:pc,_embind_register_integer:qc,_embind_register_memory_view:rc,_embind_register_std_string:sc,_embind_register_std_wstring:tc,_embind_register_value_object:uc,_embind_register_value_object_field:vc,_embind_register_void:wc,_emscripten_dlopen_js:xc,_emscripten_dlsync_threads:yc,_emscripten_dlsync_threads_async:zc,_emscripten_get_dynamic_libraries_js:Ac,
_emscripten_get_now_is_monotonic:Bc,_emscripten_init_main_thread_js:Cc,_emscripten_notify_mailbox_postmessage:Dc,_emscripten_receive_on_main_thread_js:Ec,_emscripten_runtime_keepalive_clear:Fc,_emscripten_thread_cleanup:Gc,_emscripten_thread_exit_joinable:Hc,_emscripten_thread_mailbox_await:La,_emscripten_thread_set_strongref:Ic,_emscripten_throw_longjmp:Jc,_emval_as:Kc,_emval_call:Lc,_emval_decref:Mc,_emval_get_global:Nc,_emval_get_method_caller:Oc,_emval_get_module_property:Pc,_emval_get_property:Qc,
_emval_incref:Rc,_emval_instanceof:Sc,_emval_is_number:Tc,_emval_is_string:Uc,_emval_new_cstring:Vc,_emval_run_destructors:Wc,_emval_set_property:Xc,_emval_take_value:Yc,_emval_typeof:Zc,_gmtime_js:$c,_localtime_js:ad,_mmap_js:bd,_munmap_js:cd,_tzset_js:dd,emscripten_check_blocking_allowed:ed,emscripten_console_error:fd,emscripten_date_now:gd,emscripten_err:hd,emscripten_exit_with_live_runtime:jd,emscripten_get_heap_max:kd,emscripten_get_now:ld,emscripten_num_logical_cores:md,emscripten_promise_destroy:nd,
emscripten_promise_resolve:od,emscripten_resize_heap:pd,environ_get:qd,environ_sizes_get:rd,exit:sd,fd_close:td,fd_fdstat_get:ud,fd_read:vd,fd_seek:wd,fd_write:xd,ffi_call_js:yd,getentropy:zd,heif_error_success:Ad,heif_image_release:Bd,heif_nclx_color_profile_free:Cd,invoke_di:Dd,invoke_dii:Ed,invoke_diii:Fd,invoke_diiii:Gd,invoke_fiii:Hd,invoke_i:Id,invoke_ii:Jd,invoke_iii:Kd,invoke_iiid:Ld,invoke_iiii:Md,invoke_iiiii:Nd,invoke_iiiiid:Od,invoke_iiiiii:Pd,invoke_iiiiiii:Qd,invoke_iiiiiiii:Rd,invoke_iiiiiiiiiii:Sd,
invoke_iiiiiiiiiiii:Td,invoke_iiiiiiiiiiiii:Ud,invoke_iiiiij:Vd,invoke_ji:Wd,invoke_jiiii:Xd,invoke_v:Yd,invoke_vi:Zd,invoke_vid:$d,invoke_viddi:ae,invoke_vii:be,invoke_viid:ce,invoke_viidd:de,invoke_viiddi:ee,invoke_viidi:fe,invoke_viii:ge,invoke_viiid:he,invoke_viiidddddi:ie,invoke_viiiddddi:je,invoke_viiidddi:ke,invoke_viiiddi:le,invoke_viiidi:me,invoke_viiii:ne,invoke_viiiii:oe,invoke_viiiiii:pe,invoke_viiiiiii:qe,invoke_viiiiiiii:re,invoke_viiiiiiiii:se,invoke_viiiiiiiiii:te,invoke_viiiiiiiiiii:ue,
invoke_viiiiiiiiiiii:ve,invoke_viiiiiiiiiiiii:we,invoke_viiiiiiiiiiiiiii:xe,llvm_eh_typeid_for:ye,memory:va,proc_exit:ze};return{env:F,wasi_snapshot_preview1:F,"GOT.mem":new Proxy(F,Ae),"GOT.func":new Proxy(F,Ae)}}var Be={};function Ce(a){for(var b=A[a+6>>1];13===b&&!(16<C[a>>2]);){var c=C[a+8>>2],d=C[c>>2];if(0===d){b=0;break}else if(0===C[(c>>2)+1])a=d,b=A[d+6>>1];else break}return[a,b]}
function yd(a,b,c,d){var e=C[(a>>2)+1],f=C[(a>>2)+6],g=C[(a>>2)+2];a=Ce(C[(a>>2)+3])[1];var h=J(),k=h,l=[],n=0;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)l.push(c),n=1;for(var p=0;p<f;p++){var q=C[(d>>2)+p],r=Ce(C[(g>>2)+p]),u=r[0];r=r[1];switch(r){case 1:case 10:case 9:case 14:l.push(C[q>>2]);break;case 2:l.push(za[q>>2]);break;case 3:l.push(Ba[q>>3]);break;case 5:l.push(y[q]);break;case 6:l.push(x[q]);break;case 7:l.push(A[q>>
1]);break;case 8:l.push(z[q>>1]);break;case 11:case 12:l.push(Aa[q>>3]);break;case 4:l.push(Aa[q>>3]);l.push(Aa[(q>>3)+1]);break;case 13:r=C[u>>2];u=A[u+4>>1];k-=r;k&=~(u-1);x.subarray(k,k+r).set(x.subarray(q,q+r));l.push(k);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+r);}}if(f!=e){var v=[];for(p=e-1;p>=f;p--)switch(q=C[(d>>2)+p],r=Ce(C[(g>>2)+p]),u=r[0],r=r[1],r){case 5:case 6:--k;k&=-1;y[k]=y[q];break;case 7:case 8:k-=2;k&=-2;A[k>>1]=A[q>>1];break;
case 1:case 9:case 10:case 14:case 2:k-=4;k&=-4;C[k>>2]=C[q>>2];break;case 3:case 11:case 12:k-=8;k&=-8;C[k>>2]=C[q>>2];C[(k>>2)+1]=C[(q>>2)+1];break;case 4:k-=16;k&=-8;C[k>>2]=C[q>>2];C[(k>>2)+1]=C[(q>>2)+1];C[(k>>2)+2]=C[(q>>2)+2];C[(k>>2)+3]=C[(q>>2)+3];break;case 13:k-=4;k&=-4;v.push([k,q,C[u>>2],A[u+4>>1]]);break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+r);}l.push(k);for(p=0;p<v.length;p++)e=v[p],d=e[0],q=e[1],r=e[2],u=e[3],k-=r,k&=~(u-1),x.subarray(k,
k+r).set(x.subarray(q,q+r)),C[d>>2]=k}K(k);De(0);b=N(b).apply(null,l);K(h);if(!n)switch(a){case 0:break;case 1:case 9:case 10:case 14:C[c>>2]=b;break;case 2:za[c>>2]=b;break;case 3:Ba[c>>3]=b;break;case 5:case 6:y[c+0]=b;break;case 7:case 8:A[c>>1]=b;break;case 11:case 12:Aa[c>>3]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}yd.g="viiii";var Fe=a=>{if(!(a instanceof Ee||"unwind"==a))throw a;};
function Ee(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ge=0,He=a=>{a.terminate();a.onmessage=()=>{}},Oe=a=>{var b=Ie[a];Je.delete(a);a in Ke&&Ke[a].resolve();a=b.W;delete Ie[a];Le.push(b);Me.splice(Me.indexOf(b),1);b.W=0;Ne(a)},Re=a=>{0==Le.length&&(Pe(),Qe(Le[0]));var b=Le.pop();if(!b)return 6;Me.push(b);Ie[a.W]=b;b.W=a.W;b.postMessage({P:"run",lc:a.kc,Da:a.Da,W:a.W},a.kb);return 0},Le=[],Me=[],Se=[],Ie={};
function Te(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Pe();ab(()=>{hb("loading-workers");Ue(()=>ib("loading-workers"))});Ke={};Je=new Set}var Ve=()=>{for(var a of Me)He(a);for(a of Le)He(a);Le=[];Me=[];Ie=[]};function Ka(){Se.forEach(a=>a())}
var Qe=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.P;if(f.Ca&&f.Ca!=Fa()){var h=Ie[f.Ca];h?h.postMessage(f,f.kb):w(`Internal error! Worker sent a message "${g}" to target pthread ${f.Ca}, but that thread no longer exists!`)}else if("checkMailbox"===g)Oa();else if("spawnThread"===g)Re(f);else if("cleanupThread"===g)Oe(f.Qa);else if("markAsFinished"===g)f=f.Qa,Je.add(f),f in Ke&&Ke[f].resolve();else if("loaded"===g)a.loaded=!0,b(a);else if("alert"===g)alert(`Thread ${f.nc}: ${f.text}`);else if("setimmediate"===
f.target)a.postMessage(f);else if("callHandler"===g)m[f.Kb](...f.qb);else g&&w(`worker sent an unknown command ${g}`)};a.onerror=f=>{w(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)m.propertyIsEnumerable(e)&&c.push(e);a.postMessage({P:"load",Lb:c,rc:va,sc:wa,Ab:ta,ic:Ha})});function Ue(a){t?a():Promise.all(Le.map(Qe)).then(a)}
function Pe(){var a=new URL("vips-es6.js",import.meta.url);a=new Worker(a,{type:"module",name:"em-pthread"});Le.push(a)}var Je,Ke,O=(a,b,...c)=>{for(var d=2*c.length,e=J(),f=De(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(D[g+2*h]=1n,D[g+2*h+1]=k):(D[g+2*h]=0n,Ba[g+2*h+1]=k)}a=We(a,0,d,f,b);K(e);return a};function ze(a){if(t)return O(0,1,a);ya=a;Xe||0<Ge||(Ve(),m.onExit?.(a),xa=!0);throw new Ee(a);}ze.g="vi";function Ye(a){if(t)return O(1,0,a);sd(a)}
var sd=a=>{ya=a;if(t)throw Ye(a),"unwind";if(!(Xe||0<Ge||t)){Ze();bb(Va);FS.Ia=!1;$e(0);for(var b=0;b<FS.streams.length;b++){var c=FS.streams[b];c&&FS.close(c)}Ve();Za=!0}ze(a)};sd.g="vi";var bf=a=>{if(!Za&&!xa)try{if(a(),!(Za||Xe||0<Ge))try{t?af(ya):sd(ya)}catch(b){Fe(b)}}catch(b){Fe(b)}},cf=a=>{Ge+=1;setTimeout(()=>{--Ge;bf(a)},1E4)},df=m.preloadPlugins||[],ef={},ff=!1,gf=!1,hf=[];
function jf(){function a(){gf=document.pointerLockElement===m.canvas||document.mozPointerLockElement===m.canvas||document.webkitPointerLockElement===m.canvas||document.msPointerLockElement===m.canvas}if(!kf){kf=!0;df.push({canHandle:function(c){return!m.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:lf(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:lf(d)}));var h=URL.createObjectURL(g),k=new Image;k.onload=()=>{var l=
document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(h);e?.(c)};k.onerror=()=>{w(`Image ${h} could not be decoded`);f?.()};k.src=h}});df.push({canHandle:function(c){return!m.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:lf(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){w(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="",n=0,p=0,q=0;q<c.length;q++)for(n=n<<8|c[q],p+=8;6<=p;){var r=n>>p-6&63;p-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==p?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&3)<<4],l+="=="):4==p&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&15)<<2],l+="=");k.src="data:audio/x-"+d.substr(-3)+";base64,"+l;f(k)}};k.src=h;cf(()=>{f(k)})}});var b=m.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),m.elementPointerLock&&b.addEventListener("click",
c=>{!gf&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),c.preventDefault())},!1))}}var mf=!1,nf=void 0,of=void 0;function pf(){if(!ff)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function lf(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var qf=[];function rf(){var a=m.canvas;qf.forEach(b=>b(a.width,a.height))}
function sf(a,b,c){b&&c?(a.tc=b,a.Mb=c):(b=a.tc,c=a.Mb);var d=b,e=c;m.forcedAspectRatio&&0<m.forcedAspectRatio&&(d/e<m.forcedAspectRatio?d=Math.round(e*m.forcedAspectRatio):e=Math.round(d/m.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}of?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var tf={},kf,uf={},vf=new Set(["__lsan_ignore_object","__lsan_ignore_object"]),Ae={get(a,b){(a=uf[b])||(a=uf[b]=new WebAssembly.Global({value:"i32",mutable:!0}));vf.has(b)||(a.required=!0);return a}},bb=a=>{a.forEach(b=>b(m))},Ia=a=>{var b=C[a+52>>2];wf(b,b-C[a+56>>2]);K(b)},xf=new TextDecoder,yf=(a,b=0,c=NaN)=>{c=b+c;for(var d=b;a[d]&&!(d>=c);)++d;return xf.decode(a.buffer?a.buffer instanceof SharedArrayBuffer?a.slice(b,d):a.subarray(b,d):new Uint8Array(a.slice(b,d)))},zf=a=>{function b(){for(var n=
0,p=1;;){var q=a[e++];n+=(q&127)*p;p*=128;if(!(q&128))break}return n}function c(){var n=b();e+=n;return yf(a,e-n,n)}function d(n,p){if(n)throw Error(p);}var e=0,f=0,g="dylink.0";a instanceof WebAssembly.Module?(f=WebAssembly.Module.customSections(a,g),0===f.length&&(g="dylink",f=WebAssembly.Module.customSections(a,g)),d(0===f.length,"need dylink section"),a=new Uint8Array(f[0]),f=a.length):(f=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0],d(!f,"need to see wasm magic number"),
d(0!==a[8],"need the dylink section to be first"),e=9,f=b(),f=e+f,g=c());var h={za:[],jb:new Set,lb:new Set};if("dylink"==g){h.ya=b();h.cb=b();h.qa=b();h.mc=b();g=b();for(var k=0;k<g;++k){var l=c();h.za.push(l)}}else for(d("dylink.0"!==g);e<f;)if(g=a[e++],k=b(),1===g)h.ya=b(),h.cb=b(),h.qa=b(),h.mc=b();else if(2===g)for(g=b(),k=0;k<g;++k)l=c(),h.za.push(l);else if(3===g)for(g=b();g--;)k=c(),l=b(),l&256&&h.jb.add(k);else if(4===g)for(g=b();g--;)c(),k=c(),l=b(),1==(l&3)&&h.lb.add(k);else e+=k;return h},
Af=[],I=new WebAssembly.Table({initial:5909,element:"anyfunc"}),N=a=>{var b=Af[a];b||(a>=Af.length&&(Af.length=a+1),Af[a]=b=I.get(a));return b},Na=(a,b)=>{Xe=Ge=0;Bf();a=N(a)(b);Xe||0<Ge?ya=a:af(a)},Ef=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};Cf[a]=c;void 0!=b&&(Df[b]=c);return c},Cf={},Df={},Cb=3671424,Ff=(a,b)=>Math.ceil(a/b)*b,Hf=a=>{if(Ya)return Gf(a,1);var b=Cb;Cb=a=b+16*Math.ceil(a/16);uf.__heap_base.value=a;return b},Jf=(a,b)=>{if(If)for(var c=a;c<a+b;c++){var d=N(c);d&&If.set(d,
c)}},If,Kf=a=>{If||(If=new WeakMap,Jf(0,I.length));return If.get(a)||0},Lf=[],Mf=(a,b)=>{var c=Kf(a);if(c)return c;if(Lf.length)c=Lf.pop();else{try{I.grow(1)}catch(h){if(!(h instanceof RangeError))throw h;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=I.length-1}try{var d=c;I.set(d,a);Af[d]=I.get(d)}catch(h){if(!(h instanceof TypeError))throw h;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;for(var e={i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"},f={parameters:[],
results:"v"==b[0]?[]:[e[b[0]]]},g=1;g<b.length;++g)f.parameters.push(e[b[g]]);b=new d(f,a)}else{d=[1];e=b.slice(0,1);b=b.slice(1);f={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);g=b.length;128>g?d.push(g):d.push(g%128|128,g>>7);for(g=0;g<b.length;++g)d.push(f[b[g]]);"v"==e?d.push(0):d.push(1,f[e]);b=[0,97,115,109,1,0,0,0,1];e=d.length;128>e?b.push(e):b.push(e%128|128,e>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,
{e:{f:a}})).exports.f}d=c;I.set(d,b);Af[d]=I.get(d)}If.set(a,c);return c},Nf=(a,b,c)=>{var d={},e;for(e in a){var f=a[e];"object"==typeof f&&(f=f.value);"number"==typeof f&&(f+=b);d[e]=f}for(var g in d){a=g;if("__cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(a)||a.startsWith("__em_js__"))continue;a=d[g];let h,
k;(h=uf)[k=g]||(h[k]=new WebAssembly.Global({value:"i32",mutable:!0}));if(c||0==uf[g].value)"function"==typeof a?uf[g].value=Mf(a):"number"==typeof a?uf[g].value=a:w(`unhandled export type for '${g}': ${typeof a}`)}return d},Of=a=>{a=F[a];return!a||a.ja?!1:!0},Qf=(a,b=[])=>N(a)(...b),Rf=a=>(b,...c)=>{var d=J();try{return Qf(b,c)}catch(e){K(d);if(!(e instanceof E))throw e;P(1,0);if("j"==a[0])return 0n}},Tf=a=>{var b;Of(a)?b=F[a]:a.startsWith("invoke_")?b=F[a]=Rf(a.split("_")[1]):a.startsWith("__cxa_find_matching_catch_")&&
(b=F[a]=(...c)=>Sf(c));return{Pa:b,name:a}},R=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&y[c];)++c;return xf.decode(y.slice(a,c))},Xf=(a,b,c,d,e)=>{function f(){function h(u,v){function G(L,ha){L=[];for(var Qa=0;16>Qa;Qa++)if(-1!=ha.indexOf("$"+Qa))L.push("$"+Qa);else break;L=L.join(",");Be[H]=eval(`(${L}) => { ${ha} };`)}function M(L,ha,Qa){var Pf=[];ha=ha.slice(1,-1);if("void"!=ha){ha=ha.split(",");for(var ji in ha){var ki=ha[ji].split(" ").pop();Pf.push(ki.replace("*",""))}}q[L]=eval(`(${Pf}) => ${Qa};`)}
!t&&c&&(Ha[c]=u);Jf(p,g.qa);q=Nf(v.exports,n);b.pb||Uf();if("__start_em_asm"in q){var H=q.__start_em_asm;for(u=q.__stop_em_asm;H<u;){var Q=R(H);G(H,Q);H=y.indexOf(0,H)+1}}for(var ia in q)ia.startsWith("__em_js__")&&(H=q[ia],Q=R(H),u=Q.split("<::>"),M(ia.replace("__em_js__",""),u[0],u[1]),delete q[ia]);Vf(q._emscripten_tls_init,v.exports,g);k&&((v=q.__wasm_apply_data_relocs)&&(Ya?v():Xa.push(v)),(v=q.__wasm_call_ctors)&&(Ya?v():Ta.push(v)));return q}var k=!e||!x[e+8];if(k){var l=Math.pow(2,g.cb),n=
g.ya?Ff(Hf(g.ya+l),l):0,p=g.qa?I.length:0;e&&(x[e+8]=1,C[e+12>>2]=n,B[e+16>>2]=g.ya,C[e+20>>2]=p,B[e+24>>2]=g.qa)}else n=C[e+12>>2],p=C[e+20>>2];l=p+g.qa-I.length;0<l&&I.grow(l);var q;l=new Proxy({},{get(u,v){switch(v){case "__memory_base":return n;case "__table_base":return p}if(v in F&&!F[v].ja)return F[v];if(!(v in u)){var G;u[v]=(...M)=>{if(!G){var H=Tf(v).Pa;!H&&d&&(H=d[v]);H||=q[v];G=H}return G(...M)}}return u[v]}});var r={"GOT.mem":new Proxy({},Ae),"GOT.func":new Proxy({},Ae),env:l,wasi_snapshot_preview1:l};
if(b.G)return a instanceof WebAssembly.Module?(r=new WebAssembly.Instance(a,r),Promise.resolve(h(a,r))):WebAssembly.instantiate(a,r).then(u=>h(u.module,u.instance));l=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);r=new WebAssembly.Instance(l,r);return h(l,r)}var g=zf(a);vf=g.lb;if(b.G)return g.za.reduce((h,k)=>h.then(()=>Wf(k,b,d)),Promise.resolve()).then(f);g.za.forEach(h=>Wf(h,b,d));return f()},Yf=a=>{var b,c;for([b,c]of Object.entries(a))Of(b)||(F[b]=c)},Zf=(a,b,c)=>{var d=`al ${a}`;
pa(a).then(e=>{b(new Uint8Array(e));d&&ib(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&hb(d)};
function Wf(a,b={global:!0,ma:!0},c,d){function e(){var k=Ha[a];if(k)return b.G?Promise.resolve(k):k;if(d){k=C[d+28>>2];var l=C[d+32>>2];if(k&&l)return k=x.slice(k,k+l),b.G?Promise.resolve(k):k}var n=oa(a);if(b.G)return new Promise((p,q)=>Zf(n,p,q));if(!qa)throw Error(`${n}: file not found, and synchronous loading of external files is not available`);return qa(n)}function f(){var k=ef[a];return k?b.G?Promise.resolve(k):k:b.G?e().then(l=>Xf(l,b,a,c,d)):Xf(e(),b,a,c,d)}function g(k){h.global?Yf(k):
c&&Object.assign(c,k);h.exports=k}var h=Cf[a];if(h)return b.global?h.global||(h.global=!0,Yf(h.exports)):c&&Object.assign(c,h.exports),b.ma&&Infinity!==h.Aa&&(h.Aa=Infinity),h.Aa++,d&&(Df[d]=h),b.G?Promise.resolve(!0):!0;h=Ef(a,d,"loading");h.Aa=b.ma?Infinity:1;h.global=b.global;if(b.G)return f().then(k=>{g(k);return!0});g(f());return!0}
var Uf=()=>{var a,b;for([a,b]of Object.entries(uf))if(0==b.value){var c=Tf(a).Pa;if(c||b.required)if("function"==typeof c)b.value=Mf(c,c.g);else if("number"==typeof c)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c}`);}},$f=()=>{ta.length?(hb("loadDylibs"),ta.reduce((a,b)=>a.then(()=>Wf(b,{G:!0,global:!0,ma:!0,pb:!0})),Promise.resolve()).then(()=>{Uf();ib("loadDylibs")})):Uf()},Xe=m.noExitRuntime||!1,Vf=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.jb.forEach(g=>f[g]=b[g]);
Nf(f,e,!0)}}Se.push(d);Ya&&d()},tb=(a,b,c,d)=>{jb(`Assertion failed: ${R(a)}, at: `+[b?R(b):"unknown filename",c,d?R(d):"unknown function"])};tb.g="vppip";var ub=(a,b)=>N(a)(b);ub.g="vpi";var ag=[],bg=0,vb=a=>{var b=new cg(a);0==x[b.s+12]&&(x[b.s+12]=1,bg--);x[b.s+13]=0;ag.push(b);dg(a);return eg(a)};vb.g="pp";var fg=0,wb=()=>{P(0,0);var a=ag.pop();gg(a.ta);fg=0};wb.g="v";class cg{constructor(a){this.ta=a;this.s=a-24}init(a,b){C[this.s+16>>2]=0;C[this.s+4>>2]=a;C[this.s+8>>2]=b}}
var Gb=a=>{fg||=new mb(a);throw fg;};Gb.g="vp";var Sf=a=>{var b=fg?.ta;if(!b)return hg(0),0;var c=new cg(b);C[c.s+16>>2]=b;var d=C[c.s+4>>2];if(!d)return hg(0),b;for(var e of a){if(0===e||e===d)break;if(ig(e,d,c.s+16))return hg(e),b}hg(d);return b},xb=()=>Sf([]);xb.g="p";var yb=a=>Sf([a]);yb.g="pp";var zb=()=>{var a=ag.pop();a||jb("no exception to throw");var b=a.ta;0==x[a.s+13]&&(ag.push(a),x[a.s+13]=1,x[a.s+12]=0,bg++);fg=new mb(b);throw fg;};zb.g="v";
var Ab=(a,b,c)=>{(new cg(a)).init(b,c);fg=new mb(a);bg++;throw fg;};Ab.g="vppp";var Bb=()=>bg;Bb.g="i";function Db(...a){return F.__lsan_ignore_object(...a)}Db.ja=!0;var Eb=new WebAssembly.Global({value:"i32",mutable:!1},1024);function jg(a,b,c,d){return t?O(2,1,a,b,c,d):Fb(a,b,c,d)}var Fb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(t&&0===e.length)return jg(a,b,c,d);a={kc:c,W:a,Da:d,kb:e};return t?(a.P="spawnThread",postMessage(a,e),0):Re(a)};Fb.g="ipppp";
var Hb=3671424,Ib=3409280,Jb=new WebAssembly.Global({value:"i32",mutable:!0},3671424),kg=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},lg=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kg(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},mg=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},ng=a=>{if("/"===a)return"/";a=lg(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},og=(a,b)=>lg(a+"/"+b),pg=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);jb("initRandomDevice")},qg=a=>(qg=pg())(a),rg=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=kg(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},sg=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=rg(a).substr(1);b=rg(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},tg=[],ug=a=>
{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},vg=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|
g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function wg(a){var b=Array(ug(a)+1);a=vg(a,b,0,b.length);b.length=a;return b}var xg=[];function yg(a,b){xg[a]={input:[],K:[],Z:b};FS.registerDevice(a,zg)}
var zg={open(a){var b=xg[a.node.oa];if(!b)throw new FS.h(43);a.A=b;a.seekable=!1},close(a){a.A.Z.ua(a.A)},ua(a){a.A.Z.ua(a.A)},read(a,b,c,d){if(!a.A||!a.A.Z.Za)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.A.Z.Za(a.A)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.A||!a.A.Z.Ma)throw new FS.h(60);try{for(var e=0;e<d;e++)a.A.Z.Ma(a.A,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.timestamp=Date.now());return e}},Ag={Za(){a:{if(!tg.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}tg=wg(a)}a=tg.shift()}return a},Ma(a,b){null===b||10===b?(sa(yf(a.K)),a.K=[]):0!=b&&a.K.push(b)},ua(a){a.K&&0<a.K.length&&(sa(yf(a.K)),a.K=[])},Pb(){return{xc:25856,zc:5,wc:191,yc:35387,vc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Qb(){return 0},Rb(){return[24,
80]}},Bg={Ma(a,b){null===b||10===b?(w(yf(a.K)),a.K=[]):0!=b&&a.K.push(b)},ua(a){a.K&&0<a.K.length&&(w(yf(a.K)),a.K=[])}},Dg=a=>{a=65536*Math.ceil(a/65536);var b=Cg(65536,a);b&&y.fill(0,b,b+a);return b};function Eg(a,b){var c=a.u?a.u.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.u,a.u=new Uint8Array(b),0<a.C&&a.u.set(c.subarray(0,a.C),0))}
var S={V:null,mount(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);S.V||(S.V={dir:{node:{T:S.m.T,H:S.m.H,fa:S.m.fa,Y:S.m.Y,rename:S.m.rename,unlink:S.m.unlink,rmdir:S.m.rmdir,pa:S.m.pa,symlink:S.m.symlink},stream:{llseek:S.o.llseek}},file:{node:{T:S.m.T,H:S.m.H},stream:{llseek:S.o.llseek,read:S.o.read,write:S.o.write,ba:S.o.ba,ga:S.o.ga,ia:S.o.ia}},link:{node:{T:S.m.T,H:S.m.H,readlink:S.m.readlink},stream:{}},Ra:{node:{T:S.m.T,
H:S.m.H},stream:FS.vb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=S.V.dir.node,c.o=S.V.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=S.V.file.node,c.o=S.V.file.stream,c.C=0,c.u=null):FS.isLink(c.mode)?(c.m=S.V.link.node,c.o=S.V.link.stream):FS.isChrdev(c.mode)&&(c.m=S.V.Ra.node,c.o=S.V.Ra.stream);c.timestamp=Date.now();a&&(a.u[b]=c,a.timestamp=c.timestamp);return c},Dc(a){return a.u?a.u.subarray?a.u.subarray(0,a.C):new Uint8Array(a.u):new Uint8Array(0)},m:{T(a){var b={};b.yb=FS.isChrdev(a.mode)?
a.id:1;b.Ob=a.id;b.mode=a.mode;b.Xb=1;b.uid=0;b.Jb=0;b.oa=a.oa;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.C:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.rb=new Date(a.timestamp);b.Vb=new Date(a.timestamp);b.xb=new Date(a.timestamp);b.sb=4096;b.tb=Math.ceil(b.size/b.sb);return b},H(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.C!=b))if(0==b)a.u=null,a.C=0;else{var c=a.u;a.u=new Uint8Array(b);c&&a.u.set(c.subarray(0,
Math.min(b,a.C)));a.C=b}},fa(){throw FS.Fa[44];},Y(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){if(FS.isDir(a.mode)){try{var d=Fg(b,c)}catch(f){}if(d)for(var e in d.u)throw new FS.h(55);}delete a.parent.u[a.name];a.parent.timestamp=Date.now();a.name=c;b.u[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.u[b];a.timestamp=Date.now()},rmdir(a,b){var c=Fg(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.timestamp=Date.now()},pa(a){var b=[".",".."],c;for(c of Object.keys(a.u))b.push(c);
return b},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){var f=a.node.u;if(e>=a.node.C)return 0;a=Math.min(a.node.C-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.u||a.u.subarray)){if(f)return a.u=b.subarray(c,c+d),a.C=d;if(0===a.C&&0===e)return a.u=b.slice(c,c+d),
a.C=d;if(e+d<=a.C)return a.u.set(b.subarray(c,c+d),e),d}Eg(a,e+d);if(a.u.subarray&&b.subarray)a.u.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.u[e+f]=b[c+f];a.C=Math.max(a.C,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.C);if(0>b)throw new FS.h(28);return b},ba(a,b,c){Eg(a.node,b+c);a.node.C=Math.max(a.node.C,b+c)},ga(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||!a||a.buffer!==x.buffer){d=!0;e=Dg(b);if(!e)throw new FS.h(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);x.set(a,e)}}else d=!1,e=a.byteOffset;return{s:e,$:d}},ia(a,b,c,d){S.o.write(a,b,0,d,c,!1);return 0}}},Gg=(a,b,c,d)=>{"undefined"!=typeof tf&&jf();var e=!1;df.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Hg=(a,b,c,d,e,f,g,h,k,l)=>{function n(r){function u(v){l?.();h||FS.createDataFile(a,b,v,d,e,k);f?.();ib(q)}Gg(r,p,u,()=>{g?.();ib(q)})||u(r)}var p=b?rg(lg(a+"/"+b)):a,q=`cp ${p}`;
hb(q);"string"==typeof c?Zf(c,n,g):n(c)},Ig=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};function Fg(a,b){var c=FS.isDir(a.mode)?(c=Jg(a,"x"))?c:a.m.fa?0:2:54;if(c)throw new FS.h(c);for(c=FS.U[Kg(a.id,b)];c;c=c.ha){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.fa(a,b)}function Kg(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.U.length}function Lg(a){var b=Kg(a.parent.id,a.name);a.ha=FS.U[b];FS.U[b]=a}
function Mg(a){var b=Kg(a.parent.id,a.name);if(FS.U[b]===a)FS.U[b]=a.ha;else for(b=FS.U[b];b;){if(b.ha===a){b.ha=a.ha;break}b=b.ha}}function Ng(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Jg(a,b){if(FS.$a)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Og(a,b){try{return Fg(a,b),20}catch(c){}return Jg(a,"wx")}
function Pg(a,b,c){try{var d=Fg(a,b)}catch(e){return e.B}if(a=Jg(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.wa(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function T(a){a=FS.Ya(a);if(!a)throw new FS.h(8);return a}function Qg(a,b=-1){a=Object.assign(new FS.nb,a);if(-1==b)a:{for(b=0;b<=FS.ob;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.S=b;return FS.streams[b]=a}function Rg(a,b=-1){a=Qg(a,b);a.o?.Bc?.(a);return a}
function Sg(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.la)}return b}function Tg(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=lg(a+"/"+b);return FS.create(b,Ig(c,d))}
function Ug(a){if(!(a.Sb||a.Tb||a.link||a.u)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.u=qa(a.url),a.C=a.u.length}catch(b){throw new FS.h(29);}}}
var FS={root:null,la:[],Va:{},streams:[],Wb:1,U:null,Ta:"/",Ia:!1,$a:!0,h:class{constructor(a){this.name="ErrnoError";this.B=a}},Fa:{},Db:null,Ba:0,hb:{},nb:class{constructor(){this.N={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.N.flags}set flags(a){this.N.flags=a}get position(){return this.N.position}set position(a){this.N.position=a}},mb:class{constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.R=null;this.id=FS.Wb++;this.name=
b;this.mode=c;this.m={};this.o={};this.oa=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Tb(){return FS.isDir(this.mode)}get Sb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){a=rg(a);if(!a)return{path:"",node:null};b=Object.assign({Ea:!0,Oa:0},b);if(8<b.Oa)throw new FS.h(32);a=a.split("/").filter(g=>!!g);for(var c=FS.root,d="/",e=0;e<a.length;e++){var f=e===a.length-
1;if(f&&b.parent)break;c=Fg(c,a[e]);d=lg(d+"/"+a[e]);c.R&&(!f||f&&b.Ea)&&(c=c.R.root);if(!f||b.follow)for(f=0;FS.isLink(c.mode);)if(c=FS.readlink(d),d=rg(mg(d),c),c=FS.lookupPath(d,{Oa:b.Oa+1}).node,40<f++)throw new FS.h(32);}return{path:d,node:c}},getPath(a){for(var b;;){if(FS.wa(a))return a=a.mount.eb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.mb(a,b,c,d);Lg(a);return a},wa(a){return a===a.parent},isFile(a){return 32768===(a&61440)},
isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},ob:4096,Ya:a=>FS.streams[a],vb:{open(a){a.o=FS.Fb(a.node.oa).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},La:a=>a>>8,Gc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Va[a]={o:b}},Fb:a=>FS.Va[a],syncfs(a,b){function c(g){FS.Ba--;return b(g)}function d(g){if(g){if(!d.Bb)return d.Bb=!0,c(g)}else++f>=e.length&&
c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ba++;1<FS.Ba&&w(`warning: ${FS.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Sg(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&c){var e=FS.lookupPath(c,{Ea:!1});c=e.path;e=e.node;if(e.R)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,Ic:b,eb:c,la:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=
a:e&&(e.R=b,e.mount&&e.mount.la.push(b));return a},unmount(a){a=FS.lookupPath(a,{Ea:!1});if(!a.node.R)throw new FS.h(28);a=a.node;var b=a.R,c=Sg(b);Object.keys(FS.U).forEach(d=>{for(d=FS.U[d];d;){var e=d.ha;c.includes(d.mount)&&Mg(d);d=e}});a.R=null;a.mount.la.splice(a.mount.la.indexOf(b),1)},fa(a,b){return a.m.fa(a,b)},Y(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=ng(a);if(!a||"."===a||".."===a)throw new FS.h(28);var e=Og(d,a);if(e)throw new FS.h(e);if(!d.m.Y)throw new FS.h(63);return d.m.Y(d,
a,b,c)},create(a,b){return FS.Y(a,(void 0!==b?b:438)&4095|32768,0)},mkdir(a,b){return FS.Y(a,(void 0!==b?b:511)&1023|16384,0)},Hc(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{FS.mkdir(c,b)}catch(e){if(20!=e.B)throw e;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.Y(a,b|8192,c)},symlink(a,b){if(!rg(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=ng(b);var d=Og(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);
return c.m.symlink(c,b,a)},rename(a,b){var c=mg(a),d=mg(b),e=ng(a),f=ng(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);var k=Fg(h,e);a=sg(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=sg(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var l=Fg(g,f)}catch(n){}if(k!==l){b=FS.isDir(k.mode);if(e=Pg(h,e,b))throw new FS.h(e);if(e=l?Pg(g,f,b):Og(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);
if(k.R||l&&l.R)throw new FS.h(10);if(g!==h&&(e=Jg(h,"w")))throw new FS.h(e);Mg(k);try{h.m.rename(k,g,f),k.parent=g}catch(n){throw n;}finally{Lg(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=ng(a);var c=Fg(b,a),d=Pg(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.R)throw new FS.h(10);b.m.rmdir(b,a);Mg(c)},pa(a){a=FS.lookupPath(a,{follow:!0}).node;if(!a.m.pa)throw new FS.h(54);return a.m.pa(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);
a=ng(a);var c=Fg(b,a),d=Pg(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.R)throw new FS.h(10);b.m.unlink(b,a);Mg(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return rg(FS.getPath(a.parent),a.m.readlink(a))},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;if(!a)throw new FS.h(44);if(!a.m.T)throw new FS.h(63);return a.m.T(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:
a;if(!a.m.H)throw new FS.h(63);a.m.H(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=T(a);FS.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;if(!a.m.H)throw new FS.h(63);a.m.H(a,{timestamp:Date.now()})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a,b,c){a=T(a);FS.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new FS.h(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;if(!a.m.H)throw new FS.h(63);if(FS.isDir(a.mode))throw new FS.h(31);
if(!FS.isFile(a.mode))throw new FS.h(28);var c=Jg(a,"w");if(c)throw new FS.h(c);a.m.H(a,{size:b,timestamp:Date.now()})},ftruncate(a,b){a=T(a);if(0===(a.flags&2097155))throw new FS.h(28);FS.truncate(a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;a.m.H(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==
typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=lg(a);try{e=FS.lookupPath(a,{follow:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new FS.h(20);}else e=FS.Y(a,c,0),d=!0;if(!e)throw new FS.h(44);FS.isChrdev(e.mode)&&(b&=-513);if(b&65536&&!FS.isDir(e.mode))throw new FS.h(54);if(!d){c=e;var f=b;if(c=c?FS.isLink(c.mode)?32:FS.isDir(c.mode)&&("r"!==Ng(f)||f&512)?31:Jg(c,Ng(f)):44)throw new FS.h(c);}b&512&&!d&&FS.truncate(e,0);b&=-131713;e=Qg({node:e,path:FS.getPath(e),
flags:b,seekable:!0,position:0,o:e.o,pc:[],error:!1});e.o.open&&e.o.open(e);!m.logReadFiles||b&1||a in FS.hb||(FS.hb[a]=1);return e},close(a){if(null===a.S)throw new FS.h(8);a.Ga&&(a.Ga=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.S]=null}a.S=null},llseek(a,b,c){if(null===a.S)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.pc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.S)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.S)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ba(a,b,c){if(null===a.S)throw new FS.h(8);if(0>b||0>=c)throw new FS.h(28);if(0===(a.flags&2097155))throw new FS.h(8);if(!FS.isFile(a.node.mode)&&!FS.isDir(a.node.mode))throw new FS.h(43);if(!a.o.ba)throw new FS.h(138);a.o.ba(a,b,c)},ga(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);
if(!a.o.ga)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ga(a,b,c,d,e)},ia(a,b,c,d,e){return a.o.ia?a.o.ia(a,b,c,d,e):0},Ja(a,b,c){if(!a.o.Ja)throw new FS.h(59);return a.o.Ja(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=FS.open(a,b.flags);a=FS.stat(a).size;var e=new Uint8Array(a);FS.read(d,e,0,a,0);"utf8"===b.encoding?c=yf(e):"binary"===b.encoding&&(c=
e);FS.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(ug(b)+1);b=vg(b,d,0,d.length);FS.write(a,d,0,b,void 0,c.ub)}else if(ArrayBuffer.isView(b))FS.write(a,b,0,b.byteLength,void 0,c.ub);else throw Error("Unsupported data type");FS.close(a)},cwd:()=>FS.Ta,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);var b=Jg(a.node,"x");if(b)throw new FS.h(b);
FS.Ta=a.path},init(a,b,c){FS.Ia=!0;a??=m.stdin;b??=m.stdout;c??=m.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Cc(a,b){a=FS.analyzePath(a,b);return a.Wa?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d=
{wa:!1,Wa:!1,error:0,name:null,path:null,object:null,Yb:!1,$b:null,Zb:null};try{c=FS.lookupPath(a,{parent:!0}),d.Yb=!0,d.$b=c.path,d.Zb=c.node,d.name=ng(a),c=FS.lookupPath(a,{follow:!b}),d.Wa=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.wa="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=lg(a+"/"+c);try{FS.mkdir(d)}catch(e){}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;
a&&(a="string"==typeof a?a:FS.getPath(a),g=b?lg(a+"/"+b):a);a=Ig(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,b,c,d){a=og("string"==typeof a?a:FS.getPath(a),b);b=Ig(!!c,!!d);var e;(e=FS.createDevice).La??(e.La=64);e=FS.makedev(FS.createDevice.La++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&
d(10)},read(f,g,h,k){for(var l=0,n=0;n<k;n++){try{var p=c()}catch(q){throw new FS.h(29);}if(void 0===p&&0===l)throw new FS.h(6);if(null===p||void 0===p)break;l++;g[h+n]=p}l&&(f.node.timestamp=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(n){throw new FS.h(29);}k&&(f.node.timestamp=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(p,q,r,u,v){p=p.node.u;if(v>=p.length)return 0;u=Math.min(p.length-v,u);if(p.slice)for(var G=0;G<u;G++)q[r+
G]=p[v+G];else for(G=0;G<u;G++)q[r+G]=p.get(v+G);return u}class g{constructor(){this.Ha=!1;this.N=[];this.ka=void 0;this.ab=this.bb=0}get(p){if(!(p>this.length-1||0>p)){var q=p%this.ib;return this.ka(p/this.ib|0)[q]}}oc(p){this.ka=p}fb(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),r,u=(r=p.getResponseHeader("Accept-Ranges"))&&"bytes"===
r;p=(r=p.getResponseHeader("Content-Encoding"))&&"gzip"===r;var v=1048576;u||(v=q);var G=this;G.oc(M=>{var H=M*v,Q=(M+1)*v-1;Q=Math.min(Q,q-1);if("undefined"==typeof G.N[M]){var ia=G.N;if(H>Q)throw Error("invalid range ("+H+", "+Q+") or no bytes requested!");if(Q>q-1)throw Error("only "+q+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);q!==v&&L.setRequestHeader("Range","bytes="+H+"-"+Q);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");
L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);H=void 0!==L.response?new Uint8Array(L.response||[]):wg(L.responseText||"");ia[M]=H}if("undefined"==typeof G.N[M])throw Error("doXHR failed!");return G.N[M]});if(p||!q)v=q=1,v=q=this.ka(0).length,sa("LazyFiles on gzip forces download of the whole file when length is accessed");this.bb=q;this.ab=v;this.Ha=!0}get length(){this.Ha||this.fb();return this.bb}get ib(){this.Ha||this.fb();
return this.ab}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var l=Tg(a,b,d,e);h?l.u=h:k&&(l.u=null,l.url=k);Object.defineProperties(l,{C:{get:function(){return this.u.length}}});var n={};Object.keys(l.o).forEach(p=>{var q=l.o[p];n[p]=(...r)=>{Ug(l);return q(...r)}});n.read=(p,q,r,u,v)=>{Ug(l);return f(p,q,r,u,v)};n.ga=(p,q,r)=>{Ug(l);
var u=Dg(q);if(!u)throw new FS.h(48);f(p,x,u,q,r);return{s:u,$:!0}};l.o=n;return l}},Vg=5;function Wg(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():T(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return lg(a+"/"+b)}
function Xg(a,b,c){a=a(b);B[c>>2]=a.yb;B[c+4>>2]=a.mode;C[c+8>>2]=a.Xb;B[c+12>>2]=a.uid;B[c+16>>2]=a.Jb;B[c+20>>2]=a.oa;D[c+24>>3]=BigInt(a.size);B[c+32>>2]=4096;B[c+36>>2]=a.tb;b=a.rb.getTime();var d=a.Vb.getTime(),e=a.xb.getTime();D[c+40>>3]=BigInt(Math.floor(b/1E3));C[c+48>>2]=b%1E3*1E6;D[c+56>>3]=BigInt(Math.floor(d/1E3));C[c+64>>2]=d%1E3*1E6;D[c+72>>3]=BigInt(Math.floor(e/1E3));C[c+80>>2]=e%1E3*1E6;D[c+88>>3]=BigInt(a.Ob);return 0}var Yg=void 0;
function Kb(a){if(t)return O(3,1,a);try{var b=T(a);return Rg(b).S}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}Kb.g="ii";function Lb(a,b,c,d){if(t)return O(4,1,a,b,c,d);try{b=R(b);b=Wg(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Jg(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}Lb.g="iipii";
function Zg(){var a=B[+Yg>>2];Yg+=4;return a}function Mb(a,b,c){if(t)return O(5,1,a,b,c);Yg=c;try{var d=T(a);switch(b){case 0:var e=Zg();if(0>e)break;for(;FS.streams[e];)e++;return Rg(d,e).S;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Zg(),d.flags|=e,0;case 12:return e=Zg(),z[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}Mb.g="iiip";
function Nb(a,b){if(t)return O(6,1,a,b);try{var c=T(a);return Xg(FS.stat,c.path,b)}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}Nb.g="iip";function Ob(a,b){if(t)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}Ob.g="iij";
function Pb(a,b){if(t)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=ug(c)+1;if(b<d)return-68;vg(c,y,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}Pb.g="ipp";
function Qb(a,b,c){if(t)return O(9,1,a,b,c);Yg=c;try{var d=T(a);switch(b){case 21509:return d.A?0:-59;case 21505:if(!d.A)return-59;if(d.A.Z.Pb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Zg();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)x[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.A?0:-59;case 21506:case 21507:case 21508:if(!d.A)return-59;if(d.A.Z.Qb)for(e=Zg(),a=[],f=0;32>f;f++)a.push(x[e+f+17]);return 0;
case 21519:if(!d.A)return-59;e=Zg();return B[e>>2]=0;case 21520:return d.A?-28:-59;case 21531:return e=Zg(),FS.Ja(d,b,e);case 21523:if(!d.A)return-59;d.A.Z.Rb&&(f=[24,80],e=Zg(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.A?0:-59;case 21515:return d.A?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}Qb.g="iiip";
function Rb(a,b){if(t)return O(10,1,a,b);try{return a=R(a),Xg(FS.lstat,a,b)}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}Rb.g="ipp";function Sb(a,b,c,d){if(t)return O(11,1,a,b,c,d);try{b=R(b);var e=d&256;b=Wg(a,b,d&4096);return Xg(e?FS.lstat:FS.stat,b,c)}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}Sb.g="iippi";
function Tb(a,b,c,d){if(t)return O(12,1,a,b,c,d);Yg=d;try{b=R(b);b=Wg(a,b);var e=d?Zg():0;return FS.open(b,c,e).S}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}Tb.g="iipip";function Ub(a,b,c){if(t)return O(13,1,a,b,c);try{for(var d=c=0;d<b;d++){var e=a+8*d,f=z[e+4>>1],g=32,h=FS.Ya(B[e>>2]);h&&(g=Vg,h.o.bc&&(g=h.o.bc(h,-1)));(g&=f|24)&&c++;z[e+6>>1]=g}return c}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.B}}Ub.g="ipii";
function Vb(a){if(t)return O(14,1,a);try{return a=R(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}Vb.g="ip";function Wb(a,b){if(t)return O(15,1,a,b);try{return a=R(a),Xg(FS.stat,a,b)}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}Wb.g="ipp";
function Xb(a,b,c){if(t)return O(16,1,a,b,c);try{return b=R(b),b=Wg(a,b),0===c?FS.unlink(b):512===c?FS.rmdir(b):jb("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}Xb.g="iipi";var Yb=new WebAssembly.Global({value:"i32",mutable:!1},1),Zb=()=>{jb("")};Zb.g="v";
var $g={},ah=a=>{var b=ug(a)+1,c=De(b);vg(a,y,c,b);return c},ch=a=>{var b=J();a=ah(a);bh(a,0);K(b)},dh=(a,b)=>{var c=R(a+36),d=B[a+4>>2];c=lg(c);var e=!!(d&256),f=e?null:{};d={global:e,ma:!!(d&4096),G:b.G};if(b.G)return Wf(c,d,f,a);try{return Wf(c,d,f,a)}catch(g){return ch(`Could not load dynamic lib: ${c}\n${g}`),0}},$b=a=>dh(a,{G:!1});$b.g="pp";var ac=(a,b)=>{a=Df[a].exports;b=Object.keys(a)[b];b=a[b];return Mf(b,b.g)};ac.g="ppi";
var bc=(a,b,c)=>{b=R(b);var d=Df[a];if(!d.exports.hasOwnProperty(b)||d.exports[b].ja)return ch(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;a=Object.keys(d.exports).indexOf(b);b=d.exports[b];"function"==typeof b&&((d=Kf(b))?b=d:(b=Mf(b,b.g),C[c>>2]=a));return b};bc.g="pppp";var eh={},fh=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function gh(a){return this.fromWireType(C[a>>2])}
var hh={},ih={},jh={},kh,mh=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new kh("Mismatched type converter count");for(var k=0;k<a.length;++k)lh(a[k],h[k])}a.forEach(h=>jh[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{ih.hasOwnProperty(h)?e[k]=ih[h]:(f.push(h),hh.hasOwnProperty(h)||(hh[h]=[]),hh[h].push(()=>{e[k]=ih[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},cc=a=>{var b=eh[a];delete eh[a];var c=b.Na,d=b.X,e=b.Xa,f=e.map(g=>g.Ib).concat(e.map(g=>g.fc));mh([a],f,g=>
{var h={};e.forEach((k,l)=>{var n=g[l],p=k.ka,q=k.Hb,r=g[l+e.length],u=k.ec,v=k.hc;h[k.Cb]={read:G=>n.fromWireType(p(q,G)),write:(G,M)=>{var H=[];u(v,G,r.toWireType(H,M));fh(H)}}});return[{name:b.name,fromWireType:k=>{var l={},n;for(n in h)l[n]=h[n].read(k);d(k);return l},toWireType:(k,l)=>{for(var n in h)if(!(n in l))throw new TypeError(`Missing field: "${n}"`);var p=c();for(n in h)h[n].write(p,l[n]);null!==k&&k.push(d,p);return p},L:nh,readValueFromPointer:gh,J:d}]})};cc.g="vp";
var oh,U=a=>{for(var b="";y[a];)b+=oh[y[a++]];return b},V,ph=a=>{throw new V(a);};function qh(a,b,c={}){var d=b.name;if(!a)throw new V(`type "${d}" must have a positive integer typeid pointer`);if(ih.hasOwnProperty(a)){if(c.Nb)return;throw new V(`Cannot register type '${d}' twice`);}ih[a]=b;delete jh[a];hh.hasOwnProperty(a)&&(b=hh[a],delete hh[a],b.forEach(e=>e()))}function lh(a,b,c={}){return qh(a,b,c)}
var dc=(a,b,c,d,e)=>{b=U(b);if(d)a:switch(c){case 4:d=za;break a;case 8:d=Ba;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?x:y;break a;case 2:d=e?z:A;break a;case 4:d=e?B:C;break a;case 8:d=e?D:Aa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);lh(a,{name:b,fromWireType:h=>{for(var k=C[h>>2],l=Array(k),n=h+Math.max(4,c)>>g,p=0;p<k;++p)l[p]=f[n+p];W(h);return l},toWireType:(h,k)=>{"number"==typeof k&&
(k=[k]);if(!Array.isArray(k))throw new V("Cannot pass non-array to C++ vector type "+b);k=Array.prototype.concat.apply([],k);var l=k.length,n=Math.max(4,c),p=rh(n+l*c);n=p+n>>g;C[p>>2]=l;f.set(k,n);null!==h&&h.push(W,p);return p},L:nh,readValueFromPointer:gh,J(h){W(h)}})};dc.g="vpppii";
var sh=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},th=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>y[d];case 2:return c?d=>z[d>>1]:d=>A[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];case 8:return c?d=>D[d>>3]:d=>Aa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ec=(a,b,c)=>{b=U(b);var d=b.includes("u");lh(a,{name:b,fromWireType:e=>e,toWireType:function(e,f){if("bigint"!=typeof f&&"number"!=typeof f)throw new TypeError(`Cannot convert "${sh(f)}" to ${this.name}`);
"number"==typeof f&&(f=BigInt(f));return f},L:nh,readValueFromPointer:th(b,c,!d),J:null})};ec.g="vpppjj";var nh=8,fc=(a,b,c,d)=>{b=U(b);lh(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},L:nh,readValueFromPointer:function(e){return this.fromWireType(y[e])},J:null})};fc.g="vppii";
var uh=a=>{throw new V(a.l.D.v.name+" instance already deleted");},vh=!1,wh=!1,xh=()=>{},yh=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=yh(a,b,c.M);return null===a?null:c.zb(a)},zh={},Ah={},Bh=(a,b)=>{if(void 0===b)throw new V("ptr should not be undefined");for(;a.M;)b=a.ra(b),a=a.M;return Ah[b]},Dh=(a,b)=>{if(!b.D||!b.s)throw new kh("makeClassHandle requires ptr and ptrType");if(!!b.O!==!!b.I)throw new kh("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ch(Object.create(a,
{l:{value:b,writable:!0}}))},Ch=a=>{if(vh)return Ch=b=>b.deleteLater(),Ch(a);if("undefined"===typeof FinalizationRegistry)return Ch=b=>b,a;wh=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.I?b.O.X(b.I):b.D.v.X(b.s))});Ch=b=>{var c=b.l;c.I&&wh.register(b,{l:c},b);return b};xh=b=>{wh.unregister(b)};return Ch(a)},Eh=[],Fh=()=>{for(;Eh.length;){var a=Eh.pop();a.l.ea=!1;a["delete"]()}},Gh;function Hh(){}
var Ih=(a,b)=>Object.defineProperty(b,"name",{value:a}),Jh=(a,b,c)=>{if(void 0===a[b].F){var d=a[b];a[b]=function(...e){if(!a[b].F.hasOwnProperty(e.length))throw new V(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].F})!`);return a[b].F[e.length].apply(this,e)};a[b].F=[];a[b].F[d.ca]=d}},Kh=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].F&&void 0!==m[a].F[c])throw new V(`Cannot register public name '${a}' twice`);Jh(m,a,a);if(m[a].F.hasOwnProperty(c))throw new V(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].F[c]=b}else m[a]=b,m[a].ca=c},Lh=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Mh(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.aa=c;this.X=d;this.M=e;this.Eb=f;this.ra=g;this.zb=h;this.cc=[]}var Nh=(a,b,c)=>{for(;b!==c;){if(!b.ra)throw new V(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ra(a);b=b.M}return a};
function Oh(a,b){if(null===b){if(this.Ka)throw new V(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new V(`Cannot pass "${sh(b)}" as a ${this.name}`);if(!b.l.s)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);return Nh(b.l.s,b.l.D.v,this.v)}
function Ph(a,b){if(null===b){if(this.Ka)throw new V(`null is not a valid ${this.name}`);if(this.xa){var c=this.Na();null!==a&&a.push(this.X,c);return c}return 0}if(!b||!b.l)throw new V(`Cannot pass "${sh(b)}" as a ${this.name}`);if(!b.l.s)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&b.l.D.va)throw new V(`Cannot convert argument of type ${b.l.O?b.l.O.name:b.l.D.name} to parameter type ${this.name}`);c=Nh(b.l.s,b.l.D.v,this.v);if(this.xa){if(void 0===b.l.I)throw new V("Passing raw pointer to smart pointer is illegal");
switch(this.jc){case 0:if(b.l.O===this)c=b.l.I;else throw new V(`Cannot convert argument of type ${b.l.O?b.l.O.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.I;break;case 2:if(b.l.O===this)c=b.l.I;else{var d=b.clone();c=this.dc(c,Qh(()=>d["delete"]()));null!==a&&a.push(this.X,c)}break;default:throw new V("Unsupporting sharing policy");}}return c}
function Rh(a,b){if(null===b){if(this.Ka)throw new V(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new V(`Cannot pass "${sh(b)}" as a ${this.name}`);if(!b.l.s)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.va)throw new V(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return Nh(b.l.s,b.l.D.v,this.v)}
function Sh(a,b,c,d,e,f,g,h,k,l,n){this.name=a;this.v=b;this.Ka=c;this.va=d;this.xa=e;this.ac=f;this.jc=g;this.gb=h;this.Na=k;this.dc=l;this.X=n;e||void 0!==b.M?this.toWireType=Ph:(this.toWireType=d?Oh:Rh,this.J=null)}
var Th=(a,b,c)=>{if(!m.hasOwnProperty(a))throw new kh("Replacing nonexistent public symbol");void 0!==m[a].F&&void 0!==c?m[a].F[c]=b:(m[a]=b,m[a].ca=c)},X=(a,b)=>{a=U(a);var c=N(b);if("function"!=typeof c)throw new V(`unknown function pointer with signature ${a}: ${b}`);return c},Uh,Wh=a=>{a=Vh(a);var b=U(a);W(a);return b},Xh=(a,b)=>{function c(f){e[f]||ih[f]||(jh[f]?jh[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Uh(`${a}: `+d.map(Wh).join([", "]));},gc=(a,b,c,d,e,f,g,
h,k,l,n,p,q)=>{n=U(n);f=X(e,f);h&&=X(g,h);l&&=X(k,l);q=X(p,q);var r=Lh(n);Kh(r,function(){Xh(`Cannot construct ${n} due to unbound types`,[d])});mh([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.v;var G=v.aa}else G=Hh.prototype;u=Ih(n,function(...ia){if(Object.getPrototypeOf(this)!==M)throw new V("Use 'new' to construct "+n);if(void 0===H.da)throw new V(n+" has no accessible constructor");var L=H.da[ia.length];if(void 0===L)throw new V(`Tried to invoke ctor of ${n} with invalid number of parameters (${ia.length}) - expected (${Object.keys(H.da).toString()}) parameters instead!`);
return L.apply(this,ia)});var M=Object.create(G,{constructor:{value:u}});u.prototype=M;var H=new Mh(n,u,M,q,v,f,h,l);if(H.M){var Q;(Q=H.M).sa??(Q.sa=[]);H.M.sa.push(H)}v=new Sh(n,H,!0,!1,!1);Q=new Sh(n+"*",H,!1,!1,!1);G=new Sh(n+" const*",H,!1,!0,!1);zh[a]={pointerType:Q,wb:G};Th(r,u);return[v,Q,G]})};gc.g="vppppppppppppp";function Yh(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].J)return!0;return!1}
function Zh(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ih(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function $h(a,b,c,d,e,f){var g=b.length;if(2>g)throw new V("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Yh(b);c="void"!==b[0].name;d=[a,ph,d,e,fh,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].J&&d.push(b[e].J);k=Yh(b);e=b.length-2;var l=[],n=["fn"];h&&n.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),n.push(`arg${g}Wired`);l=l.join(",");n=n.join(",");l=`return function (${l}) {\n`;k&&
(l+="var destructors = [];\n");var p=k?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(l+=`var thisWired = classParam['toWireType'](${p}, this);\n`);for(g=0;g<e;++g)l+=`var arg${g}Wired = argType${g}['toWireType'](${p}, arg${g});\n`,q.push(`argType${g}`);l+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(k)l+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].J&&(l+=`${f}_dtor(${f});\n`,
q.push(`${f}_dtor`));c&&(l+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [r,u]=[q,l+"}\n"];r.push(u);b=Zh(r)(...d);return Ih(a,b)}
var ai=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},bi=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},hc=(a,b,c,d,e,f,g,h)=>{var k=ai(c,d);b=U(b);b=bi(b);f=X(e,f);mh([],[a],l=>{function n(){Xh(`Cannot call ${p} due to unbound types`,k)}l=l[0];var p=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=l.v.constructor;void 0===q[b]?(n.ca=c-1,q[b]=n):(Jh(q,b,p),q[b].F[c-1]=n);mh([],k,r=>{r=$h(p,[r[0],null].concat(r.slice(1)),null,f,g,h);void 0===
q[b].F?(r.ca=c-1,q[b]=r):q[b].F[c-1]=r;if(l.v.sa)for(const u of l.v.sa)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})};hc.g="vppippppii";
var ic=(a,b,c,d,e,f)=>{var g=ai(b,c);e=X(d,e);mh([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.v.da&&(h.v.da=[]);if(void 0!==h.v.da[b-1])throw new V(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.v.da[b-1]=()=>{Xh(`Cannot construct ${h.name} due to unbound types`,g)};mh([],g,l=>{l.splice(1,0,null);h.v.da[b-1]=$h(k,l,null,e,f);
return[]});return[]})};ic.g="vpipppp";
var jc=(a,b,c,d,e,f,g,h,k)=>{var l=ai(c,d);b=U(b);b=bi(b);f=X(e,f);mh([],[a],n=>{function p(){Xh(`Cannot call ${q} due to unbound types`,l)}n=n[0];var q=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&n.v.cc.push(b);var r=n.v.aa,u=r[b];void 0===u||void 0===u.F&&u.className!==n.name&&u.ca===c-2?(p.ca=c-2,p.className=n.name,r[b]=p):(Jh(r,b,q),r[b].F[c-2]=p);mh([],l,v=>{v=$h(q,v,n,f,g,k);void 0===r[b].F?(v.ca=c-2,r[b]=v):r[b].F[c-2]=v;return[]});return[]})};jc.g="vppippppiii";
var ci=(a,b,c)=>{if(!(a instanceof Object))throw new V(`${c} with invalid "this": ${a}`);if(!(a instanceof b.v.constructor))throw new V(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.s)throw new V(`cannot call emscripten binding method ${c} on deleted object`);return Nh(a.l.s,a.l.D.v,b.v)},kc=(a,b,c,d,e,f,g,h,k,l)=>{b=U(b);e=X(d,e);mh([],[a],n=>{n=n[0];var p=`${n.name}.${b}`,q={get(){Xh(`Cannot access ${p} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};q.set=
k?()=>Xh(`Cannot access ${p} due to unbound types`,[c,g]):()=>{throw new V(p+" is a read-only property");};Object.defineProperty(n.v.aa,b,q);mh([],k?[c,g]:[c],r=>{var u=r[0],v={get(){var M=ci(this,n,p+" getter");return u.fromWireType(e(f,M))},enumerable:!0};if(k){k=X(h,k);var G=r[1];v.set=function(M){var H=ci(this,n,p+" setter"),Q=[];k(l,H,G.toWireType(Q,M));fh(Q)}}Object.defineProperty(n.v.aa,b,v);return[]});return[]})};kc.g="vpppppppppp";
var di=[],ei=[],Mc=a=>{9<a&&0===--ei[a+1]&&(ei[a]=void 0,di.push(a))};Mc.g="vp";var Y=a=>{if(!a)throw new V("Cannot use deleted val. handle = "+a);return ei[a]},Qh=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=di.pop()||ei.length;ei[b]=a;ei[b+1]=1;return b}},fi={name:"emscripten::val",fromWireType:a=>{var b=Y(a);Mc(a);return b},toWireType:(a,b)=>Qh(b),L:nh,readValueFromPointer:gh,J:null},lc=a=>lh(a,fi);lc.g="vp";
var gi=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(x[d])}:function(d){return this.fromWireType(y[d])};case 2:return c?function(d){return this.fromWireType(z[d>>1])}:function(d){return this.fromWireType(A[d>>1])};case 4:return c?function(d){return this.fromWireType(B[d>>2])}:function(d){return this.fromWireType(C[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},mc=(a,b,c,d)=>{function e(){}b=U(b);e.values={};lh(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},
toWireType:(f,g)=>g.value,L:nh,readValueFromPointer:gi(b,c,d),J:null});Kh(b,e)};mc.g="vpppi";var hi=(a,b)=>{var c=ih[a];if(void 0===c)throw a=`${b} has unknown type ${Wh(a)}`,new V(a);return c},nc=(a,b,c)=>{var d=hi(a,"enum");b=U(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ih(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d};nc.g="vppi";
var ii=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(za[c>>2])};case 8:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},oc=(a,b,c)=>{b=U(b);lh(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,L:nh,readValueFromPointer:ii(b,c),J:null})};oc.g="vppp";
var pc=(a,b,c,d,e,f,g)=>{var h=ai(b,c);a=U(a);a=bi(a);e=X(d,e);Kh(a,function(){Xh(`Cannot call ${a} due to unbound types`,h)},b-1);mh([],h,k=>{Th(a,$h(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};pc.g="vpippppii";var qc=(a,b,c,d,e)=>{b=U(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var g=b.includes("unsigned")?function(h,k){return k>>>0}:function(h,k){return k};lh(a,{name:b,fromWireType:e,toWireType:g,L:nh,readValueFromPointer:th(b,c,0!==d),J:null})};
qc.g="vpppii";var rc=(a,b,c)=>{function d(f){return new e(x.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=U(c);lh(a,{name:c,fromWireType:d,L:nh,readValueFromPointer:d},{Nb:!0})};rc.g="vpip";
var sc=(a,b)=>{b=U(b);var c="std::string"===b;lh(a,{name:b,fromWireType:function(d){var e=C[d>>2],f=d+4;if(c)for(var g=f,h=0;h<=e;++h){var k=f+h;if(h==e||0==y[k]){g=R(g,k-g);if(void 0===l)var l=g;else l+=String.fromCharCode(0),l+=g;g=k+1}}else{l=Array(e);for(h=0;h<e;++h)l[h]=String.fromCharCode(y[f+h]);l=l.join("")}W(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof
Int8Array))throw new V("Cannot pass non-string to std::string");var g=c&&f?ug(e):e.length;var h=rh(4+g+1),k=h+4;C[h>>2]=g;if(c&&f)vg(e,y,k,g+1);else if(f)for(f=0;f<g;++f){var l=e.charCodeAt(f);if(255<l)throw W(k),new V("String has UTF-16 code units that do not fit in 8 bits");y[k+f]=l}else y.set(e,k);null!==d&&d.push(W,h);return h},L:nh,readValueFromPointer:gh,J(d){W(d)}})};sc.g="vpp";
var li=new TextDecoder("utf-16le"),mi=(a,b)=>{var c=a>>1;for(b=c+b/2;!(c>=b)&&A[c];)++c;return li.decode(y.slice(a,c<<1))},ni=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},oi=a=>2*a.length,pi=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=B[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},qi=(a,b,c)=>{c??=2147483647;
if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},ri=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},tc=(a,b,c)=>{c=U(c);if(2===b){var d=mi;var e=ni;var f=oi;var g=h=>A[h>>1]}else 4===b&&(d=pi,e=qi,f=ri,g=h=>C[h>>2]);lh(a,{name:c,fromWireType:h=>{for(var k=C[h>>2],l,n=h+4,p=0;p<=k;++p){var q=
h+4+p*b;if(p==k||0==g(q))n=d(n,q-n),void 0===l?l=n:(l+=String.fromCharCode(0),l+=n),n=q+b}W(h);return l},toWireType:(h,k)=>{if("string"!=typeof k)throw new V(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),n=rh(4+l+b);C[n>>2]=l/b;e(k,n+4,l+b);null!==h&&h.push(W,n);return n},L:nh,readValueFromPointer:gh,J(h){W(h)}})};tc.g="vppp";var uc=(a,b,c,d,e,f)=>{eh[a]={name:U(b),Na:X(c,d),X:X(e,f),Xa:[]}};uc.g="vpppppp";
var vc=(a,b,c,d,e,f,g,h,k,l)=>{eh[a].Xa.push({Cb:U(b),Ib:c,ka:X(d,e),Hb:f,fc:g,ec:X(h,k),hc:l})};vc.g="vpppppppppp";var wc=(a,b)=>{b=U(b);lh(a,{Ub:!0,name:b,L:0,fromWireType:()=>{},toWireType:()=>{}})};wc.g="vpp";var xc=(a,b,c,d)=>{function e(h){var k=R(a+36);ch(`'Could not load dynamic lib: ${k}\n${h}`);--Ge;bf(()=>N(c)(a,d))}function f(){--Ge;bf(()=>N(b)(a,d))}Ge+=1;var g=dh(a,{G:!0});g?g.then(f,e):e()};xc.g="vpppp";var yc=()=>{for(const a of Object.keys(Ie)){const b=Number(a);Je.has(b)||si(b)}};
yc.g="v";function ti(a){var b=ui;b.$[a]=void 0;b.N.push(a)}class vi{constructor(){this.$=[void 0];this.N=[]}get(a){return this.$[a]}has(a){return void 0!==this.$[a]}ba(a){var b=this.N.pop()||this.$.length;this.$[b]=a;return b}}
var ui=new vi,wi=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=ui.ba(a);return a},zc=(a,b,c)=>{const d=[];0===Object.keys(Ke).length||jb();var e=wi();d.push(e.promise);xi(e.id);for(const f of Object.keys(Ie)){const g=Number(f);g===a||Je.has(g)||(e=wi(),yi(g,e.id),Ke[g]=e,d.push(e.promise))}Promise.all(d).then(()=>{Ke={};N(b)(c)})};zc.g="vppp";
function Ac(){var a=rh(4*(ta.length+1)),b=a;ta.forEach(c=>{var d=C,e=b>>2,f=ug(c)+1,g=rh(f);g&&vg(c,y,g,f);d[e]=g;b+=4});C[b>>2]=0;return a}Ac.g="p";var Bc=()=>1;Bc.g="i";var Cc=a=>{Ja(a,!ea,1,!da,262144,!1);Ka()};Cc.g="vp";var La=a=>{"function"===typeof Atomics.qc&&(Atomics.qc(B,a>>2,a).value.then(Oa),Atomics.store(B,a+128>>2,1))};La.g="vp";var Oa=()=>{var a=Fa();a&&(La(a),bf(zi))},Dc=(a,b)=>{a==b?setTimeout(Oa):t?postMessage({Ca:a,P:"checkMailbox"}):(a=Ie[a])&&a.postMessage({P:"checkMailbox"})};
Dc.g="vpp";var Ai=[],Ec=(a,b,c,d,e)=>{d/=2;Ai.length=d;c=e>>3;for(e=0;e<d;e++)Ai[e]=D[c+2*e]?D[c+2*e+1]:Ba[c+2*e+1];return(b?Be[b]:Bi[a])(...Ai)};Ec.g="dippip";var Fc=()=>{Xe=!1;Ge=0};Fc.g="v";var Gc=a=>{t?postMessage({P:"cleanupThread",Qa:a}):Oe(a)};Gc.g="vp";var Hc=a=>{t?postMessage({P:"markAsFinished",Qa:a}):(Je.add(a),a in Ke&&Ke[a].resolve())};Hc.g="vp";var Ic=()=>{};Ic.g="vp";var Jc=()=>{throw new lb;};Jc.g="v";
var Ci=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(C[b>>2]=Qh(d));return a},Kc=(a,b,c)=>{a=Y(a);b=hi(b,"emval::as");return Ci(b,c,a)};Kc.g="dppp";var Di=[],Lc=(a,b,c,d)=>{a=Di[a];b=Y(b);return a(null,b,c,d)};Lc.g="dpppp";var Ei={},Fi=a=>{var b=Ei[a];return void 0===b?U(a):b},Gi=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Nc=a=>{if(0===a)return Qh(Gi());a=Fi(a);return Qh(Gi()[a])};Nc.g="pp";
var Hi=a=>{var b=Di.length;Di.push(a);return b},Ii=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=hi(C[b+4*d>>2],"parameter "+d);return c},Oc=(a,b,c)=>{b=Ii(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,g=[];0===c&&g.push("obj");for(var h=["retType"],k=[d],l=0;l<a;++l)g.push("arg"+l),h.push("argType"+l),k.push(b[l]),e+=`  var arg${l} = argType${l}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[l].L;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;
d.Ub||(h.push("emval_returnValue"),k.push(Ci),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");h.push(e+"};\n");a=Zh(h)(...k);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return Hi(Ih(c,a))};Oc.g="pipi";var Pc=a=>{a=Fi(a);return Qh(m[a])};Pc.g="pp";var Qc=(a,b)=>{a=Y(a);b=Y(b);return Qh(a[b])};Qc.g="ppp";var Rc=a=>{9<a&&(ei[a+1]+=1)};Rc.g="vp";var Sc=(a,b)=>{a=Y(a);b=Y(b);return a instanceof b};Sc.g="ipp";var Tc=a=>{a=Y(a);return"number"==typeof a};Tc.g="ip";
var Uc=a=>{a=Y(a);return"string"==typeof a};Uc.g="ip";var Vc=a=>Qh(Fi(a));Vc.g="pp";var Wc=a=>{var b=Y(a);fh(b);Mc(a)};Wc.g="vp";var Xc=(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c};Xc.g="vppp";var Yc=(a,b)=>{a=hi(a,"_emval_take_value");a=a.readValueFromPointer(b);return Qh(a)};Yc.g="ppp";var Zc=a=>{a=Y(a);return Qh(typeof a)};Zc.g="pp";
function $c(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getUTCSeconds();B[b+4>>2]=a.getUTCMinutes();B[b+8>>2]=a.getUTCHours();B[b+12>>2]=a.getUTCDate();B[b+16>>2]=a.getUTCMonth();B[b+20>>2]=a.getUTCFullYear()-1900;B[b+24>>2]=a.getUTCDay();B[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}$c.g="vjp";var Ji=[0,31,60,91,121,152,182,213,244,274,305,335],Ki=[0,31,59,90,120,151,181,212,243,273,304,334];
function ad(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=a.getFullYear();B[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ki:Ji)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}ad.g="vjp";function bd(a,b,c,d,e,f,g){if(t)return O(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var h=T(d),k=FS.ga(h,a,e,b,c),l=k.s;B[f>>2]=k.$;C[g>>2]=l;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.B}}bd.g="ipiiijpp";
function cd(a,b,c,d,e,f){if(t)return O(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=T(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.ia(g,y.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.B}}cd.g="ippiiij";
var dd=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();C[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(vg(a,y,c,17),vg(b,y,d,17)):(vg(a,y,d,17),vg(b,y,c,17))};dd.g="vpppp";var ed=()=>{};ed.g="v";var fd=a=>{console.error(R(a))};fd.g="vp";var gd=()=>Date.now();gd.g="d";var hd=a=>w(R(a));
hd.g="vp";var jd=()=>{Ge+=1;throw"unwind";};jd.g="v";var kd=()=>y.length;kd.g="p";var ld=()=>performance.timeOrigin+performance.now();ld.g="d";var md=()=>navigator.hardwareConcurrency;md.g="i";var nd=a=>{ti(a)};nd.g="vp";var od=(a,b,c)=>{a=ui.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(ui.get(c).promise);break;case 2:a.resolve(ui.get(c).promise);ti(c);break;case 3:a.reject(c)}};od.g="vpip";var pd=()=>!1;pd.g="ip";
var Mi=()=>{if(!Li){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:la||"./this.program"},b;for(b in $g)void 0===$g[b]?delete a[b]:a[b]=$g[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Li=c}return Li},Li;
function qd(a,b){if(t)return O(19,1,a,b);var c=0;Mi().forEach((d,e)=>{var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)x[e++]=d.charCodeAt(f);x[e]=0;c+=d.length+1});return 0}qd.g="ipp";function rd(a,b){if(t)return O(20,1,a,b);var c=Mi();C[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);C[b>>2]=d;return 0}rd.g="ipp";function td(a){if(t)return O(21,1,a);try{var b=T(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}td.g="ii";
function ud(a,b){if(t)return O(22,1,a,b);try{var c=T(a),d=c.A?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;x[b]=d;z[b+2>>1]=0;D[b+8>>3]=BigInt(0);D[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}ud.g="iip";
function vd(a,b,c,d){if(t)return O(23,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],k=C[a+4>>2];a+=8;var l=FS.read(e,x,h,k,f);if(0>l){var n=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}n=b}C[d>>2]=n;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.B}}vd.g="iippp";
function wd(a,b,c,d){if(t)return O(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=T(a);FS.llseek(e,b,c);D[d>>3]=BigInt(e.position);e.Ga&&0===b&&0===c&&(e.Ga=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}wd.g="iijip";
function xd(a,b,c,d){if(t)return O(25,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],k=C[a+4>>2];a+=8;var l=FS.write(e,x,h,k,f);if(0>l){var n=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}n=b}C[d>>2]=n;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.B}}xd.g="iippp";var zd=(a,b)=>{qg(y.subarray(a,a+b));return 0};zd.g="ipp";function Ad(...a){return F.heif_error_success(...a)}Ad.ja=!0;
function Bd(...a){return F.heif_image_release(...a)}Bd.ja=!0;function Cd(...a){return F.heif_nclx_color_profile_free(...a)}Cd.ja=!0;var ye=a=>a;ye.g="vp";var Ni=FS.createPath,Oi=FS.createLazyFile,Pi=FS.createDevice;m.incrementExceptionRefcount=a=>dg(a);m.decrementExceptionRefcount=a=>gg(a);var nb=a=>{var b=J(),c=De(4),d=De(4);Qi(a,c,d);a=C[c>>2];d=C[d>>2];c=R(a);W(a);if(d){var e=R(d);W(d)}K(b);return[c,e]};m.getExceptionMessage=a=>nb(a);
m.requestFullscreen=function(a,b){function c(){ff=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=pf,nf&&d.requestPointerLock(),ff=!0,of?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),sf(m.canvas),rf()):sf(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),of?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=
C[SDL.screen>>2]&-8388609),sf(m.canvas),rf()):sf(d));m.onFullScreen?.(ff);m.onFullscreen?.(ff)}nf=a;of=b;"undefined"==typeof nf&&(nf=!0);"undefined"==typeof of&&(of=!1);var d=m.canvas;mf||(mf=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};m.setCanvasSize=function(a,b,c){sf(m.canvas,a,b);c||rf()};m.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
m.createContext=function(a,b,c,d){if(b&&m.Sa&&a==m.canvas)return m.Sa;var e;if(b){var f={antialias:!1,alpha:!1,Ec:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof GL&&(e=GL.Ac(a,f)))var h=GL.getContext(e).uc}else h=a.getContext("2d");if(!h)return null;c&&(m.Sa=h,b&&GL.Fc(e),hf.forEach(k=>k()),jf());return h};t||Te();
(()=>{var a={promiseChainEnd:Promise.resolve(),canHandle:b=>!m.noWasmDecoding&&b.endsWith(".so"),handle:(b,c,d,e)=>{a.promiseChainEnd=a.promiseChainEnd.then(()=>Xf(b,{G:!0,ma:!0},c,{})).then(f=>{ef[c]=f;d(b)},f=>{w(`failed to instantiate wasm: ${c}: ${f}`);e()})}};df.push(a)})();FS.createPreloadedFile=Hg;[44].forEach(a=>{FS.Fa[a]=new FS.h(a);FS.Fa[a].stack="<generic error, no stack>"});FS.U=Array(4096);FS.mount(S,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g});FS.mkdev("/dev/null",FS.makedev(1,3));yg(FS.makedev(5,0),Ag);yg(FS.makedev(6,0),Bg);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=qg(a).byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.m={fa(c,d){var e=T(+d);c={parent:null,mount:{eb:"fake"},m:{readlink:()=>e.path}};return c.parent=c}};return b}},{},"/proc/self/fd")})();FS.Db={MEMFS:S};m.FS_createPath=FS.createPath;m.FS_createDataFile=FS.createDataFile;m.FS_createPreloadedFile=FS.createPreloadedFile;m.FS_unlink=FS.unlink;m.FS_createLazyFile=FS.createLazyFile;m.FS_createDevice=FS.createDevice;
kh=m.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Ri=Array(256),Si=0;256>Si;++Si)Ri[Si]=String.fromCharCode(Si);oh=Ri;V=m.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Hh.prototype,{isAliasOf:function(a){if(!(this instanceof Hh&&a instanceof Hh))return!1;var b=this.l.D.v,c=this.l.s;a.l=a.l;var d=a.l.D.v;for(a=a.l.s;b.M;)c=b.ra(c),b=b.M;for(;d.M;)a=d.ra(a),d=d.M;return b===d&&c===a},clone:function(){this.l.s||uh(this);if(this.l.na)return this.l.count.value+=1,this;var a=Ch,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.l;a=a(c.call(b,d,{l:{value:{count:e.count,ea:e.ea,na:e.na,s:e.s,D:e.D,I:e.I,O:e.O}}}));a.l.count.value+=1;a.l.ea=!1;return a},
["delete"](){this.l.s||uh(this);if(this.l.ea&&!this.l.na)throw new V("Object already scheduled for deletion");xh(this);var a=this.l;--a.count.value;0===a.count.value&&(a.I?a.O.X(a.I):a.D.v.X(a.s));this.l.na||(this.l.I=void 0,this.l.s=void 0)},isDeleted:function(){return!this.l.s},deleteLater:function(){this.l.s||uh(this);if(this.l.ea&&!this.l.na)throw new V("Object already scheduled for deletion");Eh.push(this);1===Eh.length&&Gh&&Gh(Fh);this.l.ea=!0;return this}});
Object.assign(Sh.prototype,{Gb(a){this.gb&&(a=this.gb(a));return a},Ua(a){this.X?.(a)},L:nh,readValueFromPointer:gh,fromWireType:function(a){function b(){return this.xa?Dh(this.v.aa,{D:this.ac,s:c,O:this,I:a}):Dh(this.v.aa,{D:this,s:a})}var c=this.Gb(a);if(!c)return this.Ua(a),null;var d=Bh(this.v,c);if(void 0!==d){if(0===d.l.count.value)return d.l.s=c,d.l.I=a,d.clone();d=d.clone();this.Ua(a);return d}d=this.v.Eb(c);d=zh[d];if(!d)return b.call(this);d=this.va?d.wb:d.pointerType;var e=yh(c,this.v,
d.v);return null===e?b.call(this):this.xa?Dh(d.v.aa,{D:d,s:e,O:this,I:a}):Dh(d.v.aa,{D:d,s:e})}});Uh=m.UnboundTypeError=((a,b)=>{var c=Ih(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ei.push(0,1,void 0,1,null,1,!0,1,!1,1);m.count_emval_handles=()=>ei.length/2-5-di.length;ab(()=>{$g.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;$g.VIPS_CONCURRENCY=1});
Ta.unshift(()=>{const a=Object.getOwnPropertyDescriptor(m.SourceCustom.prototype,"onRead");Object.defineProperty(m.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>Qh(c(d)))}});const b=Object.getOwnPropertyDescriptor(m.TargetCustom.prototype,"onWrite");Object.defineProperty(m.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Y(d)))}})});Object.assign(Hh.prototype,{preventAutoDelete:function(){const a=Eh.indexOf(this);-1<a&&Eh.splice(a,1);this.l.ea=!1;return this}});
var Bi=[ze,Ye,jg,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,bd,cd,qd,rd,td,ud,vd,wd,xd],F,Z=function(){function a(c,d){Z=c.exports;Z=Nf(Z,1024);var e=zf(d);Yf(Z);Ef("__main__",0,F);$f();Vf(Z._emscripten_tls_init,c.exports,e);Ta.unshift(Z.__wasm_call_ctors);Xa.push(Z.__wasm_apply_data_relocs);wa=d;ib("wasm-instantiate");return Z}var b=Ga();hb("wasm-instantiate");if(m.instantiateWasm)try{return m.instantiateWasm(b,a)}catch(c){w(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}ob??=m.locateFile?
kb("vips.wasm")?"vips.wasm":oa("vips.wasm"):(new URL("vips.wasm",import.meta.url)).href;sb(b,function(c){a(c.instance,c.module)}).catch(ba);return{}}(),Vh=a=>(Vh=Z.__getTypeName)(a),Ma=()=>(Ma=Z._embind_initialize_bindings)(),Fa=()=>(Fa=Z.pthread_self)(),rh=a=>(rh=Z.malloc)(a);m._main=(a,b)=>(m._main=Z.main)(a,b);var W=a=>(W=Z.free)(a),$e=a=>($e=Z.fflush)(a),Gf=(a,b)=>(Gf=Z.calloc)(a,b);m._emscripten_builtin_free=a=>(m._emscripten_builtin_free=Z.emscripten_builtin_free)(a);
var Cg=(a,b)=>(Cg=Z.emscripten_builtin_memalign)(a,b);m._emscripten_builtin_malloc=a=>(m._emscripten_builtin_malloc=Z.emscripten_builtin_malloc)(a);var Ze=()=>(Ze=Z.__funcs_on_exit)();m.___libc_calloc=(a,b)=>(m.___libc_calloc=Z.__libc_calloc)(a,b);m.___libc_free=a=>(m.___libc_free=Z.__libc_free)(a);m.___libc_malloc=a=>(m.___libc_malloc=Z.__libc_malloc)(a);
var bh=(a,b)=>(bh=Z.__dl_seterr)(a,b),xi=a=>(xi=Z._emscripten_dlsync_self_async)(a),Bf=()=>(Bf=Z._emscripten_dlsync_self)(),yi=(a,b)=>(yi=Z._emscripten_proxy_dlsync_async)(a,b),si=a=>(si=Z._emscripten_proxy_dlsync)(a),Ja=(a,b,c,d,e,f)=>(Ja=Z._emscripten_thread_init)(a,b,c,d,e,f),Pa=()=>(Pa=Z._emscripten_thread_crashed)(),We=(a,b,c,d,e)=>(We=Z._emscripten_run_on_main_thread_js)(a,b,c,d,e),Ne=a=>(Ne=Z._emscripten_thread_free_data)(a),af=a=>(af=Z._emscripten_thread_exit)(a),zi=()=>(zi=Z._emscripten_check_mailbox)();
m.__ZdaPvm=(a,b)=>(m.__ZdaPvm=Z._ZdaPvm)(a,b);m.__Znaj=a=>(m.__Znaj=Z._Znaj)(a);m.__ZnajSt11align_val_t=(a,b)=>(m.__ZnajSt11align_val_t=Z._ZnajSt11align_val_t)(a,b);m.__Znwj=a=>(m.__Znwj=Z._Znwj)(a);m.__ZnwjSt11align_val_t=(a,b)=>(m.__ZnwjSt11align_val_t=Z._ZnwjSt11align_val_t)(a,b);m.___libc_realloc=(a,b)=>(m.___libc_realloc=Z.__libc_realloc)(a,b);m._emscripten_builtin_calloc=(a,b)=>(m._emscripten_builtin_calloc=Z.emscripten_builtin_calloc)(a,b);m._malloc_size=a=>(m._malloc_size=Z.malloc_size)(a);
m._malloc_usable_size=a=>(m._malloc_usable_size=Z.malloc_usable_size)(a);m._reallocf=(a,b)=>(m._reallocf=Z.reallocf)(a,b);
var P=(a,b)=>(P=Z.setThrew)(a,b),hg=a=>(hg=Z._emscripten_tempret_set)(a),wf=(a,b)=>(wf=Z.emscripten_stack_set_limits)(a,b),K=a=>(K=Z._emscripten_stack_restore)(a),De=a=>(De=Z._emscripten_stack_alloc)(a),J=()=>(J=Z.emscripten_stack_get_current)(),dg=a=>(dg=Z.__cxa_increment_exception_refcount)(a),gg=a=>(gg=Z.__cxa_decrement_exception_refcount)(a),Qi=(a,b,c)=>(Qi=Z.__get_exception_message)(a,b,c),ig=(a,b,c)=>(ig=Z.__cxa_can_catch)(a,b,c),eg=a=>(eg=Z.__cxa_get_exception_ptr)(a);m.___THREW__=1200;
m.__ZTISt12length_error=1424580;m.__ZTVSt12length_error=1424560;m.__ZTVN10__cxxabiv120__si_class_type_infoE=1424252;m.__ZTVN10__cxxabiv117__class_type_infoE=1424212;m.__ZTISt20bad_array_new_length=1424452;m.___threwValue=1204;m._stdout=1417648;m._stderr=1417496;m._g_mem_gc_friendly=3345468;m._g_utf8_skip=1360660;m.__ZTVNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1428136;m.__ZTTNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1428552;
m.__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1428784;m.__ZTVNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1428492;m.__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1428744;m.__ZNSt3__24coutE=3408408;m.__ZNSt3__24cerrE=3408576;m.__ZNSt3__25ctypeIcE2idE=3405628;m.__ZTVNSt3__212bad_weak_ptrE=1424708;m.__ZTINSt3__212bad_weak_ptrE=1424728;m.__ZTINSt3__219__shared_weak_countE=1424768;m.__ZTISt9bad_alloc=1424464;
m.__ZSt7nothrow=937548;m.__ZTISt12out_of_range=1424612;m.__ZTVSt12out_of_range=1424592;m.__ZTVN10__cxxabiv121__vmi_class_type_infoE=1424304;function Zd(a,b){var c=J();try{N(a)(b)}catch(d){K(c);if(!(d instanceof E))throw d;P(1,0)}}function ge(a,b,c,d){var e=J();try{N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}function Kd(a,b,c){var d=J();try{return N(a)(b,c)}catch(e){K(d);if(!(e instanceof E))throw e;P(1,0)}}
function Jd(a,b){var c=J();try{return N(a)(b)}catch(d){K(c);if(!(d instanceof E))throw d;P(1,0)}}function Id(a){var b=J();try{return N(a)()}catch(c){K(b);if(!(c instanceof E))throw c;P(1,0)}}function Yd(a){var b=J();try{N(a)()}catch(c){K(b);if(!(c instanceof E))throw c;P(1,0)}}function ne(a,b,c,d,e){var f=J();try{N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function Fd(a,b,c,d){var e=J();try{return N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}
function be(a,b,c){var d=J();try{N(a)(b,c)}catch(e){K(d);if(!(e instanceof E))throw e;P(1,0)}}function Md(a,b,c,d){var e=J();try{return N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}function Pd(a,b,c,d,e,f){var g=J();try{return N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}function oe(a,b,c,d,e,f){var g=J();try{N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}
function Qd(a,b,c,d,e,f,g){var h=J();try{return N(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof E))throw k;P(1,0)}}function Nd(a,b,c,d,e){var f=J();try{return N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function ce(a,b,c,d){var e=J();try{N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}function de(a,b,c,d,e){var f=J();try{N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}
function Ld(a,b,c,d){var e=J();try{return N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}function $d(a,b,c){var d=J();try{N(a)(b,c)}catch(e){K(d);if(!(e instanceof E))throw e;P(1,0)}}function Gd(a,b,c,d,e){var f=J();try{return N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function Dd(a,b){var c=J();try{return N(a)(b)}catch(d){K(c);if(!(d instanceof E))throw d;P(1,0)}}
function te(a,b,c,d,e,f,g,h,k,l,n){var p=J();try{N(a)(b,c,d,e,f,g,h,k,l,n)}catch(q){K(p);if(!(q instanceof E))throw q;P(1,0)}}function pe(a,b,c,d,e,f,g){var h=J();try{N(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof E))throw k;P(1,0)}}function qe(a,b,c,d,e,f,g,h){var k=J();try{N(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof E))throw l;P(1,0)}}function Ed(a,b,c){var d=J();try{return N(a)(b,c)}catch(e){K(d);if(!(e instanceof E))throw e;P(1,0)}}
function fe(a,b,c,d,e){var f=J();try{N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function he(a,b,c,d,e){var f=J();try{N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function ae(a,b,c,d,e){var f=J();try{N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0)}}function ke(a,b,c,d,e,f,g,h){var k=J();try{N(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof E))throw l;P(1,0)}}
function ie(a,b,c,d,e,f,g,h,k,l){var n=J();try{N(a)(b,c,d,e,f,g,h,k,l)}catch(p){K(n);if(!(p instanceof E))throw p;P(1,0)}}function je(a,b,c,d,e,f,g,h,k){var l=J();try{N(a)(b,c,d,e,f,g,h,k)}catch(n){K(l);if(!(n instanceof E))throw n;P(1,0)}}function me(a,b,c,d,e,f){var g=J();try{N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}function le(a,b,c,d,e,f,g){var h=J();try{N(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof E))throw k;P(1,0)}}
function ve(a,b,c,d,e,f,g,h,k,l,n,p,q){var r=J();try{N(a)(b,c,d,e,f,g,h,k,l,n,p,q)}catch(u){K(r);if(!(u instanceof E))throw u;P(1,0)}}function ue(a,b,c,d,e,f,g,h,k,l,n,p){var q=J();try{N(a)(b,c,d,e,f,g,h,k,l,n,p)}catch(r){K(q);if(!(r instanceof E))throw r;P(1,0)}}function se(a,b,c,d,e,f,g,h,k,l){var n=J();try{N(a)(b,c,d,e,f,g,h,k,l)}catch(p){K(n);if(!(p instanceof E))throw p;P(1,0)}}
function re(a,b,c,d,e,f,g,h,k){var l=J();try{N(a)(b,c,d,e,f,g,h,k)}catch(n){K(l);if(!(n instanceof E))throw n;P(1,0)}}function we(a,b,c,d,e,f,g,h,k,l,n,p,q,r){var u=J();try{N(a)(b,c,d,e,f,g,h,k,l,n,p,q,r)}catch(v){K(u);if(!(v instanceof E))throw v;P(1,0)}}function ee(a,b,c,d,e,f){var g=J();try{N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}function Rd(a,b,c,d,e,f,g,h){var k=J();try{return N(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof E))throw l;P(1,0)}}
function Wd(a,b){var c=J();try{return N(a)(b)}catch(d){K(c);if(!(d instanceof E))throw d;P(1,0);return 0n}}function Ud(a,b,c,d,e,f,g,h,k,l,n,p,q){var r=J();try{return N(a)(b,c,d,e,f,g,h,k,l,n,p,q)}catch(u){K(r);if(!(u instanceof E))throw u;P(1,0)}}function Xd(a,b,c,d,e){var f=J();try{return N(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof E))throw g;P(1,0);return 0n}}function Hd(a,b,c,d){var e=J();try{return N(a)(b,c,d)}catch(f){K(e);if(!(f instanceof E))throw f;P(1,0)}}
function Sd(a,b,c,d,e,f,g,h,k,l,n){var p=J();try{return N(a)(b,c,d,e,f,g,h,k,l,n)}catch(q){K(p);if(!(q instanceof E))throw q;P(1,0)}}function Td(a,b,c,d,e,f,g,h,k,l,n,p){var q=J();try{return N(a)(b,c,d,e,f,g,h,k,l,n,p)}catch(r){K(q);if(!(r instanceof E))throw r;P(1,0)}}function xe(a,b,c,d,e,f,g,h,k,l,n,p,q,r,u,v){var G=J();try{N(a)(b,c,d,e,f,g,h,k,l,n,p,q,r,u,v)}catch(M){K(G);if(!(M instanceof E))throw M;P(1,0)}}
function Vd(a,b,c,d,e,f){var g=J();try{return N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}function Od(a,b,c,d,e,f){var g=J();try{return N(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof E))throw h;P(1,0)}}m.addRunDependency=hb;m.removeRunDependency=ib;m.ENV=$g;m.addFunction=Mf;m.FS_createPreloadedFile=Hg;m.FS_unlink=a=>FS.unlink(a);m.FS_createPath=Ni;m.FS_createDevice=Pi;m.FS=FS;m.FS_createDataFile=(a,b,c,d,e,f)=>{FS.createDataFile(a,b,c,d,e,f)};m.FS_createLazyFile=Oi;
m.setAutoDeleteLater=a=>{vh=a};m.deletionQueue=Eh;m.setDelayFunction=a=>{Gh=a;Eh.length&&Gh&&Gh(Fh)};var Ti,Ui;gb=function Vi(){Ti||Wi();Ti||(gb=Vi)};function Xi(a=[]){var b=Tf("main").Pa;if(b){a.unshift(la);var c=a.length,d=De(4*(c+1)),e=d;a.forEach(g=>{C[e>>2]=ah(g);e+=4});C[e>>2]=0;try{var f=b(c,d);sd(f,!0)}catch(g){Fe(g)}}}var Ha={};
function Wi(){var a=ka;function b(){if(!Ti&&(Ti=1,m.calledRun=1,!xa&&(cb(),t||bb(Ua),aa(m),m.onRuntimeInitialized?.(),Yi&&Xi(a),!t))){var c=m.postRun;c&&("function"==typeof c&&(c=[c]),c.forEach(db));bb(Wa)}}if(!(0<eb))if(t)aa(m),cb(),startWorker(m);else{if(!Ui&&(Ui=1,$a(),0<eb))return;m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);b()},1)):b()}}if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();
var Yi=!0;m.noInitialRun&&(Yi=!1);Wi();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Vips;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Vips();
